#ifndef __GAMEDEFINE_SCENE_H__
#define __GAMEDEFINE_SCENE_H__

enum MAP_STATUS { MAP_STATUS_SLEEP = 0, MAP_STATUS_SELECT, MAP_STATUS_LOAD, MAP_STATUS_INIT, MAP_STATUS_RUNNING, };

enum MAP_TYPE
{
	MAP_TYPE_INVALID	= -1,
	MAP_TYPE_GAMELOGIC,
	MAP_TYPE_FUBEN,
	MAP_TYPE_BATTLEFIELD,
	MAP_TYPE_ARENA,
	MAP_TYPE_CIT,
	MAP_TYPE_PRISON,
	MAP_TYPE_HOUSE,
	MAP_TYPE_MBATTLEFIELD,
	MAP_TYPE_MSIGNUP,
	MAP_TYPE_NUMBERS
};
#endif
