#ifndef __GAMEDEFINE_CITY_H__
#define __GAMEDEFINE_CITY_H__

#define MAX_CITY_PER_WORLD	200
#define MAX_CITY_PORT		5
#define MAX_CITY_BUILDING	1024
enum eCITY_ERROR_TYPE { CITY_ERROR_NOTHING = 0, CITY_ERROR_GUID_ON_WORKING, };

enum eUPDATE_CITY_ATT { CITY_UPDATE_CITY_LEVEL = 0, CITY_UPDATE_CITY_NAME, CITY_UPDATE_BUILDING, CITY_UPDATE_MAX, };
#endif
