language: cpp
dist: trusty
matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-7
                    - cmake
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - os: linux
          compiler: clang
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                    - llvm-toolchain-trusty
                packages:
                    - clang-9
                    - cmake
          env:
            - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang
          
before_script:
    - eval "${MATRIX_EVAL}"          
    - travis_wait cmake -H. -B./build
    - cd ./build
script:
    - travis_wait make
notifications:
    email: false
