/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef AUTHORS_GEN_H
#define AUTHORS_GEN_H
const char *const AUTHORS_FOUNDERS[] = {
	"Juan Linietsky (reduz)",
	"Ariel Manzur (punto-)",
	0
};
const char *const AUTHORS_LEAD_DEVELOPERS[] = {
	"Juan Linietsky (reduz)",
	0
};
const char *const AUTHORS_PROJECT_MANAGERS[] = {
	"R\303\251mi Verschelde (akien-mga)",
	0
};
const char *const AUTHORS_DEVELOPERS[] = {
	"Aaron Franke (aaronfranke)",
	"Aaron Pagano (aaronp64)",
	"Aaron Record (LightningAA)",
	"Adam Scott (adamscott)",
	"Alexander Hartmann (Alex2782)",
	"Alexander Holland (AlexHolly)",
	"Alex Drozd (brno32)",
	"Alexey Khoroshavin (allkhor)",
	"Alfred Reinold Baudisch (alfredbaudisch)",
	"Alistair Leslie-Hughes (alesliehughes)",
	"Alket Rexhepi (alketii)",
	"Alvin Wong (alvinhochun)",
	"Andrea Catania (AndreaCatania)",
	"Andreia Gaita (shana)",
	"Andrii Doroshenko (Xrayez)",
	"Andy Maloney (asmaloney)",
	"Andy Moss (MillionOstrich)",
	"Angad Kambli (angad-k)",
	"Anilforextra (AnilBK)",
	"Anish Bhobe (KidRigger)",
	"Anni Ryyn\303\244nen (anniryynanen)",
	"Anton Yabchinskiy (a12n)",
	"Anutrix",
	"Aren Villanueva (kurikaesu)",
	"Ariel Manzur (punto-)",
	"Arman Elgudzhyan (puchik)",
	"Arseny Kapoulkine (zeux)",
	"AThousandShips",
	"aXu-AP",
	"Bart\305\202omiej T. Listwon (Listwon)",
	"Bastiaan Olij (BastiaanOlij)",
	"Ben Brookshire (sheepandshepherd)",
	"Benjamin Larsson (Nallebeorn)",
	"Bernhard Liebl (poke1024)",
	"Bhuvan Vemula (Bhu1-V)",
	"bitsawer",
	"B\305\202a\305\274ej Szczygie\305\202 (zaps166)",
	"BlueCube3310",
	"Bojidar Marinov (bojidar-bg)",
	"Brian Semrau (briansemrau)",
	"Bruno Louren\303\247o (MadEqua)",
	"Cameron Reikes (creikey)",
	"Camille Mohr-Daurat (pouleyKetchoupp)",
	"Caner Demirer (cdemirer)",
	"Carl Olsson (not-surt)",
	"Carter Anderson (cart)",
	"ChibiDenDen",
	"Chris Bradfield (cbscribe)",
	"Chris Cranford (Naros)",
	"Christian Kaiser (ckaiser)",
	"Clay John (clayjohn)",
	"ConteZero",
	"CookieBadger",
	"Dana Olson (adolson)",
	"Daniel J. Ramirez (djrm)",
	"Daniel Rakos (aqnuep)",
	"Daniel Zilberleyb (dzil123)",
	"Danil Alexeev (dalexeev)",
	"dankan1890",
	"Dar\303\255o Banini (DarioSamo)",
	"David Cambr\303\251 (Gallilus)",
	"David Sichma (DavidSichma)",
	"David Snopek (dsnopek)",
	"derammo",
	"Dharkael (lupoDharkael)",
	"Dirk Steinmetz (rsjtdrjgfuzkfg)",
	"Dmitry Koteroff (Krakean)",
	"Dmitry Maganov (vonagam)",
	"Dominik Jasi\305\204ski (dreamsComeTrue)",
	"Douglas Le\303\243o (DeeJayLSP)",
	"DualMatrix",
	"Ellen Poe (ellenhp)",
	"Emilio Coppola (coppolaemilio)",
	"Emmanuel Barroga (codecustard)",
	"Emmanuel Leblond (touilleMan)",
	"Eoin O'Neill (Eoin-ONeill-Yokai)",
	"Eric Lasota (elasota)",
	"Eric M (EricEzaM)",
	"Eric Rybicki (ericrybick)",
	"Erik Seleck\303\275 (rxlecky)",
	"est31",
	"Eveline Jarosz (Marqin)",
	"Fabian Mathews (supagu)",
	"Fabio Alessandrelli (Faless)",
	"Fabrice Cipolla (fabriceci)",
	"Ferenc Arn (tagcup)",
	"FireForge (fire-forge)",
	"Florian Kothmeier (Dragoncraft89)",
	"follower",
	"foxydevloper",
	"Fran\303\247ois Belair (Razoric480)",
	"Franklin Sobrinho (TheHX)",
	"Fredia Huya-Kouadio (m4gr3d)",
	"Geequlim",
	"George Marques (vnen)",
	"Gerrit Gro\303\237kopf (Grosskopf)",
	"Giganzo",
	"Gilles Roudiere (groud)",
	"Gordon MacPherson (RevoluPowered)",
	"Guilherme Felipe de C. G. da Silva (guilhermefelipecgs)",
	"Hakim Rouatbi (hakro)",
	"Hanif Bin Ariffin (hbina)",
	"Haoyu Qiu (timothyqiu)",
	"Hein-Pieter van Braam-Stewart (hpvb)",
	"Hendrik Brucker (Geometror)",
	"Hilderin",
	"Hiroshi Ogawa (hi-ogawa)",
	"HolonProduction",
	"homer666",
	"hoontee",
	"Hugo Locurcio (Calinou)",
	"Ian Bishop (ianb96)",
	"Ibrahn Sahir (ibrahn)",
	"Ignacio Rold\303\241n Etcheverry (neikeq)",
	"Igor Kordiukiewicz (IgorKordiukiewicz)",
	"Ilaria Cislaghi (QbieShay)",
	"Indah Sylvia (ISylvox)",
	"Ivan \305\240achov (van800)",
	"J08nY",
	"Jake Young (Duroxxigar)",
	"Jakub Grzesik (kubecz3k)",
	"Jakub Marcowski (Chubercik)",
	"James Buck (jbuck3)",
	"Jan Haller (Bromeon)",
	"Jason Knight (jasonwinterpixel)",
	"Jean-Michel Bernard (jmb462)",
	"J\303\251r\303\264me Gully (Nutriz)",
	"Jia Jun Chai (SkyLucilfer)",
	"jitspoe",
	"Joan Fons Sanchez (JFonS)",
	"Johan Aires Rast\303\251n (JohanAR)",
	"Johan Manuel (29jm)",
	"Johannes Witt (HaSa1002)",
	"Jonathan Nicholl (jtnicholl)",
	"Jordan Schidlowsky (winterpixelgames)",
	"Josh Jones (DarkKilauea)",
	"Joshua Grams (JoshuaGrams)",
	"Juan Linietsky (reduz)",
	"Julian Murgia (StraToN)",
	"Julien Nguyen (Blackiris)",
	"Jummit",
	"Justo Delgado (mrcdk)",
	"karroffel",
	"Kassandra Pucher (PucklaJ)",
	"Kelly Thomas (KellyThomas)",
	"kleonc",
	"Kongfa Waroros (gongpha)",
	"Kostadin Damyanov (Max-Might)",
	"K. S. Ernest (iFire) Lee (fire)",
	"Kyle Eichlin (likeich)",
	"lawnjelly",
	"Leon Krause (leonkrause)",
	"Liz Haas (27thLiz)",
	"Lucien Menassol (Kanabenki)",
	"Lyuma",
	"Maganty Rushyendra (mrushyendra)",
	"Magian (magian1127)",
	"Mai Lavelle (maiself)",
	"Malcolm Nixon (Malcolmnixon)",
	"Manuele Finocchiaro (m4nu3lf)",
	"Marcel Admiraal (madmiraal)",
	"Marcelo Fernandez (marcelofg55)",
	"Marc Gilleron (Zylann)",
	"Marcin Zawiejski (dragmz)",
	"Marcus Brummer (mbrlabs)",
	"Marcus Elg (MCrafterzz)",
	"Mariano Javier Suligoy (MarianoGnu)",
	"Mario Liebisch (MarioLiebisch)",
	"Mario Schlack (hurikhan)",
	"Marios Staikopoulos (marstaik)",
	"Marius Hanl (Maran23)",
	"Mark DiBarry (markdibarry)",
	"Mark Riedesel (klowner)",
	"Markus Sauermann (Sauermann)",
	"Martin Capitanio (capnm)",
	"Martin Li\305\241ka (marxin)",
	"Martin Sjursen (binbitten)",
	"marynate",
	"Masoud BH (masoudbh3)",
	"Mateo Kuruk Miccino (kuruk-mm)",
	"Matias N. Goldberg (darksylinc)",
	"Matthew Murphy (mashumafi)",
	"Matthew (skyace65)",
	"Matthias H\303\266lzl (hoelzl)",
	"Max Hilbrunner (mhilbrunner)",
	"merumelu",
	"Meru Patel (Janglee123)",
	"MewPurPur",
	"Michael Alexsander (YeldhamDev)",
	"Micha\305\202 Iwa\305\204czuk (iwek7)",
	"MichiRecRoom (LikeLakers2)",
	"Micky (Mickeon)",
	"Mikael Hermansson (mihe)",
	"Mika Viskari (miv391)",
	"MinusKube",
	"MJacred",
	"Mounir Tohami (WhalesState)",
	"mrezai",
	"Muhammad Huri (CakHuri)",
	"muiroc",
	"myaaaaaaaaa",
	"Nathalie Galla (MurderVeggie)",
	"Nathan Franke (nathanfranke)",
	"Nathan Lovato (NathanLovato)",
	"Nathan Warden (NathanWarden)",
	"Nicholas Huelin (SirQuartz)",
	"Nikita Lita (nikitalita)",
	"Nils Andr\303\251-Chang (NilsIrl)",
	"Noah Beard (TwistedTwigleg)",
	"N\303\264ng V\304\203n T\303\254nh (nongvantinh)",
	"Nuno Donato (nunodonato)",
	"ocean (they/them) (anvilfolk)",
	"Omar El Sheikh (The-O-King)",
	"Ovnuniarchos",
	"Pascal Richter (ShyRed)",
	"passivestar",
	"Patrick Dawson (pkdawson)",
	"Patrick Exner (FlameLizard)",
	"Patrick (firefly2442)",
	"patwork",
	"Paul Batty (Paulb23)",
	"Paul Joannon (paulloz)",
	"Paul Trojahn (ptrojahn)",
	"P\304\201vels Nadto\304\215ajevs (bruvzg)",
	"Pawe\305\202 Fertyk (pfertyk)",
	"Pawel Kowal (pkowal1982)",
	"Pawel Lampe (Scony)",
	"Pedro J. Est\303\251banez (RandomShaper)",
	"Pieter-Jan Briers (PJB3005)",
	"Poommetee Ketson (Noshyaar)",
	"Przemys\305\202aw Go\305\202\304\205b (n-pigeon)",
	"Radiant (RadiantUwU)",
	"Rafael M. G. (rafallus)",
	"Rafa\305\202 Mikrut (qarmin)",
	"Raffaele Picca (RPicster)",
	"Ralf H\303\266lzemer (rollenrolm)",
	"Ramesh Ravone (RameshRavone)",
	"Raphael2048",
	"Raul Santos (raulsntos)",
	"Ray Koopa (RayKoopa)",
	"RedMser",
	"RedworkDE",
	"R\303\251mi Verschelde (akien-mga)",
	"Rhody Lugo (rraallvv)",
	"Ricardo Buring (rburing)",
	"Ricardo Subtil (Ev1lbl0w)",
	"Riteo Siuga (Riteo)",
	"Roberto F. Arroyo (robfram)",
	"Robert Yevdokimov (ryevdokimov)",
	"Robin H\303\274bner (profan)",
	"romulox-x",
	"Rune Smith (rune-scape)",
	"Ruslan Mustakov (endragor)",
	"Ryan Roden-Corrent (rrcore)",
	"Saniko (sanikoyes)",
	"santouits",
	"SaracenOne",
	"Septian Ganendra S. K. (sepTN)",
	"Sergey Minakov (naithar)",
	"sersoong",
	"Shiqing (kawa-yoiko)",
	"Silc 'Tokage' Renew (TokageItLab)",
	"Simon Wenner (swenner)",
	"smix8",
	"snailrhymer",
	"Sofox (TheSofox)",
	"Stanislav Labzyuk (DarkMessiah)",
	"Stijn Hinlopen (hinlopen)",
	"stmSi",
	"Stuart Carnie (stuartcarnie)",
	"Swarnim Arun (minraws)",
	"TC (floppyhammer)",
	"TechnoPorg",
	"Thaddeus Crews (Repiteo)",
	"Thakee Nathees (ThakeeNathees)",
	"thebestnom",
	"Theo Hallenius (TheoXD)",
	"Thomas ten Cate (ttencate)",
	"Timo Schwarzer (timoschwarzer)",
	"Timoth\303\251 Bonhoure (ajreckof)",
	"Timo (toger5)",
	"Tomasz Chabora (KoBeWi)",
	"trollodel",
	"Twarit Waikar (IronicallySerious)",
	"Umang Kalra (theoway)",
	"Vinzenz Feenstra (vinzenz)",
	"Vitika Soni (Vitika9)",
	"\353\260\225\355\225\234\354\226\274 (volzhs)",
	"V. Vamsi Krishna (vkbsb)",
	"Wilhem Barbier (nounoursheureux)",
	"William Deurwaarder (williamd67)",
	"Will Nations (willnationsdev)",
	"Wilson E. Alvarez (Rubonnek)",
	"Xavier Cho (mysticfall)",
	"Yaohua Xiong (xiongyaohua)",
	"yg2f (SuperUserNameMan)",
	"Yordan Dolchinkov (Jordyfel)",
	"Yuri Rubinsky (Chaosus)",
	"Yuri Sizov (YuriSizov)",
	"Zae Chao (zaevi)",
	"Zak Stam (zaksnet)",
	"Zher Huei Lee (leezh)",
	"Zi Ye (MajorMcDoom)",
	"ZuBsPaCe",
	"\320\224\320\274\320\270\321\202\321\200\320\270\320\271 \320\241\320\260\320\273\321\214\320\275\320\270\320\272\320\276\320\262 (DmitriySalnikov)",
	"\345\277\230\345\277\247\343\201\256 (Daylily-Zeleen)",
	"\350\260\242\345\244\251 (jsjtxietian)",
	"\351\243\216\351\235\222\345\261\261 (Rindbee)",
	0
};
#endif // AUTHORS_GEN_H
