/* THIS FILE IS GENERATED DO NOT EDIT */
#ifndef DONORS_GEN_H
#define DONORS_GEN_H
const char *const DONORS_PATRONS[] = {
	"Khronos\302\256 Group <https://www.khronos.org/>",
	"OSS Capital <https://oss.capital/>",
	0
};
const char *const DONORS_SPONSORS_PLATINUM[] = {
	"Google Play <https://play.google.com>",
	"Ramatak <https://ramatak.com/>",
	"V-Sekai <https://github.com/V-Sekai>",
	"W4 Games <https://w4games.com/>",
	0
};
const char *const DONORS_SPONSORS_GOLD[] = {
	"Mega Crit <https://www.megacrit.com/>",
	"Pirate Software <https://gopiratesoftware.com>",
	"Prehensile Tales <https://prehensile-tales.com>",
	"Robot Gentleman <http://robotgentleman.com/>",
	0
};
const char *const DONORS_SPONSORS_SILVER[] = {
	"Broken Rules <https://brokenrul.es>",
	"Chasing Carrots <https://www.chasing-carrots.com>",
	"Copia Wealth Studios <https://copiawealthstudios.com/>",
	"Indoor Astronaut <https://indoorastronaut.ch/>",
	"LoadComplete <https://loadcomplete.com/>",
	"Null <https://null.com/>",
	"Orbital Knight <https://www.orbitalknight.com/>",
	"Playful Studios <https://playfulstudios.com/>",
	"Re-Logic <https://re-logic.com/>",
	0
};
const char *const DONORS_MEMBERS_DIAMOND[] = {
	"Bippinbits <http://domekeepergame.com/>",
	"Sylv <https://rankith.itch.io/unnamed-space-idle-prototype>",
	"And 3 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_TITANIUM[] = {
	"Adriaan de Jongh <https://adriaan.games>",
	"Anitya Space <https://www.anitya.space>",
	"Basically Games",
	"FDG Entertainment <https://www.fdg-entertainment.com>",
	"Game Dev Artisan <https://gamedevartisan.com>",
	"Garry Newman",
	"Kenney <https://kenney.nl/>",
	"Libretrend <https://libretrend.com>",
	"Life Art Studios <https://lifeartstudios.net/>",
	"Lucid Silence Games",
	"Matthew Campbell",
	"PolyMars <https://polymars.dev/>",
	"Razenpok <https://www.youtube.com/watch?v=-QxI-RP6-HM>",
	"RPG in a Box <https://www.rpginabox.com>",
	"Smirk Software <https://smirk.gg>",
	"Studio Sunshower <https://www.studiosunshower.com/>",
	"TrampolineTales <https://TrampolineTales.com/>",
	"\347\262\237\344\272\214\345\215\216 (Su Erhua)",
	"And 4 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_PLATINUM[] = {
	"Andy Touch",
	"BlockImperiumGames (BIG)",
	"Christopher Shifflett",
	"Christoph Woinke",
	"Cody Bentley",
	"Darrin Massena",
	"Edward Flick",
	"GetIntoGameDev",
	"HP van Braam",
	"iCommitGames",
	"Jonah Stich",
	"Justo Delgado Baud\303\255",
	"katnamag",
	"Matthew Ekenstedt",
	"Memories in 8Bit",
	"Mike King",
	"Neal Gompa (Conan Kudo)",
	"Radivarig",
	"Ronnie Cheng",
	"Ryan Heath",
	"Scott Pezza",
	"ShikadiGum",
	"Silver Creek Entertainment",
	"SolarLabyrinth",
	"Stephan Kessler",
	"Stephan Lanfermann",
	"TigerJ",
	"Violin Iliev",
	"Vladim\303\255r Chv\303\241til",
	"And 13 anonymous donors",
	0
};
const char *const DONORS_MEMBERS_GOLD[] = {
	"80px",
	"afreytes",
	"alMoo Games",
	"alMoo Games",
	"Alva Majo",
	"Antti Vesanen",
	"Asher Glick",
	"Axthelm",
	"Bellbird Studio",
	"Benito",
	"Benjamin Sarsgard",
	"Ben Rog-Wilhelm",
	"Bernd Barsuhn",
	"BetaTester704",
	"Brian Levinsen",
	"Brut",
	"Bryce Dixon",
	"c64cosmin",
	"Carlo del Mundo",
	"Carl van der Geest",
	"Chocolate Software",
	"Cindy Trieu",
	"ClarkThyLord",
	"Codex404",
	"cora",
	"Daniel Eichler",
	"Daniel Krafft",
	"David Chen Zhen",
	"David Coles",
	"David Hubber",
	"David Snopek",
	"Deakcor",
	"Delton Ding",
	"dfseifert",
	"dgehrig",
	"dhanielk",
	"Distorted Realities",
	"Donkung",
	"Dono",
	"Don't You Know Who I Am? Inc.",
	"Dustuu",
	"Dylan P.",
	"Edelweiss",
	"Ends",
	"Eren Ogrul",
	"Eric Brand",
	"Eric Phy",
	"Faisal Al-Kubaisi (QatariGameDev)",
	"Felix Adam",
	"FeralBytes",
	"Festzeltgaming.de",
	"Frozen Fractal",
	"Gaudipern",
	"GlassBrick",
	"Grau",
	"Guangzhou Lingchan",
	"Hayden Oliver",
	"hiulit",
	"Illyan",
	"Immaculate Lift Studio",
	"Ivan Tabashki",
	"Jacob (HACKhalo2 Studios)",
	"Jam",
	"Jason Cawood",
	"Javier Roman",
	"Jeff Hungerford",
	"Jeronimo Schreyer",
	"Johannes Wuensch",
	"John Gabriel",
	"Jonas Yamazaki",
	"Jonathan",
	"Jos\303\251 Canepa",
	"Joshua Stelly",
	"Kalydi Bal\303\241zs",
	"KAR Games",
	"Kiri \042ExpiredPopsicle\042 Artemis",
	"KOGA Mitsuhiro (@shiena)",
	"korinVR",
	"Kristian Kriehl",
	"Lars Thie\303\237en",
	"Lisandro Lorea (Red Mage Games)",
	"Logan Apple",
	"Luca Junge",
	"LyaaaaaGames",
	"m1n1ster",
	"Manuel Requena",
	"Mara Huldra",
	"Marek Belski",
	"Martin \305\240enke\305\231\303\255k",
	"MHDante",
	"Michael Gooch",
	"Modus Ponens",
	"Moshe Harris",
	"Moth",
	"Mr. Byte",
	"Nassor Paulino da Silva",
	"nezticle",
	"Niklas Wahrman",
	"Nitzan Bueno",
	"Niwl Games",
	"NotNet",
	"Oathbringer",
	"Officine Pixel",
	"ohanaya3",
	"Okatima AB",
	"Oleksii Nosov",
	"Osirisa",
	"Patrick Traynor",
	"Petr Malac",
	"pirey",
	"Rafa Laguna",
	"@reilaos",
	"Request",
	"re:thinc",
	"Richard Iv\303\241nek",
	"Rudi P",
	"Sam Leathers",
	"Samuel Judd",
	"ScoreSpace",
	"Shiny Shinken",
	"Silverclad Studios",
	"Sofox",
	"Space Kraken Studios",
	"spacesloth",
	"Spoony Panda",
	"TANAKA Yu",
	"TaraSophieDev (pls fix #43093)",
	"Thad Guidry",
	"ThatGamer",
	"The Polyglot Programmer",
	"TheRiverNyx",
	"Thomas Lobig",
	"Tim Nedvyga",
	"Tom Langwaldt",
	"Trevor Slocum",
	"tukon",
	"Tyler C",
	"Vagastella",
	"Vincent Foulon",
	"Vojtech Lacina",
	"Watchinofoye",
	"Weasel Games",
	"Wilson Birney",
	"Wolfram",
	"WuotanStudios.com",
	"Zhu Li",
	"zikes",
	"\345\227\257\345\244\247\347\210\267",
	"\346\275\230\345\275\246\345\234\243",
	"Alex Khayrullin",
	"Algebrute",
	"Andriy",
	"Antanas Paskauskas",
	"Ari",
	"Arisaka Mayuki",
	"Arthur S. Muszynski",
	"Cameron Connolly",
	"Charlie Whitfield",
	"Craig Ostrin",
	"Craig Swain",
	"CzechBlueBear",
	"Dennis Belfrage",
	"Emily A. Bellows",
	"Felix Winterhalter",
	"Fransiska",
	"Harry Tumber",
	"James Couzens",
	"Jared White",
	"Jes\303\272s Chicharro",
	"Joel Fivat",
	"Johnathan Kupferer",
	"Josef Stumpfegger",
	"Joshua Lesperance",
	"Kelteseth",
	"kickmaniac",
	"Liam Smyth",
	"LoparPanda",
	"Martin Gulliksson",
	"Michael D\303\274rwald",
	"Michael Policastro",
	"n00sh",
	"Nicol\303\241s Monner Sans",
	"Nikita Rotskov",
	"Oliver Dick",
	"Patrick Wuttke",
	"Pete Goodwin",
	"Philip Woods",
	"Reilt",
	"Rickard Hermanson",
	"Rob",
	"Rob McInroy",
	"RodZilla",
	"Ruzgud",
	"Ryan Breaker",
	"\042Sage Automatic Systems, LLC\042",
	"spacechase0",
	"sus",
	"Thomas Kurz",
	"Tobias Bocanegra",
	"Torbulous",
	"toto bibi",
	"Valryia",
	"VoidPointer",
	"Yifan Lai",
	"Adam Carr",
	"Adam Smeltzer",
	"Adisibio",
	"Aidan Marwick",
	"Aidan O'Flannagain",
	"AJWolbers",
	"Alan Beauchamp",
	"Alexander Erlemann",
	"Alex Clavelle",
	"alex raeside",
	"Andre Altmueller",
	"Andreas \303\230stergaard Nielsen",
	"Andrew",
	"Ano Nim",
	"Arch Toasty",
	"Arda Erol",
	"Arturo Rosales",
	"Ash K",
	"Aubrey Falconer",
	"Austin Miller",
	"AzulCrescent",
	"Beau Seymour",
	"Benedikt",
	"Bread",
	"Brian Ford",
	"Caleb Makela",
	"Cameron Meyer",
	"Carl van der Geest",
	"Checkpoint Charlie",
	"Chris Cavalluzzi",
	"Chris Jagusch",
	"Chris Lee",
	"Christian Mauduit",
	"Christian Ringshofer",
	"Christoph Czurda",
	"Christophe Gagnier",
	"Cody Parker",
	"Conall O",
	"Corchari",
	"Corey W",
	"Dakota Watkins",
	"Daniele Tolomelli",
	"Daniel Ramos",
	"Daren Scot Wilson",
	"Dave Jansen",
	"Davesnothere",
	"David Baker",
	"David B\303\264le",
	"David May",
	"David Maziarka",
	"Devin Carraway",
	"Devin R",
	"Dimitri Roche",
	"Donovan Hutcheon",
	"Ducky",
	"Duodecimal",
	"Egon Elbre",
	"Elijah Anderson",
	"Eric Persson",
	"Eric Stokes",
	"Eric Williams",
	"Erkki Sepp\303\244l\303\244",
	"Frank",
	"Frying\342\230\206Pan",
	"Game Endeavor",
	"gamerminstrel",
	"Garrett S",
	"Gary Thomas",
	"gebba",
	"Greyson Richey",
	"Guo Hongci",
	"Haplo",
	"Helge Maus",
	"Heribert Hirth",
	"Ian Richard Kunert",
	"Ian Williams",
	"itsybitesyspider",
	"iveks",
	"Jacob Wallace",
	"Jako Danar",
	"James Gary",
	"James Hulsizer",
	"Jamie Massey",
	"JARKKO PARVIAINEN",
	"Jason Evans",
	"Jonas",
	"Jonas Arndt",
	"Jonas Yamazaki",
	"Jonathan Bieber",
	"Jon Sully",
	"Joseph Catrambone",
	"Josh Taylor",
	"Juanfran",
	"Julian le Roux",
	"Justin Spedding",
	"Keith Bradner",
	"kindzadza",
	"KsyTek Games",
	"Kyle Burnett",
	"Kyle Haltermann",
	"Kyle Jacobs",
	"Leland Vakarian",
	"Levi Berciu",
	"liberodark",
	"Linus Lind Lundgren",
	"Ludovic DELVAL",
	"Luigi Renna",
	"Luis Morao",
	"Lukas Komischke",
	"Luke Diasio",
	"Major Haul",
	"Malcolm",
	"Manuele Finocchiaro",
	"Marcos Heitor Carvalho",
	"Markie Music",
	"Mark Tyler",
	"Markus Michael Egger",
	"Martin Holas",
	"Martin Li\305\241ka",
	"Martin Trbola",
	"Mathieu",
	"Matt Edwards",
	"Maverick",
	"Maxime Blade",
	"Maxwell",
	"Melissa Mears",
	"Metal Demon 2000",
	"Michael Morrison",
	"Mike Copley",
	"Molly Jameson",
	"Moritz Weissenberger",
	"Mrjemandem",
	"naonya3",
	"Nathaniel",
	"neighty",
	"Neil Blakey-Milner",
	"Neofytos Chimonas",
	"Nerdforge",
	"Nerdyninja",
	"Nik Rudenko",
	"Noel Billig",
	"ozrk",
	"Patrick Horn",
	"Patrickm",
	"Patrick Nafarrete",
	"Paul Black",
	"Paul Gieske",
	"Pete",
	"Phoenix Jauregui",
	"Pierre Caye",
	"Pixel Archipel",
	"Point08",
	"PsycHead",
	"Quincy Quincy",
	"Quinn Morrison",
	"Raghava Kovvali",
	"Ragnar Pettersson",
	"Rammeow",
	"Richard Hayes",
	"Riley",
	"RobotCritter",
	"Roland Rz\304\205sa",
	"Russ",
	"Ryan Groom",
	"Sammy Fischer",
	"Satnam Singh",
	"Sebastian Michailidis",
	"SeongWan Kim",
	"Shane Lillie",
	"Shane Spoor",
	"Shaun Kohanowski",
	"Simon Jonas Larsen",
	"Simon Schoenenberger",
	"Sina Yeganeh",
	"Skalli",
	"slavfox",
	"smo1704",
	"SpicyCactuar",
	"Stephen Rice",
	"Stephen Schlie",
	"Sven Walter",
	"SxP",
	"tadashi endo",
	"Tarch",
	"TheVoiceInMyHead",
	"Thibaut DECROMBECQUE",
	"thomas",
	"Thomas Pickett",
	"Tim Drumheller",
	"Tim Klein",
	"Tom Webster",
	"Trent Skinner",
	"Tyler Stepke",
	"Uther",
	"Vaughan Ling",
	"vlnx",
	"Wapiti .",
	"Wiley Thompson",
	"Xatonym",
	"Zekim",
	"\343\202\261\343\203\253\343\203\231\343\203\255\343\202\271",
	"\350\262\264\345\256\217 \345\260\217\346\235\276",
	"And 176 anonymous donors",
	0
};
#endif // DONORS_GEN_H
