/*$T Client/Game/Command/GameCommandSystem.cpp GC 1.140 08/23/09 04:52:40 */


/*$6
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */


/*
 * 功能： 事件处理 修改记录： 080305 GCD_GUILD_INVITE_OBJECT 080306
 * GUILD_INTIVE_CONFIRM GUILD_NOTIFY_INTIVE GCD_GUILD_MODIFY_TITLE 080308
 * GUILD_CREATE_FAMILY GUILD_CREATE_FAMILY_CONFIRM //创建家族确认
 * GUILD_DESTORY_FAMILY_CONFIRM //删除家族确认 080409 GCD_EQUIP_ALL_OPEN // 080519
 * GUILD_KICK_CONFIRM // 帮会踢人确认
 */
#include "StdAfx.h"
#include "GameCommandSystem.h"
#include "GameTimeCommand.h"
#include "GameTime.h"


/* 游戏通用操作 */
sCommandData	g_GameCommand[] =
{
	{ GCD_APPLICATION_INITED, "APPLICATION_INITED", },
	{ GCD_ON_SCENE_TRANS, "ON_SCENE_TRANS", },
	{ GCD_ON_SERVER_TRANS, "ON_SERVER_TRANS", },

	/* { GCD_ON_SCENE_UPDATED, "ON_SCENE_UPDATED", }, */
	{ GCD_SCENE_NAME_TIP, "SCENE_NAME_TIP", },
	{ GCD_SCENE_TRANSED, "SCENE_TRANSED", },
	{ GCD_SCENE_TELEPORT, "SCENE_TELEPORT", },
	{ GCD_PLAYER_ENTER_WORLD, "PLAYER_ENTERING_WORLD", },
	{ GCD_PLAYER_LEAVE_WORLD, "PLAYER_LEAVE_WORLD", },
	{ GCD_TEAM_CHANG_WORLD, "TEAM_CHANGE_WORLD", },

	/* 队友改变场景了 */
	{ GCD_SKILL_CHANGED, "SKILL_CHANGED", },
	{ GCD_MAINTARGET_CHANGED, "MAINTARGET_CHANGED", },
	{ GCD_MAINTARGET_OPEND, "MAINTARGET_OPEN", },
	{ GCD_UPDATE_TARGET2, "UPDATE_TARGET2", },
	{ GCD_MAINTARGET_BUFF_REFRESH, "MAINTARGET_BUFF_REFRESH", },

	/* 刷新主目标buff */
	{ GCD_PACKAGE_ITEM_CHANGED, "PACKAGE_ITEM_CHANGED", },
	{ GCD_TOGLE_SKILL_BOOK, "TOGLE_SKILL_BOOK", },
	{ GCD_CLOSE_SKILL_BOOK, "CLOSE_SKILL_BOOK", },
	{ GCD_SKILL_UPDATE, "SKILL_UPDATE", },
	{ GCD_TOGLE_PET_PAGE, "TOGLE_PET_PAGE", },
	{ GCD_TOGLE_LIFE_PAGE, "TOGLE_LIFE_PAGE", },
	{ GCD_TOGLE_COMMONSKILL_PAGE, "TOGLE_COMMONSKILL_PAGE" },
	{ GCD_TOGLE_CONTAINER, "TOGLE_CONTAINER", },
	{ GCD_TIME_ENENT, "TIME_ENENT", },

	/* 密保 */
	{ GCD_PASSWORD_CARD_OPEN, "PASSWORD_CARD_OPEN" },

	/* 密保卡 */
	{ GCD_PASSWORD_CARD_CLOSE, "PASSWORD_CARD_CLOSE" },
	{ GCD_ABILITY_COOLDOWN_TIME_ENENT, "ABILITY_COOLDOWN_TIME_ENENT", },
	{ GCD_ABILITY_COOLDOWN_ADD_TIMER, "ABILITY_COOLDOWN_ADD_TIMER", },
	
	{ GCD_PASSPOD, "EVENT_PASSPOD" },
};

/* 人物属性 */
sCommandData	g_CharCommand[] =
{
	/* 角色基本属性 */
	{ GCD_UNIT_HP, "UNIT_HP", FALSE },
	{ GCD_UNIT_MP, "UNIT_MP", FALSE },
	{ GCD_UNIT_RAGE, "UNIT_RAGE", TRUE },
	{ GCD_UNIT_MAX_RAGE, "UNIT_MAX_RAGE", TRUE },
	{ GCD_UNIT_RAGE_RESPEED, "UNIT_RAGE_RESPEED", TRUE },

	/* { GCD_UNIT_TALENT, "UNIT_TALENT", TRUE}, */
	{ GCD_UNIT_EXP, "UNIT_EXP", FALSE },
	{ GCD_UNIT_MONEY, "UNIT_MONEY", TRUE },
	{ GCD_UNIT_RACE_ID, "UNIT_RACE_ID", TRUE },
	{ GCD_UNIT_NAME, "UNIT_NAME", TRUE },
	{ GCD_UNIT_CAMP_ID, "UNIT_CAMP_ID", TRUE },
	{ GCD_UNIT_LEVEL, "UNIT_LEVEL", FALSE },
	{ GCD_UNIT_MOVE_SPEED, "UNIT_MOVE_SPEED", TRUE },
	{ GCD_UNIT_FIGHT_STATE, "UNIT_FIGHT_STATE", TRUE },
	{ GCD_UNIT_MAX_EXP, "UNIT_MAX_EXP", FALSE },

	/*
	 * " ;
	 * 一级战斗属性 "
	 */
	{ GCD_UNIT_STR, "UNIT_STR", TRUE },

	/* { GCD_UNIT_SPR, "UNIT_SPR", TRUE}, */
	{ GCD_UNIT_CON, "UNIT_CON", TRUE },
	{ GCD_UNIT_INT, "UNIT_INT", TRUE },
	{ GCD_UNIT_DEX, "UNIT_DEX", TRUE },
	{ GCD_UNIT_POINT_REMAIN, "UNIT_POINT_REMAIN", TRUE },

	/*
	 * " ;
	 * 二级战斗属性 "
	 */
	{ GCD_UNIT_ATT_NEAR, "UNIT_ATT_NEAR", TRUE },
	{ GCD_UNIT_DEF_NEAR, "UNIT_DEF_NEAR", TRUE },
	{ GCD_UNIT_ATT_FAR, "UNIT_ATT_FAR", TRUE },
	{ GCD_UNIT_DEF_FAR, "UNIT_DEF_FAR", TRUE },

	/* { GCD_UNIT_ATT_PHYSICS, "UNIT_ATT_PHYSICS", TRUE}, */
	{ GCD_UNIT_ATT_MAGIC, "UNIT_ATT_MAGIC", TRUE },

	/* { GCD_UNIT_DEF_PHYSICS, "UNIT_DEF_PHYSICS", TRUE}, */
	{ GCD_UNIT_DEF_MAGIC, "UNIT_DEF_MAGIC", TRUE },
	{ GCD_UNIT_MAX_HP, "UNIT_MAX_HP", TRUE },
	{ GCD_UNIT_MAX_MP, "UNIT_MAX_MP", TRUE },
	{ GCD_UNIT_HP_RE_SPEED, "UNIT_HP_RE_SPEED", TRUE },
	{ GCD_UNIT_MP_RE_SPEED, "UNIT_MP_RE_SPEED", TRUE },
	{ GCD_UNIT_HIT, "UNIT_HIT", TRUE },
	{ GCD_UNIT_MISS, "UNIT_MISS", TRUE },
	{ GCD_UNIT_CRIT_RATE, "UNIT_CRIT_RATE", TRUE },
	{ GCD_UNIT_CRIT_HURT, "UNIT_CRIT_HURT", TRUE },
	{ GCD_UNIT_TOUGHNESS, "UNIT_TOUGHNESS", TRUE },
	{ GCD_UNIT_ATT_SPEED, "UNIT_ATT_SPEED", TRUE },
	{ GCD_UNIT_ATT_COLD, "UNIT_ATT_COLD", TRUE },
	{ GCD_UNIT_DEF_COLD, "UNIT_DEF_COLD", TRUE },
	{ GCD_UNIT_ATT_FIRE, "UNIT_ATT_FIRE", TRUE },
	{ GCD_UNIT_DEF_FIRE, "UNIT_DEF_FIRE", TRUE },
	{ GCD_UNIT_ATT_LIGHT, "UNIT_ATT_LIGHT", TRUE },
	{ GCD_UNIT_DEF_LIGHT, "UNIT_DEF_LIGHT", TRUE },
	{ GCD_UNIT_ATT_POSION, "UNIT_ATT_POSION", TRUE },
	{ GCD_UNIT_DEF_POSION, "UNIT_DEF_POSION", TRUE },
	{ GCD_UNIT_MENPAI, "UNIT_MENPAI", TRUE },
	{ GCD_UNIT_HAIR_MESH, "UNIT_HAIR_MESH", TRUE },
	{ GCD_UNIT_HAIR_COLOR, "UNIT_HAIR_COLOR", TRUE },
	{ GCD_UNIT_FACE_IMAGE, "UNIT_FACE_IMAGE", TRUE },

	/* 头像信息改变 */
	{ GCD_UNIT_EQUIP_VER, "UNIT_EQUIP_VER", TRUE },
	{ GCD_UNIT_EQUIP, "UNIT_EQUIP", TRUE },
	{ GCD_UNIT_EQUIP_WEAPON, "UNIT_EQUIP_WEAPON", TRUE },
	{ GCD_UNIT_TITLE, "UNIT_TITLE", TRUE },
	{ GCD_UNIT_STRIKEPOINT, "UNIT_STRIKEPOINT", TRUE },
	{ GCD_UNIT_RELATIVE, "UNIT_RELATIVE", TRUE },
	{ GCD_UNIT_VIGOR, "UNIT_VIGOR", TRUE },
	{ GCD_UNIT_MAX_VIGOR, "UNIT_MAX_VIGOR", TRUE },
	{ GCD_UNIT_REGENE_VIGOR, "UNIT_REGENE_VIGOR", TRUE },
	{ GCD_UNIT_HOT, "UNIT_HOT", TRUE },

	/* 魅力 */
	{ GCD_UNIT_INHERENCE, "UNIT_INHERENCE", TRUE },

	/* 天赋 */
	{ GCD_UNIT_PVP2V2_LEVEL, "UNIT_PVP2V2_LEVEL", TRUE },

	/* 竞技场排名 */
	{ GCD_UNIT_PVP2V2_MARK, "UNIT_PVP2V2_MARK", TRUE },

	/* 节日积分 */
    { GCD_UNIT_FEAST_SCORE, "UNIT_FEAST_SCORE", TRUE },

	/* 竞技场积分 */
	{ GCD_UNIT_ENERGY, "UNIT_ENERGY", TRUE },
	{ GCD_UNIT_MAX_ENERGY, "UNIT_MAX_ENERGY", TRUE },
	{ GCD_UNIT_NEARATT_REDUCE, "UNIT_NEARATT_REDUCE", TRUE },
	{ GCD_UNIT_FARATT_REDUCE, "UNIT_FARATT_REDUCE", TRUE },
	{ GCD_UNIT_MAGICATT_REDUCE, "UNIT_MAGICATT_REDUCE", TRUE },
	{ GCD_UNIT_DREAD_RESIST, "UNIT_DREAD_RESIST", TRUE },
	{ GCD_UNIT_COMA_RESIST, "UNIT_COMA_RESIST", TRUE },
	{ GCD_UNIT_HUSH_RESIST, "UNIT_HUSH_RESIST", TRUE },
	{ GCD_UNIT_UNARM_RESIST, "UNIT_UNARM_RESIST", TRUE },
	{ GCD_UNIT_ATTACKSPEED_RESIST, "UNIT_ATTACKSPEED_RESIST", TRUE },
	{ GCD_UNIT_SKILLSPEED_RESIST, "UNIT_SKILLSPEED_RESIST", TRUE },
	{ GCD_UNIT_MOVEREDUCE_RESIST, "UNIT_MOVEREDUCE_RESIST", TRUE },
	{ GCD_UNIT_Honor_FIRE, "UNIT_Honor_FIRE", TRUE },
	{ GCD_UNIT_CTShengWang_FIRE, "UNIT_CTShengWang_FIRE", TRUE },
	{ GCD_UNIT_JHShengWang_FIRE, "UNIT_JHShengWang_FIRE", TRUE },

	/* 战场荣誉 */
	{ GCD_UNIT_BATTLEHONOUR, "UNIT_BATTLEHONOUR", TRUE },
};

sCommandData	g_GlobalCommand1[] =
{
	/* 骑宠相关 */
	{ GCD_TOGLE_MOUNT_PAGE, "TOGLE_MOUNT_PAGE" },
	{ GCD_CLOSE_MOUNT_PAGE, "CLOSE_MOUNT_PAGE" },
	{ GCD_MOUNT_ATTR_UPDATE, "MOUNT_ATTR_UPDATE" },
	{ GCD_MOUNT_MATING_SUCCESS, "MOUNT_MATING_SUCCESS" },
	{ GCD_MOUNT_COMPOSE_SUCCESS, "MOUNT_COMPOSE_SUCCESS" },
	{ GCD_MOUNT_ATTR_LINK, "MOUNT_ATTR_LINK" },
	{ GCD_OPEN_MOUNT_PAGE, "OPEN_MOUNT_PAGE" },
	{ GCD_MOUNT_HAPPINESS_UPDATE, "MOUNT_HAPPINESS_UPDATE" },

	{ GCD_MOUNT_TIMER_UPDATE, "MOUNT_COMPOSE_TIMER_UPDATE", },
	{ GCD_MOUNT_TIMER_STOP, "MOUNT_COMPOSE_TIMER_STOP", },

	{ GCD_MOUNT_SKILL_SLOT_NOT_ENOUGH, "MOUNT_SKILL_SLOT_NOT_ENOUGH" },
	/* 骑乘快乐度更新 */
	{ GCD_TOGLE_TARGET_MOUNT_PAGE, "TOGLE_TARGET_MOUNT_PAGE" },
	{ GCD_TARGET_MOUNT_ATTR_UPDATE, "TARGET_MOUNT_ATTR_UPDATE" },
	{ GCD_TOGLE_MOUNT_STUDY_PAGE, "TOGLE_MOUNT_STUDY_PAGE" },
	{ GCD_MOUNT_STUDY_ITEM_UPDATE, "MOUNT_STUDY_ITEM_UPDATE" },
	{ GCD_TOGLE_MOUNT_FEED_PAGE, "TOGLE_MOUNT_FEED_PAGE" },
	{ GCD_MOUNT_FEED_ITEM_UPDATE, "MOUNT_FEED_ITEM_UPDATE" },
	{ GCD_TOGLE_MOUNT_TRAIN_PAGE, "TOGLE_MOUNT_TRAIN_PAGE" },
	{ GCD_MOUNT_TRAIN_ITEM_UPDATE, "MOUNT_TRAIN_ITEM_UPDATE" },
	{ GCD_TOGLE_MOUNT_CHILD_PAGE, "TOGLE_MOUNT_CHILD_PAGE" },
	{ GCD_MOUNT_CHILD_ITEM_UPDATE, "MOUNT_CHILD_ITEM_UPDATE" },
	{ GCD_TOGLE_MOUNT_IDENTIFY_PAGE, "TOGLE_MOUNT_IDENTIFY_PAGE" },
	{ GCD_TOGLE_MOUNT_MATING_PAGE, "TOGLE_MOUNT_MATING_PAGE" },
	{ GCD_CLOSE_MOUNT_MATING_PAGE, "CLOSE_MOUNT_MATING_PAGE" },
	{ GCD_MY_MOUNT_MATING_LOCKED, "MY_MOUNT_MATING_LOCKED" },
	{ GCD_OTHER_MOUNT_MATING_LOCKED, "OTHER_MOUNT_MATING_LOCKED" },
	{ GCD_REQUEST_TOGLE_MOUNT_MATING_PAGE, "REQUEST_TOGLE_MOUNT_MATING_PAGE" },
	{ GCD_GAIN_MATING_MOUNT, "GAIN_MATING_MOUNT" },
	{ GCD_TOGLE_MOUNT_COMPOSE_PAGE, "TOGLE_MOUNT_COMPOSE_PAGE" },				
	{ GCD_TOGLE_MOUNT_COMPOSE_PAGE2, "TOGLE_MOUNT_COMPOSE_PAGE2" },	
	{ GCD_TOGLE_MOUNT_COMPOSE_START, "TOGLE_MOUNT_COMPOSE_START" },			
	{ GCD_CLOSE_MOUNT_COMPOSE_PAGE, "CLOSE_MOUNT_COMPOSE_PAGE" },	
	{ GCD_MOUNT_COMPOSE_LOCKPASS_ITEM_UPDATE, "MOUNT_COMPOSE_LOCKPASS_ITEM_UPDATE" },
	{ GCD_MOUNT_COMPOSE_REPENT_ITEM_UPDATE, "MOUNT_COMPOSE_REPENT_ITEM_UPDATE" },
	{ GCD_HORSE_SKILL_REPLACE_CONFIRM, "HORSE_SKILL_REPLACE_CONFIRM" },
	{ GCD_HORSE_SKILL_REPLACE_MULTI_CONFIRM, "HORSE_SKILL_REPLACE_MULTI_CONFIRM" },
	{ GCD_HORSE_SKILL_UP_CONFIRM, "HORSE_SKILL_UP_CONFIRM" },
	{ GCD_HORSE_TOCHILD_CONFIRM, "HORSE_TOCHILD_CONFIRM" },
	{ GCD_HORSE_PASSIVITY_SKILL_REPLACE_CONFIRM, "HORSE_PASSIVITY_SKILL_REPLACE_CONFIRM" },
	{ GCD_SHOW_CONTEXMENU, "SHOW_CONTEXMENU", },
	{ GCD_TOGLE_COMPOSE_WINDOW, "TOGLE_COMPOSE_WINDOW", },
	{ GCD_TOGLE_CONSOLE, "TOGLE_CONSOLE", },
	{ GCD_ON_SKILL_ACTIVE, "ON_SKILL_ACTIVE", },
	{ GCD_POSITION_MODIFY, "POSITION_MODIFY", },
	{ GCD_CHAT_MESSAGE, "CHAT_MESSAGE", },
	{ GCD_CHAT_MESSAGE2, "CHAT_MESSAGE2", },
	{ GCD_CHAT_CHANGE_PRIVATENAME, "CHAT_CHANGE_PRIVATENAME", },
	{ GCD_CHAT_ITEMLINK, "CHAT_ITEMLINK", },
	{ GCD_CHAT_QUESTLINK, "CHAT_MISSIONLINK", },
	{ GCD_CHAT_HORSELINK, "CHAT_HORSELINK", },
	{ GCD_CHAT_SKILLLINK, "CHAT_SKILLLINK", },
	{ GCD_CHAT_CHANNEL_CHANGED, "CHAT_CHANNEL_CHANGED", },
	{ GCD_CHAT_PopChatEditBox, "Chat_PopChatEditBox", },
	{ GCD_CHAT_COPYTEXT, "CHAT_COPYTEXT", },
	{ GCD_CHAT_PASTETXT, "CHAT_PASTETXT", },
	{ GCD_UI_SHOWHIDE, "UI_SHOWHIDE", },
	{ GCD_CHAT_TAB_CREATE, "CHAT_TAB_CREATE", },
	{ GCD_CHAT_TAB_CONFIG, "CHAT_TAB_CONFIG", },
	{ GCD_CHAT_TAB_CREATE_FINISH, "CHAT_TAB_CREATE_FINISH", },
	{ GCD_CHAT_TAB_CONFIG_FINISH, "CHAT_TAB_CONFIG_FINISH", },
	{ GCD_CHAT_FACEMOTION_SELECT, "CHAT_FACEMOTION_SELECT", },
	{ GCD_CHAT_TEXTCOLOR_SELECT, "CHAT_TEXTCOLOR_SELECT", },
	{ GCD_SHOW_CHATCOLOR_SELECT, "SHOW_CHATCOLOR_SELECT", },
	{ GCD_CHAT_CONTEX_MENU, "CHAT_CONTEX_MENU", },
	{ GCD_CHAT_ACTSET, "CHAT_ACTSET", },
	{ GCD_CHAT_ACTSETNEW, "GCD_CHAT_ACTSETNEW", },
	{ GCD_CHAT_ACT_SELECT, "CHAT_ACT_SELECT", },
	{ GCD_CHAT_ACT_HIDE, "CHAT_ACT_HIDE", },
	{ GCD_CHAT_PINGBI_LIST, "CHAT_PINGBI_LIST", },
	{ GCD_CHAT_PINGBI_UPDATE, "CHAT_PINGBI_UPDATE", },
	{ GCD_CHAT_RAPID_REPLY, "CHAT_RAPID_REPLY", },
	{ GCD_CHAT_RAPID_PERSONAL, "CHAT_RAPID_PERSONAL", },
	{ GCD_ACCELERATE_KEYSEND, "ACCELERATE_KEYSEND", },
	{ GCD_CHAT_ADJUST_MOVE_CTL, "CHAT_ADJUST_MOVE_CTL", },
	{ GCD_CHAT_INPUTLANGUAGE_CHANGE, "CHAT_INPUTLANGUAGE_CHANGE", TRUE },
	{ GCD_CHAT_SHOWUSERINFO, "CHAT_SHOWUSERINFO", },
	{ GCD_CHAT_LOAD_TAB_CONFIG, "CHAT_LOAD_TAB_CONFIG", },
	{ GCD_CHAT_INPUT_STATE, "CHAT_INPUT_STATE", },
	{ GCD_CHAT_CLEAR, "CHAT_CLEAR", },
	{ GCD_CHAT_SHOW_CHATFILTERUI, "CHAT_SHOW_CHATFILTERUI", },
	{ GCD_LOOT_OPENED, "LOOT_OPENED", },
	{ GCD_LOOT_SLOT_CLEARED, "LOOT_SLOT_CLEARED", },
	{ GCD_LOOT_CLOSED, "LOOT_CLOSED", },
	{ GCD_PROGRESSBAR_SHOW, "PROGRESSBAR_SHOW", },
	{ GCD_PROGRESSBAR_HIDE, "PROGRESSBAR_HIDE", },
	{ GCD_PROGRESSBAR_WIDTH, "PROGRESSBAR_WIDTH", },
	{ GCD_CHANGE_BAR, "CHANGE_BAR", },
	{ GCD_UPDATE_BAR, "UPDATE_BAR", },
	{ GCD_TOGLE_QUEST, "TOGLE_MISSION", },
	{ GCD_UPDATE_QUEST, "UPDATE_MISSION", },
	{ GCD_REPLY_QUEST, "REPLY_MISSION", },
	{ GCD_UPDATE_REPLY_QUEST, "UPDATE_REPLY_MISSION", },
	{ GCD_TOGLE_LARGEMAP, "TOGLE_LARGEMAP", },
	{ GCD_TOGLE_SCENEMAP, "TOGLE_SCENE_MAP", },
	{ GCD_OPEN_MINIMAP, "OPEN_MINIMAP", },
	{ GCD_OPEN_MINIMAPEXP, "OPEN_MINIMAPEXP", },
	{ GCD_AUTO_FIND_PATH, "AUTO_FIND_PATH", },
	{ GCD_SHOW_MINIMAP_BUTTON, "SHOW_MINIMAP_BUTTON", },
	{ GCD_QUEST_EVENTLIST, "QUEST_EVENTLIST", },
	{ GCD_QUEST_INFO, "QUEST_INFO", },
	{ GCD_QUEST_REGIE, "QUEST_REGIE", },
	{ GCD_QUEST_CONTINUE_DONE, "QUEST_CONTINUE_DONE", },
	{ GCD_QUEST_CONTINUE_NOTDONE, "QUEST_CONTINUE_NOTDONE", },
	{ GCD_QUEST_AFTER_CONTINUE, "QUEST_AFTER_CONTINUE", },
	{ GCD_QUEST_TIPS, "QUEST_TIPS", },
	{ GCD_TOGLE_COMPOSEITEM, "TOGLE_COMPOSEITEM", },

	/* { GCD_TOGLE_COMPOSEGEM, "TOGLE_COMPOSEGEM", }, */
	{ GCD_ON_LIFEABILITY_ACTIVE, "ON_LIFEABILITY_ACTIVE", },
	{ GCD_NEW_DEBUGMESSAGE, "NEW_DEBUGMESSAGE", },
	{ GCD_OPEN_BOOTH, "OPEN_BOOTH", },
	{ GCD_CLOSE_BOOTH, "CLOSE_BOOTH", },
	{ GCD_QUEST_INPUT_PASSWD_COMMAND, "QUEST_INPUT_PASSWD_COMMAND", },
	{ GCD_QUESTLOG_AUTO_FIND_PATH, "QUESTLOG_AUTO_FIND_PATH", },
	{ GCD_EVENTLIST_HIDE, "EVENTLIST_HIDE", },

	/* 一键换装 */
	{ GCD_QUICK_CHANGE_EQUIP, "QUICK_CHANGE_EQUIP", },
	{ GCD_UPDATE_QUICK_CHANGE, "UPDATE_QUICK_CHANGE", },
	{ GCD_QUICK_CHANGE_SUCCESS, "QUICK_CHANGE_SUCCESS", },
	{ GCD_QUICK_UPDATE_FRAME, "QUICK_UPDATE_FRAME", },

	/* 装备属性界面消息 */
	{ GCD_UPDATE_EQUIP, "REFRESH_EQUIP", },

	/* 更新装备, 无参数. */
	{ GCD_MANUAL_ATTR_SUCCESS_EQUIP, "MANUAL_ATTR_SUCCESS_EQUIP", },

	/* 手动调节属性成功. */
	{ GCD_CUR_TITLE_CHANGEED, "CUR_TITLE_CHANGED", },

	/* 当前标题改变了. */
	{ GCD_TOGLE_TARGET_EQUIP_PAGE, "TOGLE_TARGET_EQUIP_PAGE", },
	{ GCD_CLOSE_TARGET_EQUIP, "CLOSE_TARGET_EQUIP", },
	{ GCD_TOGLE_TARGET_EQUIP_ALL, "TOGLE_TARGET_EQUIP_ALL", },
	{ GCD_TOGLE_TARGET_EQUIP_ALL_FOR_AROUNDPLAYER, "TOGLE_TARGET_EQUIP_ALL_FOR_AROUNDPLAYER" },
	{ GCD_CLOSE_TARGET_EQUIP_ALL, "CLOSE_TARGET_EQUIP_ALL", },
	{ GCD_CHANGE_TARGET_EQUIP_ALL_PAGE, "CHANGE_TARGET_EQUIP_ALL_PAGE", },
	{ GCD_UPDATE_BOOTH, "UPDATE_BOOTH", },
	{ GCD_UPDATE_TEAM_MEMBER, "ON_UPDATE_TEAM_MEMBER", },
	{ GCD_OPEN_CHARACTOR, "OPEN_CHARACTOR", },
	{ GCD_OPEN_EQUIP, "OPEN_EQUIP", },
	{ GCD_TOGLE_JOINSCHOOL, "TOGLE_JOINSCHOOL" },
	{ GCD_UPDATE_CONTAINER, "UPDATE_CONTAINER", },

	/* soongxl */
	{ GCD_EXT_PACKAGE_OPEN, "EXT_PACKAGE_OPEN", },

	/* Nick 2007.11.21 */
	{ GCD_OPEN_MAIN_FUNC_BTN, "OPEN_MAIN_FUNC_BTN" },

	/* 主功能按钮，用于打开8个主功能按钮 */
	{ GCD_OPEN_ADD_HOLE, "OPEN_ADD_HOLE", },
	{ GCD_UPDATE_ADD_HOLE, "UPDATE_ADD_HOLE", },
	{ GCD_ADD_HOLE_SUCCESS, "EQUIP_ADD_HOLE_SUCCESS", },
	{ GCD_OPEN_BANG_DING, "OPEN_BANG_DING", },
	{ GCD_UPDATE_BANG_DING, "UPDATE_BANG_DING", },
	{ GCD_ADD_BANG_DING_SUCCESS, "EQUIP_BANG_DING_SUCCESS", },
	{ GCD_OPEN_DA_XING, "OPEN_DA_XING", },
	{ GCD_OPEN_SUIT_DA_XING, "OPEN_SUIT_DA_XING", },
	{ GCD_OPEN_HONOR_BIND, "OPEN_HONOR_BIND", },
	{ GCD_UPDATE_DA_XING, "UPDATE_DA_XING", },
	{ GCD_OPEN_DA_XING_SUCCESS, "EQUIP_DA_XING_SUCCESS" },
	{ GCD_OPEN_RING_FUSION, "OPEN_RING_FUSION" },
	{ GCD_UPDATE_RING_FUSION, "UPDATE_RING_FUSION" },
	{ GCD_OPEN_STARS_FUSION, "OPEN_STARS_FUSION" },
	{ GCD_OPEN_SP_REPAIR, "OPEN_SP_REPAIR", },
	{ GCD_UPDATE_SP_REPAIR, "UPDATE_SP_REPAIR", },
	{ GCD_OPEN_SP_REPAIR_SUCCESS, "EQUIP_SP_REPAIR_SUCCESS" },
	{ GCD_OPEN_REPAIR_SURE, "EQUIP_REPAIR_SURE_OPEN" },
	{ GCD_OPEN_SYNTHESIZE, "EQUIP_OPEN_SYNTHESIZE" },
	{ GCD_CLOSE_SYNTHESIZE, "EQUIP_CLOSE_SYNTHESIZE" },
	{ GCD_OPEN_EQUIP_REWORK, "EQUIP_OPEN_REWORK" },
	{ GCD_CLOSE_EQUIP_REWORK, "EQUIP_CLOSE_REWORK" },
	{ GCD_OPEN_EQUIP_DISASS, "EQUIP_OPEN_DISASS" },
	{ GCD_UPDATE_EQUIP_DISASS, "EQUIP_UPDATE_DISASS" },
	{ GCD_CLOSE_EQUIP_DISASS, "EQUIP_CLOSE_DISASS" },
	{ GCD_IMPACT_SELF_UPDATE, "IMPACT_SELF_UPDATE", },
	{ GCD_IMPACT_SELF_UPDATE_TIME, "IMPACT_SELF_UPDATE_TIME", },
	{ GCD_IMPACT_SELF_CLEANUP, "IMPACT_SELF_CLEANUP", },
	{ GCD_OPEN_AGNAME, "OPEN_AGNAME", },
	{ GCD_CLOSE_AGNAME, "CLOSE_AGNAME", },
	{ GCD_TOGLE_BANK, "TOGLE_BANK", },
	{ GCD_UPDATE_BANK, "UPDATE_BANK", },
	{ GCD_TOGLE_BANKPET, "TOGLE_BANKPET", },
	{ GCD_UPDATE_BANKPET, "UPDATE_BANKPET", },
	{ GCD_TOGLE_INPUT_MONEY, "TOGLE_INPUT_MONEY", },
	{ GCD_CLOSE_INPUT_MONEY, "CLOSE_INPUT_MONEY", },
	{ GCD_OPEN_BANK_EVENT, "OPEN_BANK_EVENT", },
	{ GCD_RECEIVE_EXCHANGE_APPLY, "RECEIVE_EXCHANGE_APPLY", },
	{ GCD_STOP_EXCHANGE_TIP, "STOP_EXCHANGE_TIP", },
	{ GCD_OPEN_EXCHANGE_FRAME, "OPEN_EXCHANGE_FRAME", },
	{ GCD_UPDATE_EXCHANGE, "UPDATE_EXCHANGE", },
	{ GCD_CANCEL_EXCHANGE, "CANCEL_EXCHANGE", },
	{ GCD_SUCCEED_EXCHANGE_CLOSE, "SUCCEED_EXCHANGE_CLOSE", },
	{ GCD_EXCHANGE_INPUT_MONEY, "EXCHANGE_INPUT_MONEY", },
	{ GCD_PACKET_OPEN_SALE, "PACKET_OPEN_SALE", },
	{ GCD_EQUIP_LEVELUP_CANCEL_BIND, "EQUIP_LEVELUP_CANCEL_BIND", },

	/* 通过密码打开摆摊 */
	{ GCD_UPDATE_PET_PAGE, "UPDATE_PET_PAGE", },
	{ GCD_UPDATE_LIFESKILL_PAGE, "UPDATE_LIFESKILL_PAGE", },
	{ GCD_OPEN_COMPOSE_ITEM, "OPEN_COMPOSE_ITEM", },
	{ GCD_UPDATE_COMPOSE_ITEM, "UPDATE_COMPOSE_ITEM", },
	{ GCD_OPEN_COMPOSE_GEM, "OPEN_COMPOSE_GEM", },
	{ GCD_OPEN_REPLACE_GEM, "OPEN_REPLACE_GEM", },
	{ GCD_UPDATE_COMPOSE_EQUIP, "UPDATE_COMPOSE_EQUIP", },
	{ GCD_UPDATE_COMPOSE_GEM, "UPDATE_COMPOSE_GEM", },
	{ GCD_COMPOSE_GEM_SUCCESS, "COMPOSE_GEM_SUCCESS", },
	{ GCD_ENCHASE_CONFIRM_DLG, "ENCHASE_CONFIRM_DLG", },
	{ GCD_AFFIRM_SHOW, "AFFIRM_SHOW", },

	/* 摆摊相关 */
	{ GCD_OPEN_STALL_SALE, "OPEN_STALL_SALE", },
	{ GCD_OPEN_STALL_BUY, "OPEN_STALL_BUY", },
	{ GCD_OPEN_STALL_BUY_GOLDSURE, "OPEN_STALL_BUY_GOLDSURE", },
	{ GCD_UPDATE_STALL_BUY, "UPDATE_STALL_BUY", },
	{ GCD_UPDATE_STALL_SALE, "UPDATE_STALL_SALE", },
	{ GCD_OPEN_STALL_RENT_FRAME, "OPEN_STALL_RENT_FRAME", },
	{ GCD_STALL_SALE_SELECT, "STALL_SALE_SELECT", },
	{ GCD_STALL_BUY_SELECT, "STALL_BUY_SELECT", },
	{ GCD_OPEN_STALL_MESSAGE, "OPEN_STALL_MESSAGE", },
	{ GCD_CLOSE_STALL_MESSAGE, "CLOSE_STALL_MESSAGE", },

	/* 销毁物品 */
	{ GCD_OPEN_DISCARD_ITEM_FRAME, "OPEN_DISCARD_ITEM_FRAME", },

	/* 不能销毁物品 */
	{ GCD_OPEN_CANNT_DISCARD_ITEM, "OPEN_CANNT_DISCARD_ITEM", },
	{ GCD_SHOW_SPLIT_ITEM, "SHOW_SPLIT_ITEM", },
	{ GCD_HIDE_SPLIT_ITEM, "HIDE_SPLIT_ITEM", },
	{ GCD_TOGLE_FRIEND_INFO, "TOGLE_FRIEND_INFO", },
	{ GCD_TOGLE_FRIEND, "TOGLE_FRIEND", },
	{ GCD_MENU_UPDATE_FRIENDCUSTOMGROUP, "MENU_UPDATE_FRIENDCUSTOMGROUP", },
	{ GCD_OPEN_EMAIL, "OPEN_EMAIL", },
	{ GCD_OPEN_EMAIL_WRITE, "OPEN_EMAIL_WRITE", },
	{ GCD_CLOSE_EMAIL_WRITE, "CLOSE_EMAIL_WRITE", },
	{ GCD_HAVE_MAIL, "HAVE_MAIL", },
	{ GCD_SEND_MAIL, "SEND_MAIL", },
	{ GCD_UPDATE_EMAIL, "UPDATE_EMAIL", },
	{ GCD_FRIEND_SET, "FRIEND_SET", },
	{ GCD_MOOD_CHANGE, "MOOD_CHANGE", },
	{ GCD_OPEN_HISTROY, "OPEN_HISTROY", },
	{ GCD_OPEN_XIAOLABA, "OPEN_XIAOLABA", },

	/* 系统设置相关 */
	{ GCD_TOGLE_SYSTEMFRAME, "TOGLE_SYSTEMFRAME", },
	{ GCD_TOGLE_VIEWSETUP, "TOGLE_VIEWSETUP", },
	{ GCD_TOGLE_SOUNDSETUP, "TOGLE_SOUNDSETUP", },
	{ GCD_TOGLE_UISETUP, "TOGLE_UISETUP", },
	{ GCD_TOGLE_INPUTSETUP, "TOGLE_INPUTSETUP", },
	{ GCD_TOGLE_GAMESETUP, "TOGLE_GAMESETUP", },
	{ GCD_UPDATE_VIEWSETUP, "UPDATE_VIEWSETUP", },

	/* 设置自定义键盘 */
	{ GCD_KEYBOARD_SET_KEY, "KEYBOARD_SET_KEY", },
	{ GCD_KEYBOARD_SWAP_KEY, "KEYBOARD_SWAP_KEY", },
	{ GCD_KEYBOARD_SET_REPEAT, "KEYBOARD_SET_REPEAT", },
	{ GCD_KEYBOARD_CANCEL, "KEYBOARD_CANCEL", },
	{ GCD_KEYBOARD_OVERWRITE, "KEYBOARD_OVERWRITE" },

	/* 玩家商店 */
	{ GCD_PS_OPEN_OTHER_SHOP, "PS_OPEN_OTHER_SHOP", },
	{ GCD_PS_OPEN_MY_SHOP, "PS_OPEN_MY_SHOP", },
	{ GCD_PS_OPEN_CREATESHOP, "PS_OPEN_CREATESHOP", },
	{ GCD_PS_CLOSE_CREATESHOP, "PS_CLOSE_CREATESHOP", },
	{ GCD_PS_OPEN_SHOPLIST, "PS_OPEN_SHOPLIST", },
	{ GCD_PS_SELF_ITEM_CHANGED, "PS_SELF_ITEM_CHANGED", },
	{ GCD_PS_OTHER_SELECT, "PS_OTHER_SELECT", },
	{ GCD_PS_SELF_SELECT, "PS_SELF_SELECT", },
	{ GCD_PS_UPDATE_MY_SHOP, "PS_UPDATE_MY_SHOP", },
	{ GCD_PS_UPDATE_OTHER_SHOP, "PS_UPDATE_OTHER_SHOP", },
	{ GCD_PS_OPEN_OTHER_TRANS, "PS_OPEN_OTHER_TRANS", },
	{ GCD_PS_UPDATE_OTHER_TRANS, "PS_UPDATE_OTHER_TRANS", },
	{ GCD_PS_OTHER_TRANS_SELECT, "PS_OTHER_TRANS_SELECT", },
	{ GCD_OPEN_PS_MESSAGE_FRAME, "OPEN_PS_MESSAGE_FRAME", },
	{ GCD_PS_OPEN_MESSAGE, "PS_OPEN_MESSAGE", },
	{ GCD_PS_UPDATE_MESSAGE, "PS_UPDATE_MESSAGE", },
	{ GCD_OPEN_PET_LIST, "OPEN_PET_LIST", },
    { GCD_OPEN_ITEM_LIST, "OPEN_ITEM_LIST", },
    { GCD_CLOSE_ITEM_LIST, "CLOSE_ITEM_LIST", },
	{ GCD_VIEW_EXCHANGE_PET, "VIEW_EXCHANGE_PET", },
	{ GCD_CLOSE_PET_LIST, "CLOSE_PET_LIST", },
	{ GCD_UPDATE_PET_LIST, "UPDATE_PET_LIST", },
	{ GCD_HORSE_IS_DELETED, "HORSE_IS_DELETED", },
	{ GCD_OPEN_PRIVATE_INFO, "OPEN_PRIVATE_INFO", },
	{ GCD_OPEN_OTHER_INFO, "OPEN_OTHER_INFO", },
	{ GCD_UPDATE_PRIVATE_INFO, "UPDATE_PRIVATE_INFO", },
	{ GCD_PRIVATE_INFO_MODIFY, "GPRIVATE_INFO_MODIFY", },
	{ GCD_OPEN_CALLOF_PLAYER, "OPEN_CALLOF_PLAYER", },
	{ GCD_NET_CLOSE, "NET_CLOSE", },
	{ GCD_OPEN_ITEM_COFFER, "OPEN_ITEM_COFFER", },
	{ GCD_PS_INPUT_MONEY, "PS_INPUT_MONEY", },

	/* * 组队相关事件 */
	{ GCD_TEAM_OPEN_TEAMINFO_DLG, "TEAM_OPEN_TEAMINFO_DLG", },

	/*
	 * 打开队伍信息对话框. ;
	 * ;
	 * arg0 - 正整数, 从0开始 ;
	 * 0 : 打开队伍信息 ;
	 * 1 : 有人申请加入队伍 ;
	 * 2 : 有人邀请你加入队伍
	 */
	{ GCD_TEAM_NOTIFY_APPLY, "TEAM_NOTIFY_APPLY", },

	/*
	 * mainmenubar, 闪烁按钮. ;
	 * arg0 - 正整数, 从0开始 ;
	 * 0 : 表示已经加入队伍, 不需要闪烁按钮, 打开界面为队伍信息 ;
	 * 1 : 有人申请加入队伍 ;
	 * 2 : 有人邀请你加入队伍 ;
	 * 申请的人的具体信息从申请的信息队列中获得.
	 */
	{ GCD_TEAM_APPLY, "TEAM_APPLY", },

	/*
	 * 有人申请你加入队伍. ;
	 * ;
	 * arg0 - 字符串 ;
	 * 申请的人
	 */
	{ GCD_TEAM_INVITE, "TEAM_INVITE", },

	/*
	 * 有人邀请你加入队伍. ;
	 * ;
	 * arg0 - 字符串 ;
	 * 邀请你的人.
	 */
	{ GCD_TEAM_CLEAR_UI, "TEAM_HIDE_ALL_PLAYER", },

	/* 清空界面 */
	{ GCD_TEAM_REFRESH_UI, "TEAM_REFRESH_DATA", },

	/* 刷新界面 */
	{ GCD_TEAM_MEMBER_ENTER, "TEAM_ENTER_MEMBER", },

	/*
	 * 有新的队员进入 ;
	 * ;
	 * arg0 - 正整数, 从1 开始 ;
	 * 在ui界面中的显示位置
	 */
	{ GCD_TEAM_UPTEDATA_MEMBER_INFO, "TEAM_UPDATE_MEMBER", },

	/*
	 * 更新队员信息 ;
	 * arg0 - 正整数, 从1 开始 ;
	 * 在ui界面中的显示位置
	 */
	{ GCD_TEAM_MESSAGE, "TEAM_TEAM_MESSAGE", },

	/*
	 * 队伍信息提示信息 ;
	 * arg0 - 字符串 ;
	 * 需要提示的信息.
	 */
	{ GCD_TEAM_MEMBER_INVITE, "TEAM_MEMBER_INVITE", },

	/*
	 * 队员邀请某一个人加入队伍请求队长同意 ;
	 * ;
	 * arg0 - 队员名字 ;
	 * arg1 - 被邀请人的名字
	 */
	{ GCD_TEAM_FOLLOW_INVITE, "TEAM_FOLLOW_INVITE", },

	/*
	 * 队长邀请队员进入组队跟随模式 ;
	 * ;
	 * arg0 - 队长名?
	 */
	{ GCD_TEAM_REFRESH_MEMBER, "TEAM_REFRESH_MEMBER", },

	/*
	 * 刷新队员信息 ;
	 * ;
	 * arg0 - 队员的位置索引
	 */
	{ GCD_CHANGE_TEAM_ITEM_DISTRIB_MODE, "CHANGE_TEAM_ITEM_DISTRIB_MODE", },

	/*
	 * 改变分配模式, ;
	 * 以下以后需要删除. ;
	 * { GCD_ON_TEAM_ENTER_MEMBER, "TEAM_ENTER_MEMBER", },// 有新的队员进入
	 */
	{ GCD_UPDATE_TEAM_MEMBER, "ON_UPDATE_TEAM_MEMBER", },

	/* 更新队员信息 */
	{ GCD_SHOW_TEAM_YES_NO, "SHOW_TEAM_YES_NO", },

	/* 有人邀请你加入队伍. */
	{ GCD_SHOW_TEAM_MEMBER_INFO, "SHOW_PLAYER_INFO", },

	/* 显示队员的详细信息 */
	{ GCD_SHOW_TEAM_MEMBER_NAME, "SHOW_PLAYER_NAME", },

	/* 在左边的队友列表框中显示队友的名字 */
	{ GCD_HIDE_ALL_PLAYER, "HIDE_ALL_PLAYER", },

	/* 自己离开队伍后, 清空左边的队伍列表. */
	{ GCD_SHOW_TEAM_MEMBER_NICK, "SHOW_TEAM_NICK", },

	/* 昵称 */
	{ GCD_SHOW_TEAM_MEMBER_FAMILY, "SHOW_TEAM_FAMILY", },

	/* 职业 */
	{ GCD_SHOW_TEAM_MEMBER_LEVEL, "SHOW_TEAM_LEVEL", },

	/* 等级 */
	{ GCD_SHOW_TEAM_MEMBER_POS, "SHOW_TEAM_POS", },

	/* 位置 */
	{ GCD_SHOW_TEAM_MEMBER_HP, "SHOW_TEAM_HP", },

	/* hp */
	{ GCD_SHOW_TEAM_MEMBER_MP, "SHOW_TEAM_MP", },

	/* mp */
	{ GCD_SHOW_TEAM_MEMBER_ANGER, "SHOW_TEAM_ANGER", },

	/* 怒气 */
	{ GCD_SHOW_TEAM_MEMBER_DEAD_LINK, "SHOW_TEAM_DEAD_LINK", },

	/* 连线信息 */
	{ GCD_SHOW_TEAM_MEMBER_DEAD, "SHOW_TEAM_DEAD", },

	/* 死亡信息. */
	{ GCD_SHOW_TEAM_FUNC_MENU_MEMBER, "SHOW_TEAM_CONTEXMENU_MEMBER", },

	/* 显示队员的功能菜单 */
	{ GCD_SHOW_TEAM_FUNC_MENU_LEADER, "SHOW_TEAM_CONTEXMENU_LEADER", },

	/*
	 * 显示队长的功能菜单 ;
	 * 组队相关事件 ;
	 * ;
	 * 登录相关 ;
	 */
	{ GCD_GAMELOGIN_SHOW_SYSTEM_INFO, "GAMELOGIN_SHOW_SYSTEM_INFO", },

	/*
	 * 显示系统信息 ;
	 * ;
	 * arg0 - 字符串 : 需要提示的系统信息.
	 */
	{ GCD_GAMELOGIN_SHOW_SYSTEM_INFO_CLOSE_NET, "GAMELOGIN_SHOW_SYSTEM_INFO_CLOSE_NET", },

	/*
	 * 显示系统信息 ;
	 * ;
	 * arg0 - 字符串 : 需要提示的系统信息. ;
	 * 点击确认按钮后断开网络。
	 */
	{ GCD_GAMELOGIN_CLOSE_SYSTEM_INFO, "GAMELOGIN_CLOSE_SYSTEM_INFO", },

	/* 显示队长的功能菜单 */
	{ GCD_GAMELOGIN_OPEN_SELECT_SERVER, "GAMELOGIN_OPEN_SELECT_SERVER", },

	/* 关闭选择服务器界面 */
	{ GCD_GAMELOGIN_CLOSE_SELECT_SERVER, "GAMELOGIN_CLOSE_SELECT_SERVER", },

	/* 关闭选择服务器界面 */
	{ GCD_GAMELOGIN_OPEN_COUNT_INPUT, "GAMELOGIN_OPEN_COUNT_INPUT", },

	/* 打开帐号输入界面 */
	{ GCD_GAMELOGIN_CLOSE_COUNT_INPUT, "GAMELOGIN_CLOSE_COUNT_INPUT", },

	/* 关闭帐号输入界面 */
	{ GCD_GAMELOGIN_NOTIFY_COUNT_INPUT, "GAMELOGIN_NOTIFY_COUNT_INPUT", },
	{ GCD_GAMELOGIN_SHOW_SYSTEM_INFO_NO_BUTTON, "GAMELOGIN_SHOW_SYSTEM_INFO_NO_BUTTON", },

	/*
	 * 显示系统信息, 不显示按钮 ;
	 * ;
	 * arg0 - 字符串 : 需要提示的系统信息.
	 */
	{ GCD_GAMELOGIN_OPEN_SELECT_CHARACTOR, "GAMELOGIN_OPEN_SELECT_CHARACTOR", },

	/* 显示人物选择界面 */
	{ GCD_GAMELOGIN_CLOSE_SELECT_CHARACTOR, "GAMELOGIN_CLOSE_SELECT_CHARACTOR", },

	/* 关闭人物选择界面 */
	{ GCD_GAMELOGIN_OPEN_CREATE_CHARACTOR, "GAMELOGIN_OPEN_CREATE_CHARACTOR", },

	/* 显示人物创建界面 */
	{ GCD_GAMELOGIN_CLOSE_CREATE_CHARACTOR, "GAMELOGIN_CLOSE_CREATE_CHARACTOR", },

	/* 关闭人物关闭界面 */
	{ GCD_GAMELOGIN_REFRESH_ROLE_SELECT_CHARACTOR, "GAMELOGIN_REFRESH_ROLE_SELECT_CHARACTOR", },

	/* 刷新人物信息 */
	{ GCD_GAMELOGIN_CLOSE_BACK_GROUND, "GAMELOGIN_CLOSE_BACK_GROUND", },

	/* 关闭背景界面 */
	{ GCD_GAMELOGIN_SYSTEM_INFO_YESNO, "GAMELOGIN_SYSTEM_INFO_YESNO", },

	/*
	 * 系统信息提示 yes_no 界面. ;
	 * ;
	 * 参数0, 提示的字符串 ;
	 * 参数1, 对话框的类型 ;
	 * 0 -- 是否退出游戏 ;
	 * 1 -- 是否删除角色 ;
	 * 2 -- 是否更换帐号
	 */
	{ GCD_GAMELOGIN_SELECT_LOGIN_SERVER, "GAMELOGIN_SELECT_LOGIN_SERVER", },

	/*
	 * 选择一个login server ;
	 * ;
	 * 参数0, iAreaIndex 区域索引 ;
	 * 参数1, iLoginServer 区域索引
	 */
	{ GCD_GAMELOGIN_CLEAR_ACCOUNT, "GAMELOGIN_CLEAR_ACCOUNT" },

	/* 清空帐号显示. */
	{ GCD_GAMELOGIN_SELECT_AREA, "GAMELOGIN_SELECT_AREA" },

	/* 选择区域 */
	{ GCD_GAMELOGIN_SELECT_LOGINSERVER, "GAMELOGIN_SELECT_LOGINSERVER" },

	/* 选择Login Server */
	{ GCD_GAMELOGIN_CREATE_CLEAR_NAME, "GAMELOGIN_CREATE_CLEAR_NAME" },

	/* 清空创建角色名字 */
	{ GCD_GAMELOGIN_CREATE_ROLE_OK, "GAMELOGIN_CREATE_ROLE_OK" },

	/*
	 * 创建角色成功 ;
	 * ;
	 * 登录相关 ;
	 */
	{ GCD_TOGLE_SKILLSTUDY, "TOGLE_SKILLSTUDY", },

	/* 职业技能学习界面 */
	{ GCD_SKILLSTUDY_SUCCEED, "SKILLSTUDY_SUCCEED", },

	/* 职业技能学习界面 */
	{ GCD_TOGLE_ABILITY_STUDY, "TOGLE_ABILITY_STUDY" },

	/* 生活技能学习界面 */
	{ GCD_TOGLE_ABILITY_STUDY_CLOSE, "TOGLE_ABILITY_STUDY_CLOSE" },

	/* 关闭生活技能学习界面 */
	{ GCD_SUPERTOOLTIP, "SHOW_SUPERTOOLTIP" },

	/* 显示超级tooltip */
	{ GCD_UPDATE_SUPERTOOLTIP, "UPDATE_SUPERTOOLTIP" },

	/* 刷新超级tooltip */
	{ GCD_SHOW_SUPERTOOLTIP_TITLE, "SHOW_SUPERTOOLTIP_TITLE" },

	/* 刷新超级tooltip //temp */
	{ GCD_SHOW_COMPARETOOLTIP, "SHOW_COMPARETOOLTIP" },

	/* 物品比较 */
	{ GCD_SHOW_COMPARETOOLTIP_REPOS, "SHOW_COMPARETOOLTIP_REPOS" },

	/* 物品比较重新定位 */
	{ GCD_HIDE_TOOLTIP, "HIDE_TOOLTIP" },

	/*
	 * ;
	 * 复活界面相关 ;
	 */
	{ GCD_RELIVE_SHOW, "RELIVE_SHOW", },

	/* 显示复活界面 */
	{ GCD_RELIVE_HIDE, "RELIVE_HIDE", },

	/* 隐藏复活界面 */
	{ GCD_RELIVE_REFESH_TIME, "RELIVE_REFESH_TIME", },

	/* 刷新灵魂出窍的时间 */
	{ GCD_RELIVE_ACTIVE, "RELIVE_ACTIVE", },

	/* 重新激活复活界面的按钮 */
	{ GCD_OBJECT_CARED_EVENT, "OBJECT_CARED_EVENT", },
	{ GCD_UPDATE_MAP, "UPDATE_MAP", },
	{ GCD_UPDATE_NPC_MAP, "UPDATE_NPC_MAP", },
	{ GCD_UPDATE_TRANSFER_MAP, "UPDATE_TRANSFER_MAP", },
	{ GCD_UI_COMMAND, "UI_COMMAND", },
	{ GCD_OTHERPLAYER_UPDATE_EQUIP, "OTHERPLAYER_UPDATE_EQUIP", },
	{ GCD_TOGLE_ONLINEUSER_EQUIP_ALL, "TOGLE_ONLINEUSER_EQUIP_ALL" },
	{ GCD_VARIABLE_CHANGED, "VARIABLE_CHANGED", TRUE },

	/* 全局变量发生改变 */
	{ GCD_TIME_UPDATE, "TIME_UPDATE", },
	{ GCD_UPDATE_FRIEND, "UPDATE_FRIEND", },

	/* 好友数据更新了 */
	{ GCD_UPDATE_FRIEND_INFO, "UPDATE_FRIEND_INFO", },
	{ GCD_OPEN_FRIEND_SEARCH, "OPEN_FRIEND_SEARCH", },

	/* 好友搜索 */
	{ GCD_OPEN_FRIEND_SEARCH_REASON, "OPEN_FRIEND_SEARCH_REASON", },

	/* 好友搜索结果 */
	{ GCD_UPDATE_TARGETPET_PAGE, "UPDATE_TARGETPET_PAGE", },
	{ GCD_UPDATE_PETSKILLSTUDY, "UPDATE_PETSKILLSTUDY", },
	{ GCD_UPDATE_PETINVITEFRIEND, "UPDATE_PETINVITEFRIEND", },
	{ GCD_REPLY_QUEST_PET, "REPLY_MISSION_PET", },

	/*
	 * 是否设置二级保护密码 ;
	 * ;
	 * { GCD_MINORPASSWORD_OPEN_SET_PASSWORD_DLG,
	 * "MINORPASSWORD_OPEN_SET_PASSWORD_DLG", }, // 打开设置二级密码界面 ;
	 * { GCD_MINORPASSWORD_OPEN_UNLOCK_PASSWORD_DLG,
	 * "MINORPASSWORD_OPEN_UNLOCK_PASSWORD_DLG", }, // 打开unlock密码界面。 ;
	 * { GCD_MINORPASSWORD_OPEN_CHANGCD_PASSWORD_DLG,
	 * "MINORPASSWORD_OPEN_CHANGCD_PASSWORD_DLG", }, // 打开更改密码界面。
	 */
	{ GCD_OPEN_SYSTEM_TIP_INFO_DLG, "OPEN_SYSTEM_TIP_INFO_DLG", },

	/* 提示系统信息对话框。 */
	{ GCD_INPUT_PASSWORD_DLG, "INPUT_PASSWORD_DLG", },

	/* 输入二级密码界面。 */
	{ GCD_INPUT_SUPER_PW_DLG, "INPUT_SUPER_PW_DLG", },
				
	// 追踪符窗口
	{ GCD_INPUT_FIND_PLAYER_ITEM_DLG, "INPUT_FIND_PLAYER_ITEM_DLG", },

	/*
	 * 输入超级密码界面。 ;
	 * 帮会相?
	 */
	{ GCD_GUILD_CREATE, "GUILD_CREATE", },

	/* 帮会创建事件 */
	{ GCD_GUILD_CREATE_CONFIRM, "GUILD_CREATE_CONFIRM", },

	/* 帮会创建确认事件 */
	{ GCD_GUILD_SHOW_LIST, "GUILD_SHOW_LIST", },

	/* 显示帮会列表事件 */
	{ GCD_GUILD_SHOW_MEMBERINFO, "GUILD_SHOW_MEMBERINFO", },

	/* 显示自己帮会成员管理界面 */
	{ GCD_GUILD_TOGGLE, "GUILD_TOGGLE", },

	/* 玩家按下帮会快捷键事件 */
	{ GCD_GUILD_SHOW_DETAILINFO, "GUILD_SHOW_DETAILINFO", },

	/* 显示自己帮会详细信息界面 */
	{ GCD_GUILD_SHOW_APPOINTPOS, "GUILD_SHOW_APPOINTPOS", },

	/* 显示自己帮会可用职位界面 */
	{ GCD_GUILD_DESTORY_CONFIRM, "GUILD_DESTORY_CONFIRM", },

	/* 删除帮会确认事件 */
	{ GCD_GUILD_QUIT_CONFIRM, "GUILD_QUIT_CONFIRM", },

	/* 退出帮会确认事件 */
	{ GCD_GUILD_UPDATE_MEMBERINFO, "GUILD_UPDATE_MEMBERINFO", },

	/* 更新帮会成员的信息 */
	{ GCD_GUILD_FORCE_CLOSE, "GUILD_FORCE_CLOSE", },

	/* 强制帮会相关界面关闭事件 */
	{ GCD_GUILD_INVITE_OBJECT, "GUILD_INVITE_OBJECT", },

	/* 显示邀请对话框 */
	{ GCD_GUILD_NOTIFY_INTIVE, "GUILD_NOTIFY_INTIVE", },

	/* 闪烁帮会按钮， 提示收到邀请 */
	{ GCD_GUILD_INTIVE_CONFIRM, "GUILD_INTIVE_CONFIRM", },

	/* 邀请确认 */
	{ GCD_GUILD_EVENT, "GUILD_EVENT", },

	/*
	 * 帮会中唯一的事件，事件中有type来区分具体的事件，这样子所有的事件都统一处理 add
	 * by wujianping
	 */
	{ GCD_GUILD_MODIFY_TITLE, "GUILD_MODIFY_TITLE", },

	/* 修改成员称号 */
	{ GCD_GUILD_MOVE_USER_TO_FAMILY, "GUILD_MOVE_USER_TO_FAMILY", },

	/* 转移成员到一个家族 */
	{ GCD_GUILD_CREATE_FAMILY, "GUILD_CREATE_FAMILY", },

	/* 创建家族确认 */
	{ GCD_GUILD_CREATE_FAMILY_CONFIRM, "GUILD_CREATE_FAMILY_CONFIRM", },

	/* 创建家族确认 */
	{ GCD_GUILD_DESTORY_FAMILY_CONFIRM, "GUILD_DESTORY_FAMILY_CONFIRM", },

	/* 删除家族确认 */
	{ GCD_GUILD_LEVEL_UP, "GUILD_LEVEL_UP", },

	/* 帮会升级事件 */
	{ GCD_GUILD_SHOW_LIST_CARENPC, "GUILD_SHOW_LIST_CARENPC", },

	/* 打开帮会列表时关系NPC */
	{ GCD_INPUT_PASSWD_COMMAND, "INPUT_PASSWD_COMMAND", },

	/* 通过输入密码触发 */
	{ GCD_GUILD_KICK_CONFIRM, "GUILD_KICK_CONFIRM", },

	/*
	 * 帮会踢人确认 ;
	 * 任务相关
	 */
	{ GCD_CLOSE_QUEST_REPLY, "CLOSE_MISSION_REPLY", },
	{ GCD_VIEW_RESOLUTION_CHANGED, "VIEW_RESOLUTION_CHANGED", },
	{ GCD_CLOSE_SYNTHESIZE_ENCHASE, "CLOSE_SYNTHESIZE_ENCHASE", },
	{ GCD_TOGGLE_PETLIST, "TOGGLE_PETLIST", },
	{ GCD_PET_FREE_CONFIRM, "PET_FREE_CONFIRM", },
	{ GCD_OPEN_BUY_CONFIRM, "OPEN_BUY_CONFIRM", },
	{ GCD_OPEN_SALE_CONFIRM, "OPEN_SALE_CONFIRM", },
	{ GCD_FRIEND_CREATE_GROUP, "FRIEND_ADD_GROUP", },
	{ GCD_SEARCH_MASTER, "SEARCH_MASTER", },
	{ GCD_SEARCH_PRENTICE, "SEARCH_PRENTICE", },
	{ GCD_REQUEST_MARRY, "REQUEST_MARRY", },

	/* 添加好友新组 */
	{ GCD_ADD_GROUP, "ADD_GROUP", },

	/* 显示详细信息 */
	{ GCD_SHOW_FRIEND_INFO, "SHOW_FRIEND_INFO", },
	{ GCD_QUICK_CHANGCD_NAME, "QUICK_CHANGE_NAME", },

	/* 物品链接 */
	{ GCD_ITEM_LINK, "ITEM_LINK", },

	/* 任务连接 */
	{ GCD_QUEST_LINK, "MISSION_LINK", },

	/* 坐骑连接 */
	{ GCD_HORSE_LINK, "HORSE_LINK", },

	/* 技能连接 */
	{ GCD_SKILL_LINK, "SKILL_LINK", },

	/* 任务连接显示界面 */
	{ GCD_QUEST_SUPER_TOOLTIP_SHOW, "MISSION_SUPER_TOOLTIP_SHOW", },

	/* 技能连接显示界面 */
	{ GCD_SKILL_SUPER_TOOLTIP_SHOW, "SKILL_SUPER_TOOLTIP_SHOW", },

	/* 打开装备牌型交换界面 */
	{ GCD_EQUIP_SWAPCARD_OPEN, "EQUIP_SWAPCARD_OPEN", },

	/* 更新装备牌型交换界面 */
	{ GCD_EQUIP_SWAPCARD_UPDATA, "EQUIP_SWAPCARD_UPDATA", },

	/* 装备牌型交换成功 */
	{ GCD_EQUIP_SWAPCARD_SUCESS, "EQUIP_SWAPCARD_SUCESS", },

	/* 打开装备牌型改造界面 */
	{ GCD_EQUIP_CHANGECARD_OPEN, "EQUIP_CHANGECARD_OPEN", },

	/* 更新装备牌型改造界面 */
	{ GCD_EQUIP_CHANGECARD_UPDATA, "EQUIP_CHANGECARD_UPDATA", },

	/* 装备牌型改造成功 */
	{ GCD_EQUIP_CHANGECARD_SUCESS, "EQUIP_CHANGECARD_SUCESS", },

	/* 称号表 */
	{ GCD_SHOW_TITLE, "SHOW_TITLE", },
	{ GCD_UPDATE_TITLE, "UPDATE_TITLE", },

	/* 系统和人物的信息 */
	{ GCD_PERSONAL_MESSAGE, "PERSONAL_MESSAGE", },
	{ GCD_SYSTEM_MESSAGE, "SYSTEM_MESSAGE", },
	{ GCD_PARALLEL_MESSAGE, "PARALLEL_MESSAGE", },

	/*
	 * 水平消息 ;
	 * 系统信息提示图标
	 */
	{ GCD_SHOW_SYSTEM_PROMPT, "SHOW_SYSTEM_PROMPT", },
	{ GCD_OPERATE_SYSTEM_PROMPT, "OPERATE_SYSTEM_PROMPT", },
	{ GCD_UNITE_GF_SHOW, "UNITE_GF_SHOW", },
	{ GCD_MASTER_OR_PRENTICE, "MASTER_OR_PRENTICE", },

	/* 师徒 */
	{ GCD_RICH_SAFE_GUARD, "RICH_SAFE_GUARD", },

	/* 保护范围界面 */
	{ GCD_RICH_SAFE_TIME, "RICH_SAFE_TIME", },

	/* 安全时限弹出界面 */
	{ GCD_UPDATE_RICH_SAFE_TIME, "UPDATE_RICH_SAFE_TIME", },

	/* 更新安全时限 */
	{ GCD_RICH_SET_PASSWORD, "RICH_SET_PASSWORD", },

	/* 设置密码、修改密码界面 */
	{ GCD_RICH_MODIFY_PASSWORD, "RICH_MODIFY_PASSWORD", },
	{ GCD_RICH_SETUP, "RICH_SETUP", },

	/* 财产保护功能设置界面 */
	{ GCD_OPEN_RICHES_PROTECT_FRAME, "OPEN_RICHES_PROTECT_FRAME", },

	/* 财产保护提示界面 */
	{ GCD_RICH_TEMP_CANCEL_PASSWORD, "RICH_TEMP_CANCEL_PASSWORD", },

	/* 临时取消密码 */
	{ GCD_RICH_CANCEL_PASSWORD, "RICH_CANCEL_PASSWORD", },

	/* 取消密码 */
	{ GCD_RICH_CHECK_PASSWORD, "RICH_CHECK_PASSWORD", },

	/* 检测输入密码 */
	{ GCD_RICH_SAFE_TIME_TIP, "RICH_SAFE_TIME_TIP", },

	/* 安全时间提示 */
	{ GCD_RICH_DELETE_PWD_TIME_TIP, "RICH_DELETE_PWD_TIME_TIP", },

	/*
	 * 删除密码保护的剩余时间上线提示 ;
	 * temp
	 */
	{ GCD_TEMP_CLOSE_FRIEND, "TEMP_CLOSE_FRIEND", },
	{ GCD_TEMP_CLOSE_GUILD, "TEMP_CLOSE_GUILD", },
	{ GCD_ADD_FRIEND, "ADD_FRIEND", },
	{ GCD_FRIEND_EVENT, "FRIEND_EVENT", },
	{ GCD_FRIEND_CONFIRM_EVENT, "FRIEND_CONFIRM_EVENT", },

	/* 打开装备 个人资料 宠物等6个界面 */
	{ GCD_EQUIP_ALL_OPEN, "EquipAll_OPEN", },

	/* 打开装备 个人资料 宠物等6个界面 */
	{ GCD_EQUIP_ALL_CLOSE, "EquipAll_ClOSE", },
	{ GCD_AUTOREPLY_RECV_MSG, "AUTOREPLY_RECV_MSG", },

	/* 人物详细属性界面 */
	{ GCD_TOGLE_PLAYER_ATTR_PAGE, "TOGLE_PLAYER_ATTR_PAGE", },
	{ GCD_CLOSE_PLAYER_ATTR_PAGE, "CLOSE_PLAYER_ATTR_PAGE", },

	/* 新增属性 */
	{ GCD_TOGLE_PLAYER_ATTR2_PAGE, "TOGLE_PLAYER_ATTR2_PAGE", },
	{ GCD_CLOSE_PLAYER_ATTR2_PAGE, "CLOSE_PLAYER_ATTR2_PAGE", },

	/* 打开每日提醒功能界面 */
	{ GCD_OPEN_DAY_TIPS, "OPEN_DAY_TIPS", },

	/* 每日提醒可显示列表更新 */
	{ GCD_UPDATE_DAY_TIPS_DISPLAYLIST, "UPDATE_DAY_TIPS_DISPLAYLIST" },

	/* 更新每日提醒日期 */
	{ GCD_UPDATE_DATE_TIME, "UPDATE_DATE_TIME", },

	/* 更新每日提醒内容 */
	{ GCD_UPDATE_DAY_TIPS, "UPDATE_DAY_TIPS", },

	/* 更新月历内容 */
	{ GCD_UPDATE_CALENDAR, "UPDATE_CALENDAR", },

	/* 更新退出月历内容 */
	{ GCD_QUIT_UPDATE_CALENDAR, "QUIT_UPDATE_CALENDAR", },

	/* 打开排行榜界面 */
	{ GCD_OPEN_TOP_LIST, "OPEN_TOP_LIST", },

	/* 更新排行榜界面 */
	{ GCD_UPDATE_TOP_LIST, "UPDATE_TOP_LIST", },

	/* 等级排行榜 */
	{ GCD_LEVEL_TOP_LIST, "LEVEL_TOP_LIST", },

	/* 财富排行榜 */
	{ GCD_MONEY_TOP_LIST, "MONEY_TOP_LIST", },
	{ GCD_NO_TOPLIST_INFO, "NO_TOPLIST_INFO", },
	{ GCD_UPDATE_TOPLIST_PERSONINFO, "UPDATE_TOPLIST_PERSONINFO" },

	/* 打开任务跟踪界面 */
	{ GCD_OPEN_QUEST_SCOUT, "OPEN_MISSION_SCOUT", },

	/* 更新任务跟踪界面 */
	{ GCD_UPDATE_QUEST_SCOUT, "UPDATE_MISSION_SCOUT", },

	/* 刷新任务跟踪面板上的时间倒计时 */
	{ GCD_UPDATE_TIME_QUEST, "UPDATE_TIME_MISSION", },
	{ GCD_UPDATE_TIME_QUEST_SET_QUEST_NAME, "UPDATE_TIME_MISSION_SET_MISSION_NAME", },
	{ GCD_UPDATE_TIME_QUEST_SET_TOTAL_TIME, "UPDATE_TIME_MISSION_SET_TOTAL_TIME", },
	{ GCD_UPDATE_TIME_QUEST_SET_EVENT_TIME, "UPDATE_TIME_MISSION_SET_EVENT_TIME", },
	{ GCD_UPDATA_EQUIP_ALL_POS, "UPDATA_EQUIP_ALL_POS", },
	{ GCD_COUNTRY_MANAGER_CREATE_KING, "COUNTRY_MANAGER_CREATE_KING", },

	/* 产生国王 */
	{ GCD_COUNTRY_KING_CREATE_CONFIRM, "COUNTRY_KING_CREATE_CONFIRM", },

	/* 确认产生国王 */
	{ GCD_COUNTRY_MANAGER_KING_COLLECT, "COUNTRY_MANAGER_KING_COLLECT", },

	/* 募捐 */
	{ GCD_COUNTRY_MANAGER_REQUEST_INFO, "COUNTRY_MANAGER_REQUEST_INFO", },

	/* 请求国家信息 */
	{ GCD_COUNTRY_MANAGER_INFO, "COUNTRY_MANAGER_INFO", },

	/* 国家信息 */
	{ GCD_COUNTRY_MANAGER_ADJUST_AUTH, "COUNTRY_MANAGER_ADJUST_AUTH", },

	/* 国家官职调整 */
	{ GCD_INPUT_COUNTRY_DLG, "INPUT_COUNTRY_DLG", },

	/* 输入国家官职 */
	{ GCD_SHOW_EQUIP_CONTEXMENU, "SHOW_EQUIP_CONTEXMENU" },

	/* 装备右键菜单 */
	{ GCD_CLOSE_EQUIP_CONTEXMENU, "CLOSE_EQUIP_CONTEXMENU" },
	{ GCD_FILL_TEAM_MEMBER, "FILL_TEAM_MEMBER", },

	/* 填充队员信息 */
	{ GCD_FILL_TEAM_INFO, "FILL_TEAM_INFO", },

	/* 填充队伍信息 */
	{ GCD_FILL_TEAMSEARCH_INFO, "FILL_TEAMSEARCH_INFO", },

	/*
	 * 填充寻求组队信息 ;
	 * 骑乘征友
	 */
	{ GCD_MOUNT_FRIEND_SETUI_SHOW, "GCD_MOUNT_FRIEND_SETUI_SHOW" },

	/* 设定界面 */
	{ GCD_MOUNT_FRIEND_SEARCHUI_SHOW, "GCD_MOUNT_FRIEND_SEARCHUI_SHOW" },

	/* 查询界面 */
	{ GCD_MOUNT_FRIEND_VIEWUI_SHOW, "GCD_MOUNT_FRIEND_VIEWUI_SHOW" },

	/* 查看界面 */
	{ GCD_MOUNT_FRIEND_INITINFO, "GCD_MOUNT_FRIEND_INITINFO" },

	/* 显示相关信息 */
	{ GCD_SAMECITY_PLAYER_UPDATEUI, "GE_SAMECITY_PLAYER_UPDATEUI" },

	/* 更新同城玩家界面 */
	{ GCD_TOGLE_CHATQUERY, "TOGLE_CHATQUERY", },

	/* [ ZG ] 聊天历史记录界面 */
	{ GCD_TOGLE_SUBTRAIN_PAGE, "TOGLE_SUBTRAIN_PAGE", },

	/* 带练界面 */
	{ GCD_UPDATE_SUBTRAIN_PAGE, "UPDATE_SUBTRAIN_PAGE", },
	{ GCD_PK_MODE_CHANGED, "PK_MODE_CHANGED", },

	/* by soongxl */
	{ GCD_SUB_TRAIN_EXP_DLG, "SUB_TRAIN_EXP_DLG", },

	/* 带练界面 */
	{ GCD_SUB_TRAIN_GETEXP_DLG, "SUB_TRAIN_GETEXP_DLG", },

	/* 摆摊相关 */
	{ GCD_CLOSE_STALL_SALE, "CLOSE_STALL_SALE", },
	{ GCD_STALL_SAVE_DLG, "STALL_SAVE_DLG", },

	/* 摆摊保存 */
	{ GCD_SHORTCUT_KEYDOWN, "SHORTCUT_KEYDOWN", },

	/* 快捷键按下事件 */
	{ GCD_SHORTCUT_KEYUP, "SHORTCUT_KEYUP", },

	/* 快捷键松开事件 */
	{ GCD_EXTENT_SHORTCUT, "EXTENT_SHORTCUT" },

	/* 扩展快捷键事件 */
	{ GCD_SHORTCUT_RIGHTBAR, "SHORTCUT_RIGHTBAR" },

	/* 右侧快捷栏快捷键消息 */
	{ GCD_EXTEND_SHORTCUT_SHOW, "EXTEND_SHORTCUT_SHOW", },

	/* 扩展快捷栏 */
	{ GCD_GUAJI_SHOW, "GUAJI_SHOW", },

	/* 挂机界面 */
	{ GCD_GUAJI_UPDATE, "GUAJI_UPDATE", },

	/* 挂机更新 */
	{ GCD_TOGGLE_GUAJI, "TOGGLE_GUAJI", },

	/* 081105（齐亮）切换挂机开关 */
	{ GCD_DOUBLEACTION_REQUEST, "GCD_DOUBLEACTION_REQUEST", },

	/* 国家 */
	{ GCD_COUNTRY_EVENT, "COUNTRY_EVENT", },

	/*
	 * 国家中唯一的事件，事件中有type来区分具体的事件，这样子所有的事件都统一处理 add
	 * by wujianping
	 */
	{ GCD_OPEN_DONATEPUTOUT, "OPEN_DONATEPUTOUT", },

	/* 发起募捐 */
	{ GCD_OPEN_DONATE, "OPEN_DONATE", },

	/* 提交募捐界面 */
	{ GCD_COUNTRY_DELATE, "COUNTRY_DELATE", },

	/* 弹劾界面 */
	{ GCD_COUNTRY_VOTEON, "COUNTRY_VOTEON", },
	{ GCD_OPEN_REGISTRATION, "OPEN_REGISTRATION", },
	{ GCD_OTHER_TEAM_INFO, "OTHER_TEAM_INFO", },

	/* 其他队伍信息界面 */
	{ GCD_OTHER_TEAM_INFO_HIDE, "OTHER_TEAM_INFO_HIDE", },

	/* 比武邀请取消 */
	{ GCD_TOGLE_TREASUREBOX_PAGE, "TOGLE_TREASUREBOX_PAGE", },
	{ GCD_CLOSE_TREASUREBOX_PAGE, "CLOSE_TREASUREBOX_PAGE", },
	{ GCD_TREASUREBOX_UPDATE, "TREASUREBOX_UPDATE", },
	{ GCD_TREASUREBOX_GETITEM_RESULT, "TREASUREBOX_GETITEM_RESULT", },
	{ GCD_UPDATA_EQUIP_REWORK, "UPDATA_EQUIP_REWORK", },
	{ GCD_UNLOCK_ITEM_ONLEAVE, "UNLOCK_ITEM_ONDEAD" },
	{ GCD_NAME_INPUT_ERROR, "NAME_INPUT_ERROR", },

	/* 输入的名字不合法 */
	{ GCD_NAME_INPUT_EMPTY, "NAME_INPUT_EMPTY", },

	/* 输入的名字为空 */
	{ GCD_UPDATA_SELF_ATTR, "UPDATA_SELF_ATTR", },
	{ GCD_CREATE_BUS, "CREATE_BUS", },

	/* 创建bus */
	{ GCD_OPEN_BUS, "OPEN_BUS", },

	/* 打开bus */
	{ GCD_UPDATE_BUS, "UPDATE_BUS", },

	/* 更新bus信息 */
	{ GCD_OPEN_CASHBUS, "OPEN_CASHBUS", },

	/* 打开cashbus */
	{ GCD_LOGIN_KEYPRESS, "LOGIN_KEYPRESS", },
	{ GCD_EFFECT_UI_OPEN, "EFFECT_UI_OPEN", },

	/* ui特效 */
	{ GCD_EFFECT_UI_CLOSE, "EFFECT_UI_CLOSE", },
	{ GCD_MENTAL_GAME_ASK_SIGNUP, "MENTAL_GAME_ASK_SIGNUP" },

	/* 答题 */
	{ GCD_MENTAL_GAME_INTERFACE, "MENTAL_GAME_INTERFACE" },

	/* 答题 */
	{ GCD_MENTAL_GAME_THINK, "MENTAL_GAME_THINK" },

	/* 答题 */
	{ GCD_MENTAL_GAME_QUIZ, "MENTAL_GAME_QUIZ" },

	/* 答题 */
	{ GCD_MENTAL_GAME_WENCAI, "MENTAL_GAME_WENCAI" },

	/* 答题 */
	{ GCD_MENTAL_GAME_SCORE, "MENTAL_GAME_SCORE" },

	/* 答题 */
	{ GCD_MENTAL_GAME_SORTID, "MENTAL_GAME_SORTID" },

	/* 答题 */
	{ GCD_MENTAL_GAME_FINISHED, "MENTAL_GAME_FINISHED" },

	/* 答题 */
	{ GCD_MENTAL_GAME_ANSWER_RESULT, "MENTAL_GAME_ANSWER_RESULT" },

	/* 答题 */
	{ GCD_MENTAL_GAME_CLOSE_INTERFACE, "MENTAL_GAME_CLOSE_INTERFACE" },

	/* 答题 */
	{ GCD_TOGLE_VALIDATE, "TOGLE_VALIDATE", },

	/* 打开|关闭防外挂认证窗口 */
	{ GCD_UPDATE_VALIDATE, "UPDATE_VALIDATE", },
	{ GCD_QUIT_GAME_CONFIRM, "QUIT_GAME_CONFIRM", },

	/* 退出游戏确认 */
	{ GCD_RETURN_LOGIN_CONFIRM, "RETURN_LOGIN_CONFIRM", },

	/* 返回登陆界面确认 */
	{ GCD_QUIT_GAME_TIME_UPDATA, "QUIT_GAME_TIME_UPDATA", },

	/* 退出游戏更新 */
	{ GCD_RECONNECT_SERVER, "RECONNECT_SERVER" },

	/* 重新连接服务器 */
	{ GCD_RECONNECT_SERVER_UPDATA, "RECONNECT_SERVER_UPDATA" },

	/* 重新连接服务器的时间更新 */
	{ GCD_OPEN_CONVOYBUS, "OPEN_CONVOYBUS", },

	/* 打开帮会运镖界面 */
	{ GCD_ASK_GUILDCONVOY, "ASK_GUILDCONVOY", },

	/* 询问帮会运镖 */
	{ GCD_ASK_GUILDCONVOY_QUEST, "ASK_GUILDCONVOY_MISSION", },

	/* 询问是否接受帮会运镖任务 */
	{ GCD_TOGLE_GUILDCONVOY_INFOLIST, "TOGLE_GUILDCONVOY_INFOLIST", },

	/* 询问是否接受帮会运镖任务 */
	{ GCD_GUILDCONVOY_INFO_UPDATE, "GUILDCONVOY_INFO_UPDATE", },

	/* 更新 */
	{ GCD_UPDATE_PING, "UPDATE_PING", },

	/* 游戏网络状态 */
	{ GCD_THIRD_SHORTCUT_SHOW, "THIRD_SHORTCUT_SHOW", },

	/*
	 * 第三快捷栏 ;
	 * { GCD_SEND_MOOD_ANIM, "SEND_MOOD_ANIM", }, // 发送表情动作
	 */
	{ GCD_TOGLE_MOUNT_CLEARPOINT, "TOGLE_MOUNT_CLEARPOINT", },

	/* 打开/关闭骑乘洗点界面 */
	{ GCD_MOUNT_CLEARPOINT_ITEM_UPDATE, "MOUNT_CLEARPOINT_ITEM_UPDATE", },

	/* 打开/关闭骑乘洗点界面 */
	{ GCD_ASK_INTO_BUS, "ASK_INTO_BUS", },

	/* 请求进入战车 */
	{ GCD_INVITE_TO_BUS, "INVITE_TO_BUS", },

	/* 邀请进入战车 */
	{ GCD_UPDATE_BUS_STATE, "UPDATE_BUS_STATE", },

	/* 更新bus按钮状态 */
	{ GCD_UNIT_MONEYMODE, "UNIT_MONEYMODE", TRUE },

	/* 修改消费模式 */
	{ GCD_OPEN_NPC_FINDPATH, "OPEN_NPC_FINDPATH", },

	/* NPC自动寻路 */
	{ GCD_OPEN_WORLDMAP, "OPEN_WORLDMAP", },

	/* 世界地图 */
	{ GCD_OPEN_TRIP_MAP, "OPEN_TRIP_MAP", },

	/* 传送门（马车夫传送） */
	{ GCD_ESCAPE_HIDE_MESSAGE, "ESCAPE_HIDE_MESSAGE", },

	/* ESC统一隐藏消息 */
	{ GCD_WINDOW_SHOW, "WINDOW_SHOW", },
	{ GCD_OPEN_GOLD_EXCHANGE, "OPEN_GOLD_EXCHANGE", },
	{ GCD_CLOSE_GOLD_EXCHANGE, "CLOSE_GOLD_EXCHANGE", },
	{ GCD_OPEN_GOLDCARD_EXCHANGE, "OPEN_GOLDCARD_EXCHANGE", },
	{ GCD_CLOSE_GOLDCARD_EXCHANGE, "CLOSE_GOLDCARD_EXCHANGE", },
	{ GCD_OPEN_QUIZQUEST_INTERFACE, "OPEN_QUIZQUEST_INTERFACE", },

	/* 开启科举大富翁界面 */
	{ GCD_CLOSE_QUIZQUEST_INTERFACE, "CLOSE_QUIZQUEST_INTERFACE", },

	/* 关闭科举大富翁界面 */
	{ GCD_FLASH_QUIZQUEST_TIME, "FLASH_QUIZQUEST_TIME", },

	/* 刷新科举大富翁时间 */
	{ GCD_UPDATE_MIXTURE, "UPDATE_MIXTURE", },

	/* 刷新道具合成面板（合成红绳等） */
	{ GCD_UPDATE_MIXTURE_SUCC, "UPDATE_MIXTURE_SUCC", },

	/* 任务道具合成成功时 */
	{ GCD_UPDATE_MIXTURE_FAIL, "UPDATE_MIXTURE_FAIL", },

	/* 任务道具合成完成但是未成功 */
	{ GCD_FLASH_QUIZQUEST_TIME, "FLASH_QUIZQUEST_TIME", },

	/* 刷新科举大富翁时间 */
	{ GCD_UNIT_FASHIONMODE, "UNIT_FASHIONMODE", },

	/* 刷新科举大富翁时间 */
	{ GCD_WINDOW_INPUT_KEY, "WINDOW_INPUT_KEY", },
	{ GCD_WINDOW_INPUT_MOUSE, "WINDOW_INPUT_MOUSE", },
	{ GCD_ASK_COUNTRY_DESTROY_ISSUE, "ASK_COUNTRY_DESTROY_ISSUE", },

	/* 国王拉人 */
	{ GCD_ASK_GUILD_BATTLE, "ASK_GUILD_BATTLE", },

	/* 帮会战 */
	{ GCD_OPEN_BATTLE_INTERFACE, "OPEN_BATTLE_INTERFACE", },

	/* 开启战场界面 */
	{ GCD_REFRESH_BATTLE_INFO, "REFRESH_BATTLE_INFO", },

	/* 更新战场信息 */
	{ GCD_TOGLE_MOUNT_TF_PAGE, "TOGLE_MOUNT_TF_PAGE", },
	{ GCD_MOUNT_TF_ITEM_UPDATE, "MOUNT_TF_ITEM_UPDATE", },
	{ GCD_PLAY_IMPACT, "PLAY_IMPACT", },
	{ GCD_RICH_MODIFY_PASSWORD_CLOSE, "RICH_MODIFY_PASSWORD_CLOSE", },
	{ GCD_UNLOAD_OPERATOR_ITEM, "UNLOAD_OPERATOR_ITEM", },
	{ GCD_TOGLE_VIEWSKILL_PAGE, "TOGLE_VIEWSKILL_PAGE" },
	{ GCD_OPEN_VIEWSKILL_PAGE, "OPEN_VIEWSKILL_PAGE", },
	{ GCD_VIEWSKILL_UPDATE, "VIEWSKILL_UPDATE" },
	{ GCD_SCENEMAP_FLASH_POINT, "SCENEMAP_FLASH_POINT" },
	{ GCD_SCENEMAP_COUNTRYFIGHTALARM, "SCENEMAP_COUNTRYFIGHTALARM" },

	/* 国家人员被杀地图显示信息 */
	{ GCD_SCENEMAP_COUNTRYFIGHTCLICK, "SCENEMAP_COUNTRYFIGHTCLICK" },

	/* 国家人员被杀显示信息点击事件 */
	{ GCD_SUPERTOOLTIPCMPF, "SHOW_SUPERTOOLTIPCMPF" },

	/* 显示超级tooltipCMPF */
	{ GCD_UPDATE_SUPERTOOLTIPCMPF, "UPDATE_SUPERTOOLTIPCMPF" },

	/* 刷新超级tooltipCMPF */
	{ GCD_HIDE_TOOLTIPCMPF, "HIDE_TOOLTIPCMPF" },
	{ GCD_SUPERTOOLTIPCMPS, "SHOW_SUPERTOOLTIPCMPS" },

	/* 显示超级tooltipCMPS */
	{ GCD_UPDATE_SUPERTOOLTIPCMPS, "UPDATE_SUPERTOOLTIPCMPS" },

	/* 刷新超级tooltipCMPS */
	{ GCD_HIDE_TOOLTIPCMPS, "HIDE_TOOLTIPCMPS" },
	{ GCD_OPEN_DELQUESTITEM, "OPEN_DELMISSIONITEM" },

	/* 删除任务道具 */

	/* 天赋相关 */
	{ GCD_OPEN_SELFGIFT, "OPEN_SELFGIFT", },
	{ GCD_CLOSE_SELFGIFT, "CLOSE_SELFGIFT", },

	/* 天赋修行相关 */
	{ GCD_GUILD_SKILL_GUILD_LEVEL_UP, "GUILD_SKILL_GUILD_LEVEL_UP", },	
	{ GCD_GUILD_SKILL_GUILD_EXP, "GUILD_SKILL_GUILD_EXP", },	
	{ GCD_GUILD_SKILL_GUILD_MONEY, "GUILD_SKILL_GUILD_MONEY", },	
	{ GCD_GUILD_SKILL_CHAR_INHERENCE_LEVEL, "GUILD_SKILL_CHAR_INHERENCE_LEVEL", },
	{ GCD_GUILD_SKILL_CHAR_MONEY, "GUILD_SKILL_CHAR_MONEY", },	
	{ GCD_GUILD_SKILL_CHAR_BANGGONG, "GUILD_SKILL_CHAR_BANGGONG", },
	{ GCD_GUILD_SKILL_CHAR_SHENGWANG, "GUILD_SKILL_CHAR_SHENGWANG", },
	{ GCD_GUILD_SKILL_CHAR_WEIWANG, "GUILD_SKILL_CHAR_WEIWANG", },
	{ GCD_GUILD_SKILL_CHAR_ITEM, "GUILD_SKILL_CHAR_ITEM", },
};

sCommandData	g_GlobalCommand2[] =
{
	{ GCD_OPEN_EXERCISESCOUT, "OPEN_EXERCISESCOUT" },

	/* 打开每日提示活动追踪 */
	{ GCD_CLOSE_EXERCISESCOUT, "CLOSE_EXERCISESCOUT" },

	/* 关闭每追踪日提示活动 */
	{ GCD_UPDATE_EXERCISESCOUT, "UPDATE_EXERCISESCOUT" },

	/* 更新每日提示活动追踪 */
	{ GCD_OPEN_DISMANTLE_EQUIP_FRAME, "OPEN_DISMANTLE_EQUIP_FRAME" },

	/* 拆解确认 */
	{ GCD_OPEN_BIND_EQUIP_FRAME, "OPEN_BIND_EQUIP_FRAME" },

	/* 绑定确认 */
	{ GCD_UNIT_Updata_BangGong, "UNIT_Updata_BangGong" },
	{ GCD_UNIT_Updata_ShengWang, "UNIT_Updata_ShengWang" },
	{ GCD_OPEN_ACTIVE_SHOP_ITEM_FRAME, "OPEN_ACTIVE_SHOP_ITEM_FRAME" },

	/* CZG */
	{ GCD_ASK_KING_BATTLE, "ASK_KING_BATTLE" },
	{ GCD_DAMAGE_TIP, "DAMAGE_TIP" },

	/* 伤害提示 */
	{ GCD_ADVANCED_ROSE, "ADVANCED_ROSE" },

	/*
	 * 高级玫瑰花特效(QL) ;
	 * 
	 */
	{ GCD_OPEN_CHECKOUT,		"OPEN_CHECKOUT"		},		// 登录答题
	{ GCD_OPEN_SCENE_ANSWER,	"OPEN_SCENE_ANSWER" },		// 场景内活动答题
	{ GCD_SET_CHECKOUT,			"SET_CHECKOUT"		},
	{ GCD_REFURBISH_CHECKOUT,	"REFURBISH_CHECKOUT"},

	{ GCD_CAPTCHA_OPEN,			"CAPTCHA_OPEN"		 },		// 
	{ GCD_CAPTCHA_TIME_EVENT,	"CAPTCHA_TIME_EVENT" },
	
	{ GCD_OPEN_HELP, "OPEN_HELP" },
	{ GCD_OPEN_GUILD_BATTLE_STATISTIC, "OPEN_GUILD_BATTLE_STATISTIC" },

	/* 打开帮战统计界面 */
	{ GCD_CLOSE_GUILD_BATTLE_STATISTIC, "CLOSE_GUILD_BATTLE_STATISTIC" },

	/* 关闭帮战统计界面 */
	{ GCD_UPDATE_GUILD_BATTLE_STATISTIC, "UPDATE_GUILD_BATTLE_STATISTIC" },

	/* 更新帮战统计界面 */
	{ GCD_OPEN_GOLD_BUTTON, "OPEN_GOLD_BUTTON" },

	/* 打开现金商店按钮 */
	{ GCD_CLOSE_GOLD_BUTTON, "CLOSE_GOLD_BUTTON" },

	/* 关闭现金商店按钮 */
	{ GCD_ENABLE_IB_SHOP_BUTTON, "ENABLE_IB_SHOP_BUTTON" },

	/* 置现金商店按铵有效 */
	{ GCD_ENABLE_IB_SHOP_BUTTON_ANI, "ENABLE_IB_SHOP_BUTTON_ANI", },

	/* 置现金商店按铵动画效果有效 */
	{ GCD_RIDE_EXTENT_SHORTCUT, "RIDE_EXTENT_SHORTCUT" },

	/* 更新帮战统计界面 */
	{ GCD_MIDDLE_BOTTOM_SCROLL_MESSAGE, "MIDDLE_BOTTOM_SCROLL_MESSAGE" },
	{ GCD_MIDDLE_BOTTOM_TEXT_MESSAGE, "MIDDLE_BOTTOM_TEXT_MESSAGE" },
	{ GCD_MIDDLE_ANIM_MESSAGE, "MIDDLE_ANIM_MESSAGE" },
	{ GCD_LOCKKEYBOARD_INPUT, "LOCKKEYBOARD_INPUT" },
	{ GCD_GUARD_INFO, "GUARD_INFO" },
	{ GCD_GUARDER_CHANGED, "GUARDER_CHANGED" },
	{ GCD_RICH_SAFE_GUARD_CLEAR, "RICH_SAFE_GUARD_CLEAR" },

	/* 保护范围界面清理 */
	{ GCD_LEVEL_UP, "LEVEL_UP" },
	{ GCD_POS_CARED_EVENT, "POS_CARED_EVENT" },
	{ GCD_MOREKEY_VIEW_RESET, "MOREKEY_VIEW_RESET" },

	/* 重置扩展快捷栏图标 */
	{ GCD_CHAR_RENAME, "CHAR_RENAME" },
	{ GCD_UPDATE_RENAME_FLAG, "UPDATE_RENAME_FLAG" },
	{ GCD_START_OPEN_BOX_STATE, "START_OPEN_BOX_STATE" },
	{ GCD_ASK_COUNTRY_BATTLE_LITE, "ASK_COUNTRY_BATTLE_LITE" },
	{ GCD_ASK_COUNTRY_BATTLE_LITE_KINGISSUE, "ASK_COUNTRY_BATTLE_LITE_KINGISSUE" },
	{ GCD_ASK_WORLDCUP_JOIN, "ASK_WORLDCUP_JOIN" },
	{ GCD_UPDATE_SHORTCUT_KEY, "UPDATE_SHORTCUT_KEY" },

	/* 现金寄售相关 */
	{ GCD_OPEN_WORLD_IB_SHOP_SELL, "OPEN_WORLD_IB_SHOP_SELL" },

	/* 打开寄售界面 */
	{ GCD_CLOSE_WORLD_IB_SHOP_SELL, "CLOSE_WORLD_IB_SHOP_SELL" },

	/* 关闭寄售界面 */
	{ GCD_OPEN_WORLD_IB_SHOP_BUY, "OPEN_WORLD_IB_SHOP_BUY" },

	/* 打开购买界面 */
	{ GCD_OPEN_GOLD_SALE_MESSAGE, "OPEN_GOLD_SALE_MESSAGE" },

	/* 打开寄售确认对话框 */
	{ GCD_LOCKITEM, "LOCKITEM" },

	/* 加锁对话框 */
	{ GCD_UNLOCKITEM, "UNLOCKITEM" },

	/* 解锁锁对话框 */
	{ GCD_TIRED_SCENE_INFO, "TIRED_SCENE_INFO" },

	/* 疲劳场景提示信息 */
	{ GCD_OPEN_STALL_BUY_CONFIRM, "OPEN_STALL_BUY_CONFIRM" },

	/* 摆摊购买确认 */
	{ GCD_OPEN_SUPERTOOLTIPABILITY, "OPEN_SUPERTOOLTIPABILITY" },

	/* 打开提示 */
	{ GCD_CLOSE_SUPERTOOLTIPABILITY, "CLOSE_SUPERTOOLTIPABILITY" },

	/* 关闭提示 */
	{ GCD_UNIT_UPDATA_GOODBADVALUE, "UNIT_UPDATA_GOODBADVALUE" },

	/* 刷新善恶值 */
	{ GCD_LOCKED_SHORTCUT, "LOCKED_SHORTCUT" },
	{ GCD_OPEN_DESTROY_TASK_ITEM, "OPEN_DESTROY_TASK_ITEM" },
	{ GCD_UPDATA_DESTROY_TASK_ITEM, "UPDATA_DESTROY_TASK_ITEM" },
	{ GCD_DESTROY_TASK_ITEM, "DESTROY_TASK_ITEM" },

	/* 删除任务道具 */
	{ GCD_DIALOG_SHOW, "DIALOG_SHOW" },
	{ GCD_DIALOG_UPDATE, "DIALOG_UPDATE" },
	{ GCD_DIALOG_SEND, "DIALOG_SEND" },
	{ GCD_DIALOG_OPEN_HISTORY, "DIALOG_OPEN_HISTORY" },
	{ GCD_DIALOG_ITEM_LINK, "DIALOG_ITEM_LINK" },
	{ GCD_DIALOG_QUEST_LINK, "DIALOG_MISSION_LINK" },
	{ GCD_DIALOG_HORSE_LINK, "DIALOG_HORSE_LINK" },
	{ GCD_DIALOG_SKILL_LINK, "DIALOG_SKILL_LINK" },
	{ GCD_OPEN_EQUIP_COLOR_CHANGE, "OPEN_EQUIP_COLOR_CHANGE" },
	{ GCD_UPDATE_EQUIP_COLOR_CHANGE, "UPDATE_EQUIP_COLOR_CHANGE" },
	{ GCD_OPEN_EQUIP_PURPLE_REWORK, "OPEN_EQUIP_PURPLE_REWORK" },
	{ GCD_UPDATE_EQUIP_PURPLE_REWORK, "UPDATE_EQUIP_PURPLE_REWORK" },
	{ GCD_UPDATE_EQUIP_COLOR_CHANGE_RESULT, "UPDATE_EQUIP_COLOR_CHANGE_RESULT" },
	{ GCD_UPDATE_EQUIP_PURPLE_REWORK_RESULT, "UPDATE_EQUIP_PURPLE_REWORK_RESULT" },
	{ GCD_DUEL_INVITE, "DUEL_INVITE" },
	
	{ GCD_SHOW_SUPERTOOLTIP_ACTIVATION, "SHOW_SUPERTOOLTIP_ACTIVATION" },
	{ GCD_TOGLE_AUTO_USE_DRUG, "TOGLE_AUTO_USE_DRUG" },
	{ GCD_UPDATE_AUTO_USE_DRUG, "UPDATE_AUTO_USE_DRUG" },
	{ GCD_OPEN_PAY_MESSAGEBOX, "OPEN_PAY_MESSAGEBOX" },
	{ GCD_UNIT_UPDATA_PVP2V2MARK, "UNIT_UPDATA_PVP2V2MARK" },
	{ GCD_OPEN_GEM_LEVELUP, "OPEN_GEM_LEVELUP" },
	{ GCD_UPDATE_GEM_LEVELUP, "UPDATE_GEM_LEVELUP" },
	{ GCD_GEM_LEVELUP_RESULT, "GEM_LEVELUP_RESULT" },
	{ GCD_OPEN_GEM_SYN, "OPEN_GEM_SYN" },
	{ GCD_UPDATE_GEM_SYN, "UPDATE_GEM_SYN" },
	{ GCD_GEM_SYN_RESULT, "GEM_SYN_RESULT" },
	{ GCD_OPEN_GEM_UNINST, "OPEN_GEM_UNINST" },
	{ GCD_GEM_UNINST_RESULT, "GEM_UNINST_RESULT" },
	{ GCD_OPEN_EQUIP_COPY, "OPEN_EQUIP_COPY" },
	{ GCD_UPDATE_EQUIP_COPY, "UPDATE_EQUIP_COPY" },
	{ GCD_EQUIP_COPY_RESULT, "EQUIP_COPY_RESULT" },
	{ GCD_IBSHOP_OPEN, "IBSHOP_OPEN" },

	/* 将商店的物品搬动到背包 */
	{GCD_DRAG_SHOP_ITEM_TO_BAG, "DRAG_SHOP_ITEM_TO_BAG" },

	{ GCD_OPEN_EQUIP_COPY_OTHER, "OPEN_EQUIP_COPY_OTHER" },

	/* 打开金币商店 */
	{ GCD_IBSHOP_CLOSE, "IBSHOP_CLOSE" },

	/* 关闭金币商店 */
	{ GCD_IBSHOP_UPDATE, "IBSHOP_UPDATE" },

	/* 更新金币商店 */
	//装备复制确认
	{ GCD_OEQUIP_COPY_FRAME, "OEQUIP_COPY_FRAME"} ,

	/*学习9级技能确认*/
	{ GCD_STUDY_SKILL_MSG , "STUDY_SKILL_MSG" }, 

	{ GCD_ASK_IF_REGISTER_MIBAOKA , "ASK_IF_REGISTER_MIBAOKA" }, 
	{ GCD_EQUIP_WANFA_FRAME,		"EQUIP_WANFA_FRAME" },
	{ GCD_EQUIP_WANFA_FRAME_OK,		"EQUIP_WANFA_FRAME_OK" },
	{ GCD_OPEN_EQUIP_RECALL,		"OPEN_EQUIP_RECALL" },
	{ GCD_EQUIP_RECALL_RESULT,		"EQUIP_RECALL_RESULT"},
	{ GCD_UPDATE_EQUIP_RECALL,		"UPDATE_EQUIP_RECALL" },
	{ GCD_OPEN_ITEM_RECALL,			"OPEN_ITEM_RECALL" },
	{ GCD_UPDATE_ITEM_RECALL,		"UPDATE_ITEM_RECALL" },
	{ GCD_TEAMMEMBER_CALL_UP,		"TEAMMEMBER_CALL_UP" },
	{ GCD_TRANSPOS_UPDATE,			"TRANSPOS_UPDATE" },

	{ GCD_SHOW_EQUIP_CHANGE_EFFECT,	"SHOW_EQUIP_CHANGE_EFFECT" },
    { GCD_SHOW_TOP_MESSAGEBOX,	    "SHOW_TOP_MESSAGEBOX" },
    { GCD_EXIT_TIMER_UPDATE,	    "EXIT_TIMER_UPDATE" },

	/* 打开股票界面 */
	{ GCD_OPEN_STOCK_FRAME, "OPEN_STOCK_FRAME" },

	/* 更新大盘信息 */
	{ GCD_UPDATE_STOCK_TOP_LIST, "UPDATE_STOCK_TOP_LIST" },

	/* 更新股票账户余额 */
	{ GCD_UPDATE_ACC_MONEY, "UPDATE_ACC_MONEY" },

	/* 更新股票交易历史记录 */
	{ GCD_UPDATE_STOCK_RECPRD, "UPDATE_STOCK_RECPRD" },

	/* 更新股票上架列表 */
	{ GCD_UPDATE_STOCK_MARKET, "UPDATE_STOCK_MARKET" },

	//打开股票交易确认框
	{ GCD_OPEN_STOCK_BUY_SURE_FRAME, "OPEN_STOCK_BUY_SURE_FRAME" },

	//新手UI界面提示
	{ GCD_NEW_PLAYER_UI_TIPS, "NEW_PLAYER_UI_TIPS" },

	//打开一级提醒框
	{ GCD_OPEN_1LEVEL_REMIND_FRAME, "OPEN_1LEVEL_REMIND_FRAME"},

	/*传送符定位确认*/
	{GCD_TRANSPOS_SET_FRAME,		"TRANSPOS_SET_FRAME"},
	//蓝属性吸收
	{GCD_OPEN_BULL_IN,				"OPEN_BULL_IN"},
	{GCD_UPDATE_BULL_IN,			"UPDATE_BULL_IN"},
	{GCD_BULL_IN_RESULT,			"BULL_IN_RESULT"},
	//蓝属性附加
	{GCD_OPEN_BULL_ADD,				"OPEN_BULL_ADD"},
	{GCD_UPDATE_BULL_ADD,			"UPDATE_BULL_ADD"},
	{GCD_BULL_ADD_RESULT,			"BULL_ADD_RESULT"},

	// 密保设置
	{GCD_UPDATE_LOGIN_SAFE_INFO,	"UPDATE_LOGIN_SAFE_INFO"},
	{GCD_TOGLE_SAFE_SET,			"TOGLE_SAFE_SET"},
	{GCD_SHOW_SAFE_DETAIL_INFO,		"SHOW_SAFE_DETAIL_INFO"},

	// 打开领奖对话框
	{GCD_OPEN_AWARD_FRAME,		"OPEN_AWARD_FRAME"},
	
	// 打开打造装备对话框
	{GCD_OPEN_EQUIPPRODUCE,	 "OPEN_EQUIPPRODUCE"},	
	// 关闭打造装备对话框
	{GCD_CLOSE_EQUIPPRODUCE, "CLOSE_EQUIPPRODUCE"},	

	// 返回登陆界面
	{GCD_RETURN_SELECT_ROLE, "RETURN_SELECT_ROLE"},

	// 打开转化装备界面
	{GCD_OPEN_EQUIPSWITCH, "OPEN_EQUIPSWITCH"},
	{GCD_UPDATE_EQUIPSWITCH, "UPDATE_EQUIPSWITCH"},
	{GCD_CLOSE_EQUIPSWITCH, "CLOSE_EQUIPSWITCH"},

	//蓝属性强化界面
	{ GCD_OPEN_BLUE_INTENSIFY, "OPEN_BLUE_INTENSIFY", },
	{ GCD_UPDATE_BLUE_INTENSIFY, "UPDATE_BLUE_INTENSIFY", },
	{ GCD_UPDATE_BLUE_INTENSIFY_ATTR, "UPDATE_BLUE_INTENSIFY_ATTR", },
	{ GCD_CLOSE_BLUE_INTENSIFY, "CLOSE_BLUE_INTENSIFY", },

	//蓝属性还原界面
	{ GCD_OPEN_BLUE_RESET, "OPEN_BLUE_RESET", },
	{ GCD_UPDATE_BLUE_RESET, "UPDATE_BLUE_RESET", },
	{ GCD_UPDATE_BLUE_RESET_ATTR, "UPDATE_BLUE_RESET_ATTR", },
	{ GCD_CLOSE_BLUE_RESET, "CLOSE_BLUE_RESET", },

	//更新帮会据点信息
	{GCD_UPDATE_GUILD_LAIRD_INFO,"UPDATE_GUILD_LAIRD_INFO"},
	

	// 打开职业转换界面
    { GCD_OPEN_PROFESSION_SWITCH_UI, "OPEN_PROFESSION_SWITCH_UI" },
    { GCD_ADD_PROFESSION_SWITCH_ITEM, "ADD_PROFESSION_SWITCH_ITEM" },

	{ GCD_KING_ZHAOJI , "KING_ZHAOJI" }, 
	// 摆摊物品购买确认
	{ GCD_STALL_ITEM_BUY,		"STALL_ITEM_BUY" },
	{ GCD_IB_STALL_ITEM_BUY,	"IB_STALL_ITEM_BUY" },

	{ GCD_STALL_PET_BUY,		"STALL_PET_BUY" },
	{ GCD_IB_STALL_PET_BUY,		"IB_STALL_PET_BUY" },

	{ GCD_SHOW_LOAD_BACKDROP,	"SHOW_LOAD_BACKDROP" },
	{ GCD_UPDATE_LOAD_PROGRESS, "UPDATE_LOAD_PROGRESS" },

	// 战场地图
	{ GCD_UPDATE_BATTLE_MAP, "UPDATE_BATTLE_MAP" },
	{ GCD_MENTAL_GAME_BUY_ITEM,"MENTAL_GAME_BUY_ITEM"},

	{ GCD_CAPSLOCK_KEYDOWN,		"CAPSLOCK_KEYDOWN"},

	{ GCD_UNIT_MOVE_MOVE,		"UNIT_MOVE_MOVE"},

    { GCD_COUNTRY_PRECONTRACT_OPEN, "COUNTRY_PRECONTRACT_OPEN"},

	{ GCD_GAMELOGIN_OPEN_VIEW_SETUP, "GAMELOGIN_OPEN_VIEW_SETUP"},
	{ GCD_GAMELOGIN_CLOSE_VIEW_SETUP, "GAMELOGIN_CLOSE_VIEW_SETUP"},

	{ GCD_OPEN_WORLD_DIRECTORY, "OPEN_WORLD_DIRECTORY"},
	{ GCD_UPDATE_WORLD_DIRECTORY, "UPDATE_WORLD_DIRECTORY"},

	//更换形象
	{ GCD_OPEN_CHANGE_APPEARANCE, "OPEN_CHANGE_APPEARANCE"},	
	{ GCD_UPDATE_CHAR_CHANGE_APPEARACE_RESULT, "UPDATE_CHAR_CHANGE_APPEARACE_RESULT"},

	//打开NPC商店
	{ GCD_TO_OPEN_SHOP, "TO_OPEN_SHOP" },

	{ GCD_CLOSE_SCENE_TRANS, "CLOSE_SCENE_TRANS" },

	// 个人天赋界面
	{ GCD_OPEN_SELF_GIFT, "OPEN_SELF_GIFT" },
	{ GCD_UPDATE_SELF_GIFT, "UPDATE_SELF_GIFT" },
	
	// 帮会天赋界面
	{ GCD_OPEN_GUILD_GIFT, "OPEN_GUILD_GIFT" },
	{ GCD_UPDATE_GUILD_GIFT, "UPDATE_GUILD_GIFT" },

	// 护身符补色
	{ GCD_OPEN_BLUE_SYN, "OPEN_BLUE_SYN" },
	{ GCD_UPDATE_BLUE_SYN, "UPDATE_BLUE_SYN" },
	{ GCD_CLOSE_BLUE_SYN, "CLOSE_BLUE_SYN" },
	{ GCD_BLUE_SYN_RESULT, "BLUE_SYN_RESULT" },

	{ GCD_GAMELOGIN_ENTER_SUCCEED, "GAMELOGIN_ENTER_SUCCEED" },

	{ GCD_TO_OPEN_QINGJIAN, "TO_OPEN_QINGJIAN" },	// 增加朝廷请柬与江湖请柬的互斥与互斥提示

	{ GCD_OPEN_BALANCE_GIFT,	"OPEN_BALANCE_GIFT" },
	{ GCD_UPDATE_BALANCE_GIFT,	"UPDATE_BALANCE_GIFT" },

	// 橙装打造
	{ GCD_OPEN_NEW_EQUIPPRODUCE,"OPEN_NEW_EQUIPPRODUCE"},
	{ GCD_UPDATE_NEW_EQUIPPRODUCE,"UPDATE_NEW_EQUIPPRODUCE"},
	{ GCD_CLOSE_NEW_EQUIPPRODUCE,"CLOSE_NEW_EQUIPPRODUCE"},
	{ GCD_NEW_EQUIPPRODUCE_RESULT,"NEW_EQUIPPRODUCE_RESULT"},

	// 星座铭刻
	{ GCD_OPEN_EQUIP_CONST_BIND,"OPEN_EQUIP_CONST_BIND"},
	{ GCD_UPDATE_EQUIP_CONST_BIND,"UPDATE_EQUIP_CONST_BIND"},
	{ GCD_UPDATE_EQUIP_CONST_BIND_RESULT,"UPDATE_EQUIP_CONST_BIND_RESULT"},

    { GCD_OPEN_INH_ATTACK,"OPEN_INH_ATTACK" },
    { GCD_OPEN_INH_DEFEND,"OPEN_INH_DEFEND" },

    { GCD_UPDATE_INH_ATTACK,"UPDATE_INH_ATTACK" },
    { GCD_UPDATE_INH_DEFEND,"UPDATE_INH_DEFEND" },
    { GCD_INH_ATTACK_RESET, "INH_ATTACK_RESET" },
    { GCD_INH_ATTACK_CONFIRM, "INH_ATTACK_CONFIRM" },
	{ GCD_GUILD_SEND_MAIL, "GUILD_SEND_MAIL" },

	{ GCD_OPEN_XINNIAN, "OPEN_XINNIAN" },
	
	{ GCD_AGREE_COUNTRY_COLLEAGUE_YES_NO_TO_ACQUIRE, "AGREE_COUNTRY_COLLEAGUE_YES_NO_TO_ACQUIRE", },
	{ GCD_AGREE_COUNTRY_COLLEAGUE_YES_NO, "AGREE_COUNTRY_COLLEAGUE_YES_NO", },
    

	{ GCD_OPEN_GUILD_BUSSKILL_STUDY, "OPEN_GUILD_BUSSKILL_STUDY"},
	{ GCD_UPDATE_GUILD_BUSKILL, "UPDATE_GUILD_BUSSKILL"},
	{ GCD_UPDATE_GUILD_BUSSKILL_TOOLBAR, "UPDATE_GUILD_BUSSKILL_TOOLBAR"},

    { GCD_DAILIAN_CONFIRM, "DAILIAN_CONFIRM" }, 
    { GCD_WUTING_MANAGEMENT, "WUTING_MANAGEMENT" }, 
    { GCD_WUTING_PRECONTRACT, "WUTING_PRECONTRACT" }, 
};
template<>
CGameCommandSystem * Singleton<CGameCommandSystem>::msSingleton = NULL;

/*
 =======================================================================================================================
 =======================================================================================================================
 */

CGameCommandSystem *CGameCommandSystem::GetSingletonPtr(void)
{
	return msSingleton;
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
CGameCommandSystem &CGameCommandSystem::GetSingleton(void)
{
	KLAssert(msSingleton);
	return(*msSingleton);
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
CGameCommandSystem::CGameCommandSystem()
{
	m_dwLastTickCount = 0;
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
CGameCommandSystem::~CGameCommandSystem()
{
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
KHAN_RETURN_RESULT CGameCommandSystem::Initialize(void)
{
	KYLIN_TRY int32 nCharCommandNum = sizeof(g_CharCommand) / sizeof(sCommandData);

	for(int32 i = 0; i < nCharCommandNum; ++i)
	{
		/* 生成名称检索表 */
		m_CommandMap_Name[g_CharCommand[i].szCommand] = &(g_CharCommand[i]);

		/* 生成id检索表 */
		m_CommandMap_ID[g_CharCommand[i].idCommand] = &(g_CharCommand[i]);
	}

	int32 nGameCommandNum = sizeof(g_GameCommand) / sizeof(sCommandData);

	for(int32 i = 0; i < nGameCommandNum; i++)
	{
		/* 生成名称检索表 */
		m_CommandMap_Name[g_GameCommand[i].szCommand] = &(g_GameCommand[i]);

		/* 生成id检索表 */
		m_CommandMap_ID[g_GameCommand[i].idCommand] = &(g_GameCommand[i]);
	}

	int32 nCommandNum1 = sizeof(g_GlobalCommand1) / sizeof(sCommandData);
	int32 nCommandNum2 = sizeof(g_GlobalCommand2) / sizeof(sCommandData);

	for(int32 i = 0; i < nCommandNum1; i++)
	{
		/* 生成名称检索表 */
		m_CommandMap_Name[g_GlobalCommand1[i].szCommand] = &(g_GlobalCommand1[i]);

		/* 生成id检索表 */
		m_CommandMap_ID[g_GlobalCommand1[i].idCommand] = &(g_GlobalCommand1[i]);
	}

	for(int32 i = 0; i < nCommandNum2; i++)
	{
		/* 生成名称检索表 */
		m_CommandMap_Name[g_GlobalCommand2[i].szCommand] = &(g_GlobalCommand2[i]);

		/* 生成id检索表 */
		m_CommandMap_ID[g_GlobalCommand2[i].idCommand] = &(g_GlobalCommand2[i]);
	}

	KYLIN_CATCH("10006") return KRR_SUCCEED;
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
void CGameCommandSystem::Release(void)
{
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
KHAN_RETURN_RESULT CGameCommandSystem::Update(void)
{
	return KRR_SUCCEED;
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
void CGameCommandSystem::_AddCommand(const sCommand &command)
{
	if (GCD_SUPERTOOLTIP == command.m_pCommandData->idCommand)
	{
		int kk = 0;
	}
	if(!command.m_pCommandData) return;

	/* 如果是慢速处理的事件 */
	if(command.m_pCommandData->bDelayProcess)
		m_CommandDelayList.push_back(command);
	else
		m_CommandList.push_back(command);
}

/*
 =======================================================================================================================
    注册事件处理函数
 =======================================================================================================================
 */
void CGameCommandSystem::CommandHandleRegister(const STRING &strCommand, HANDLE_COMMAND_FUNC funHandle, uint32 uOwnerData)
{
	if(NULL == funHandle) return;

	sCommandData	*pCommand = m_CommandMap_Name[strCommand];

	if(!pCommand) return;

	pCommand->FuncNotifyList.push_back(std::make_pair(funHandle, uOwnerData));

	if (strCommand == "GAMELOGIN_OPEN_COUNT_INPUT")
	{
		::OutputDebugString("GAMELOGIN_OPEN_COUNT_INPUT\n");
	}
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
void CGameCommandSystem::ProcessAllCommand(void)
{
	/* 处理慢速队列 */
	if(!(m_CommandDelayList.empty()))
	{
		const uint32 WORK_STEP = 2;
		uint32 nTickCountNow = GAME_TIME_PTR->GetTickCount();
		uint32 nTickCountStep = GAME_TIME_PTR->CalSubTime(m_dwLastTickCount, nTickCountNow);

		if(nTickCountStep >= WORK_STEP)
		{
			m_dwLastTickCount = nTickCountNow;

			const sCommand	&command = *(m_CommandDelayList.begin());

			_ProcessCommand(command);

			m_CommandDelayList.erase(m_CommandDelayList.begin());
		}
	}

	for(auto it = m_CommandList.begin(); it != m_CommandList.end(); it++)
	{
		const sCommand	&command = *it;

		/* 检测是否有同样的Event已经被处理 */
		bool bMultiPushed = false;

		for(auto itPrev = m_CommandList.begin(); itPrev != it; itPrev++)
		{
			if(*itPrev == *it)
			{
				bMultiPushed = true;
				break;
			}
		}

		if(bMultiPushed && (*it).m_pCommandData->idCommand != GCD_PERSONAL_MESSAGE) continue;

		_ProcessCommand(command);
	}

	m_CommandList.clear();
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
void CGameCommandSystem::_ProcessCommand(const sCommand &command)
{
	/* 查找事件定义 */
	sCommandData	*pCommandData = command.m_pCommandData;

	if(!pCommandData) return;

	/* 调用处理函数 */
	if(!(pCommandData->FuncNotifyList.empty()))
	{
		std::list<std::pair<HANDLE_COMMAND_FUNC, uint32> >::iterator	iter = pCommandData->FuncNotifyList.begin();

		for(; iter != pCommandData->FuncNotifyList.end(); iter++)
		{
			if((*iter).first) ((*iter).first) (&command, (*iter).second);

			//temp
//			GAME_DEBUG_PTR->DebugLog( "Command: %d, %s", pCommandData->idCommand, pCommandData->szCommand );
		}
	}
}

/*
 =======================================================================================================================
    立即处理的事件
 =======================================================================================================================
 */
void CGameCommandSystem::ProcessDirectCommand(GAME_COMMAND_ID id)
{
	/* 是否有效的 */
	if(m_CommandMap_ID.find(id) == m_CommandMap_ID.end()) return;

	sCommand command;

	command.m_pCommandData = m_CommandMap_ID[id];

	/* ] */
	_ProcessCommand(command);
}

/*
 =======================================================================================================================
 =======================================================================================================================
 */
void CGameCommandSystem::ClearAllCommand(void)
{
	/* 慢速队列 */
	if(!m_CommandDelayList.empty())
	{
		m_CommandDelayList.clear();
	}

	if(!m_CommandList.empty())
	{
		m_CommandList.clear();
	}
}
