
#ifndef __GAMEDEFINE_ITEM_H__
#define __GAMEDEFINE_ITEM_H__

enum PLAYER_EQUIP
{
	HEQUIP_MAINHAND = 0,
	HEQUIP_ASSIHAND = 1,
	HEQUIP_HEAD	= 2,
	HEQUIP_NECK	= 3,
	HEQUIP_SHOULDER = 4,
	HEQUIP_BACK	= 5,
	HEQUIP_WRIST	= 6,
	HEQUIP_HAND	= 7,
	HEQUIP_WAIST	= 8,
	HEQUIP_FEET	= 9,
	HEQUIP_RING1	= 10,
	HEQUIP_RING2	= 11,
	HEQUIP_ADORN1	= 12,
	HEQUIP_ADORN2	= 13,
	HEQUIP_SUIT	= 14,
	HEQUIP_SIGN	= 15,
	HEQUIP_SPECAIL	= 16,
	HEQUIP_AMULET	= 17,//护身符
	HEQUIP_NUMBER,
};

enum EQUIP_UPDATE
{
	UPDATE_MAINHAND		= 0,
	UPDATE_ASSIHAND		= 1,
	UPDATE_HEAD		= 2,
	UPDATE_NECK		= 3,
	UPDATE_SHOULDER		= 4,
	UPDATE_BACK		= 5,
	UPDATE_WRIST		= 6,
	UPDATE_HAND		= 7,
	UPDATE_WAIST		= 8,
	UPDATE_FEET		= 9,
	UPDATE_RING1		= 10,
	UPDATE_RING2		= 11,
	UPDATE_ADORN1		= 12,
	UPDATE_ADORN2		= 13,
	UPDATE_SUIT		= 14,
	UPDATE_SIGN		= 15,
	UPDATE_GEM		= 16,
	UPDATE_SOUL		= 17,
	UPDATE_SETSUIT		= 18,
	UPDATE_LEVEL		= 19,
	UPDATE_EQUIPNUMBER,
};

enum HORSE_EQUIP
{
	HEQUIP_HORSE_FACE	= 0,
	HEQUIP_HORSE_BODY,
	HEQUIP_HORSE_NECK,
	HEQUIP_HORSE_BACK,
	HEQUIP_HORSE_HALTER,
	HEQUIP_HORSE_BOOT,
	HEQUIP_HORSE_NUMBER,
};

enum ITEM_PROPERTY  //物品属性
{
	IPROPERTY_POINT_STR,
	IPROPERTY_RATE_STR,
	IPROPERTY_POINT_DEX,
	IPROPERTY_RATE_DEX,
	IPROPERTY_POINT_INT,
	IPROPERTY_RATE_INT,
	IPROPERTY_POINT_CON,
	IPROPERTY_RATE_CON,
	IPROPERTY_POINT_ALL_BASEATT,
	IPROPERTY_RATE_ALL_BASEATT,
	IPROPERTY_POINT_ATTACK_M,
	IPROPERTY_RATE_ATTACK_M,
	IPROPERTY_POINT_ATTACK_NEAR,
	IPROPERTY_RATE_ATTACK_NEAR,
	IPROPERTY_POINT_ATTACK_FAR,
	IPROPERTY_RATE_ATTACK_FAR,
	IPROPERTY_POINT_DEFENCE_M,
	IPROPERTY_RATE_DEFENCE_M,
	IPROPERTY_POINT_DEFENCE_NEAR,
	IPROPERTY_RATE_DEFENCE_NEAR,
	IPROPERTY_POINT_DEFENCE_FAR,
	IPROPERTY_RATE_DEFENCE_FAR,
	IPROPERTY_POINT_MAXHP,
	IPROPERTY_RATE_MAXHP,
	IPROPERTY_POINT_MAXMP,
	IPROPERTY_RATE_MAXMP,
	IPROPERTY_WUSHI_MAXRAGE,
	IPROPERTY_JIANXIA_MAXRAGE,
	IPROPERTY_QISHE_MAXRAGE,
	IPROPERTY_HUOQIANG_MAXRAGE,
	IPROPERTY_XIANZHI_MAXRAGE,
	IPROPERTY_SAMAN_MAXRAGE,
	IPROPERTY_RATE_WUSHI_MAXRAGE,
	IPROPERTY_RATE_JIANXIA_MAXRAGE,
	IPROPERTY_RATE_QISHE_MAXRAGE,
	IPROPERTY_RATE_HUOQIANG_MAXRAGE,
	IPROPERTY_RATE_XIANZHI_MAXRAGE,
	IPROPERTY_RATE_SAMAN_MAXRAGE,
	IPROPERTY_POINT_WUSHI_RAGE_RESTORE,
	IPROPERTY_POINT_JIANXIA_RAGE_RESTORE,
	IPROPERTY_POINT_QISHE_RAGE_RESTORE,
	IPROPERTY_POINT_HUOQIANG_RAGE_RESTORE,
	IPROPERTY_POINT_XIANZHI_RAGE_RESTORE,
	IPROPERTY_POINT_SAMAN_RAGE_RESTORE,
	IPROPERTY_RATE_WUSHI_RAGE_RESTORE,
	IPROPERTY_RATE_JIANXIA_RAGE_RESTORE,
	IPROPERTY_RATE_QISHE_RAGE_RESTORE,
	IPROPERTY_RATE_HUOQIANG_RAGE_RESTORE,
	IPROPERTY_RATE_XIANZHI_RAGE_RESTORE,
	IPROPERTY_RATE_SAMAN_RAGE_RESTORE,
	IPROPERTY_HIT,
	IPROPERTY_MISS,
	IPROPERTY_RATE_HIT,
	IPROPERTY_CRIT,
	IPROPERTY_TOUGHNESS,
	IPROPERTY_RATE_CRIT,
	IPROPERTY_COLD_ATTACK,
	IPROPERTY_RATE_COLD_ATTACK,
	IPROPERTY_FIRE_ATTACK,
	IPROPERTY_RATE_FIRE_ATTACK,
	IPROPERTY_LIGHT_ATTACK,
	IPROPERTY_RATE_LIGHT_ATTACK,
	IPROPERTY_POISON_ATTACK,
	IPROPERTY_RATE_POISON_ATTACK,
	IPROPERTY_COLD_RESIST,
	IPROPERTY_RATE_COLD_RESIST,
	IPROPERTY_FIRE_RESIST,
	IPROPERTY_RATE_FIRE_RESIST,
	IPROPERTY_LIGHT_RESIST,
	IPROPERTY_RATE_LIGHT_RESIST,
	IPROPERTY_POISON_RESIST,
	IPROPERTY_RATE_POISON_RESIST,
	IPROPERTY_RESIST_ALL,
	IPROPERTY_RATE_RESIST_ALL,
	IPROPERTY_RATE_DREAD,
	IPROPERTY_TIME_DREAD,
	IPROPERTY_RATE_COMA,
	IPROPERTY_TIME_COMA,
	IPROPERTY_RATE_HUSH,
	IPROPERTY_TIME_HUSH,
	IPROPERTY_RATE_UNARM,
	IPROPERTY_TIME_UNARM,
	IPROPERTY_ROLL_RESIST,
	IPROPERTY_RATE_ATTACK_SPEED,
	IPROPERTY_RATE_SKILL_SPEED,
	IPROPERTY_RATE_MOVE_REDUCE,
	IPROPERTY_HURT_DOT,
	IPROPERTY_DEBUFF_RESIST,
	IPROPERTY_SPEED_MOVE,
	IPROPERTY_SPEED_SKILL,
	IPROPERTY_ATTACK_SPEED,
	IPROPERTY_MODEL,
	IPROPERTY_COLOR_HAIR,
	IPROPERTY_MODEL_HAIR,
	IPROPERTY_HP_RESTORE,
	IPROPERTY_MP_RESTORE,
	IPROPERTY_RAGE_RESTORE,
	IPROPERTY_CRIT_HURT,
	IPROPERTY_SHIELD_ALL,
	IPROPERTY_SHIELD_NEAR,
	IPROPERTY_SHIELD_M,
	IPROPERTY_SHIELD_FAR,
	IPROPERTY_SHIELD_COLD,
	IPROPERTY_SHIELD_FIRE,
	IPROPERTY_SHIELD_LIGHT,
	IPROPERTY_SHIELD_POISON,
	IPROPERTY_SHIELD_MP_REDUCE,
	IPROPERTY_SKILL_LEVEL_INC,
	IPROPERTY_ALLSKILL_LEVEL_INC,
	IPROPERTY_WUSHI_HURT_RESIST,
	IPROPERTY_JIANXIA_HURT_RESIST,
	IPROPERTY_QISHE_HURT_RESIST,
	IPROPERTY_HUOQIANG_HURT_RESIST,
	IPROPERTY_XIANZHI_HURT_RESIST,
	IPROPERTY_SAMAN_HURT_RESIST,
	IPROPERTY_EXPRENCE_GET,
	IPROPERTY_MONEY_GET,
	IPROPERTY_POINT_ABILITY1,
	IPROPERTY_RATE_ABILITY1,
	IPROPERTY_POINT_ABILITY2,
	IPROPERTY_RATE_ABILITY2,
	IPROPERTY_POINT_ABILITY3,
	IPROPERTY_RATE_ABILITY3,
	IPROPERTY_POINT_ABILITY4,
	IPROPERTY_RATE_ABILITY4,
	IPROPERTY_POINT_ABILITY5,
	IPROPERTY_RATE_ABILITY5,
	IPROPERTY_POINT_ABILITY6,
	IPROPERTY_RATE_ABILITY6,
	IPROPERTY_POINT_ABILITY7,
	IPROPERTY_RATE_ABILITY7,
	IPROPERTY_POINT_ABILITY8,
	IPROPERTY_RATE_ABILITY8,
	IPROPERTY_POINT_ABILITY9,
	IPROPERTY_RATE_ABILITY9,
	IPROPERTY_POINT_ABILITY10,
	IPROPERTY_RATE_ABILITY10,
	IPROPERTY_BASE_RATE_ATTACK_ENEAR,
	IPROPERTY_BASE_RATE_ATTACK_FAR,
	IPROPERTY_BASE_RATE_ATTACK_M,
	IPROPERTY_BASE_RATE_DEFENCE_ENEAR,
	IPROPERTY_BASE_RATE_DEFENCE_FAR,
	IPROPERTY_BASE_RATE_DEFENCE_M,
	IPROPERTY_BASE_ATTACK_NEAR,
	IPROPERTY_BASE_ATTACK_FAR,
	IPROPERTY_BASE_ATTACK_M,
	IPROPERTY_BASE_DEFENCE_NEAR,
	IPROPERTY_BASE_DEFENCE_FAR,
	IPROPERTY_BASE_DEFENCE_M,
	IPROPERTY_RATE_NEARATT_REDUCE,
	IPROPERTY_RATE_FARATT_REDUCE,
	IPROPERTY_RATE_MATT_REDUCE,
	IPROPERTY_RATE_COLDATT_REDUCE,
	IPROPERTY_RATE_FIREATT_REDUCE,
	IPROPERTY_RATE_LIGHTATT_REDUCE,
	IPROPERTY_RATE_POISON_REDUCE,
	IPROPERTY_RATE_DREAD_RESIST,
	IPROPERTY_RATE_COMA_RESIST,
	IPROPERTY_RATE_HUSH_RESIST,
	IPROPERTY_RATE_UNARM_RESIST,
	IPROPERTY_RATE_ATTACKSPEED_RESIST,
	IPROPERTY_RATE_SKILLSPEED_RESIST,
	IPROPERTY_RATE_MOVEREDUCE_RESIST,
	IPROPERTY_RATE_ATT_REDUCE,
	IPROPERTY_POINT_MAX_VIGOR,
	IPROPERTY_RATE_VIGOR_REGENERATE,
	IPROPERTY_POINT_ABILITYEXP,
	IPROPERTY_POINT_STR_PURPLE,
	IPROPERTY_POINT_DEX_PURPLE,
	IPROPERTY_POINT_INT_PURPLE,
	IPROPERTY_POINT_CON_PURPLE,
	IPROPERTY_POINT_ATTACK_M_PURPLE,
	IPROPERTY_POINT_ATTACK_NEAR_PURPLE,
	IPROPERTY_POINT_ATTACK_FAR_PURPLE,
	IPROPERTY_POINT_DEFENCE_M_PURPLE,
	IPROPERTY_POINT_DEFENCE_NEAR_PURPLE,
	IPROPERTY_POINT_DEFENCE_FAR_PURPLE,
	IPROPERTY_POINT_MAXHP_PURPLE,
	IPROPERTY_HIT_PURPLE,
	IPROPERTY_MISS_PURPLE,
	IPROPERTY_CRIT_PURPLE,
	IPROPERTY_TOUGHNESS_PURPLE,
	IPROPERTY_CRIT_HURT_PURPLE,
	IPROPERTY_WUSHI_MAXRAGE_PURPLE,
	IPROPERTY_JIANXIA_MAXRAGE_PURPLE,
	IPROPERTY_QISHE_MAXRAGE_PURPLE,
	IPROPERTY_HUOQIANG_MAXRAGE_PURPLE,
	IPROPERTY_XIANZHI_MAXRAGE_PURPLE,
	IPROPERTY_SAMAN_MAXRAGE_PURPLE,
	IPROPERTY_SPEED_MOVE_PURPLE,
	IPROPERTY_ID_IMPACT			= 200,
	IPROPERTY_PROPERTY_IGNORE_NEAR_IMMUNITY,
	IPROPERTY_PROPERTY_IGNORE_FAR_IMMUNITY,
	IPROPERTY_PROPERTY_IGNORE_MAGIC_IMMUNITY,
	IPROPERTY_PROPERTY_NEAR_HIT_FOR_CONTROL_SPELL,
	IPROPERTY_PROPERTY_FAR_HIT_FOR_CONTROL_SPELL,
	IPROPERTY_PROPERTY_MAGIC_HIT_FOR_CONTROL_SPELL,
	IPROPERTY_PROPERTY_NEAR_MISS_FOR_CONTROL_SPELL,
	IPROPERTY_PROPERTY_FAR_MISS_FOR_CONTROL_SPELL,
	IPROPERTY_PROPERTY_MAGIC_MISS_FOR_CONTROL_SPELL,
	IPROPERTY_PROPERTY_ZOOM_SCALE,
	IPROPERTY_SHIZIJUN_HURT_RESIST,				/* 抵抗十字军职业伤害 */
	IPROPERTY_SHENGHUOSHI_HURT_RESIST,			/* 抵抗圣火使职业伤害 */
	IPROPERTY_CIKE_HURT_RESIST,					/* 抵抗刺客职业伤害 */
	IPROPERTY_JINWEIJUN_HURT_RESIST,			/* 抵抗近卫军职业伤害 */
	IPROPERTY_YINXIUSHI_HURT_RESIST,			/* 抵抗隐修士职业伤害 */
	IPROPERTY_LAMA_HURT_RESIST,					/* 抵抗僧侣职业伤害 */
	IPROPERTY_REFLECT_HURT,						/*反射伤害*/
	IPROPERTY_SUCK_BLOOD,						/*吸血*/
	IPROPERTY_REDUCE_EQUIP_LEVEL,				/*装备等级降低*/
	IPROPERTY_RATE_REDUCE_ATTACK_SPEED_5S,		/*几率触发减攻击速度5秒*/
	IPROPERTY_RATE_REDUCE_MOVE_SPEED_2S,		/*几率触发减移动速度2秒*/
	IPROPERTY_RATE_DOUBLE_ATTACK,				/*几率触发攻击双倍*/
	IPROPERTY_RATE_BLACKOUT_1S,					/*几率触发眩晕1秒*/
	IPROPERTY_RATE_IGNORE_DEFENCE,				/*几率触发忽视防御*/
	IPROPERTY_WUSHI_HURT_INCREASE,				/* 增强对武士伤害 */
	IPROPERTY_JIANXIA_HURT_INCREASE,			/* 增强对剑侠伤害 */
	IPROPERTY_QISHE_HURT_INCREASE,				/* 增强对骑射手伤害 */
	IPROPERTY_HUOQIANG_HURT_INCREASE,			/* 增强对火枪手伤害 */
	IPROPERTY_XIANZHI_HURT_INCREASE,			/* 增强对先知伤害 */
	IPROPERTY_SAMAN_HURT_INCREASE,				/* 增强对萨满伤害 */
	IPROPERTY_SHIZIJUN_HURT_INCREASE,			/* 增强对十字军伤害 */
	IPROPERTY_SHENGHUOSHI_HURT_INCREASE,		/* 增强对圣火使伤害 */
	IPROPERTY_CIKE_HURT_INCREASE,				/* 增强对刺客伤害 */
	IPROPERTY_JINWEIJUN_HURT_INCREASE,			/* 增强对近卫军伤害 */
	IPROPERTY_YINXIUSHI_HURT_INCREASE,			/* 增强对隐修士伤害 */
	IPROPERTY_LAMA_HURT_INCREASE,				/* 增强对僧侣伤害 */
	IPROPERTY_HIT_BALANCE,						/*命中平衡*/
	IPROPERTY_TOUGHNESS_BALANCE,				/*韧性平衡*/
	IPROPERTY_MISS_BALANCE,						/*闪避平衡*/
	IPROPERTY_CRIT_BALANCE,						/*暴击平衡*/
	IPROPERTY_CRIT_HURT_BALANCE,				/*暴击伤害平衡*/
	IPROPERTY_CRIT_REDUCE_BALANCE,				/*暴击减免平衡*/
	IPROPERTY_HIT_CONTROL_BALANCE,				/*控制命中平衡*/
	IPROPERTY_RESIST_CONTROL_BALANCE,			/*控制抵抗平衡*/								
	IPROPERTY_NUMBER,
};
			
enum eITEM_PROPERTY_TYPE
{
	IPROPERTY_TYPE_INVAILD = -1,
	IPROPERTY_TYPE_ALL,
	IPROPERTY_TYPE_BASE,
	IPROPERTY_TYPE_NOT_BACE,
	IPROPERTY_TYPE_NUMBER,
};

enum EQUIP_PAI
{
	EQUIPPAI_ANY				= 1,
	EQUIPPAI_ANYFENG			= 2,
	EQUIPPAI_ANYJIAN			= 3,
	EQUIPPAI_ANYZI				= 4,
	EQUIPPAI_ANYFEIZI			= 5,
	EQUIPPAI_ANYTIAO			= 6,
	EQUIPPAI_ANYTONG			= 7,
	EQUIPPAI_ANYWAN				= 8,
	EQUIPPAI_ANYSHUN			= 9,
	EQUIPPAI_ANYKE				= 10,
	EQUIPPAI_ANYJIANG			= 11,
	EQUIPPAI_ANYJIAN_ANYFEIZI	= 12,
	EQUIPPAI_ANYJIAN_RESERVE_1	= 13,//任意牌型名称保留
	EQUIPPAI_ANY_END			= 14,//最后一个任意牌型
	EQUIPPAI_DONG				= 15,
	EQUIPPAI_NAN				= 16,
	EQUIPPAI_XI				= 17,
	EQUIPPAI_BEI				= 18,
	EQUIPPAI_ZHONG				= 19,
	EQUIPPAI_FA				= 20,
	EQUIPPAI_BAI				= 21,
	EQUIPPAI_1TIAO				= 31,
	EQUIPPAI_2TIAO				= 32,
	EQUIPPAI_3TIAO				= 33,
	EQUIPPAI_4TIAO				= 34,
	EQUIPPAI_5TIAO				= 35,
	EQUIPPAI_6TIAO				= 36,
	EQUIPPAI_7TIAO				= 37,
	EQUIPPAI_8TIAO				= 38,
	EQUIPPAI_9TIAO				= 39,
	EQUIPPAI_1TONG				= 41,
	EQUIPPAI_2TONG				= 42,
	EQUIPPAI_3TONG				= 43,
	EQUIPPAI_4TONG				= 44,
	EQUIPPAI_5TONG				= 45,
	EQUIPPAI_6TONG				= 46,
	EQUIPPAI_7TONG				= 47,
	EQUIPPAI_8TONG				= 48,
	EQUIPPAI_9TONG				= 49,
	EQUIPPAI_1WAN				= 51,
	EQUIPPAI_2WAN				= 52,
	EQUIPPAI_3WAN				= 53,
	EQUIPPAI_4WAN				= 54,
	EQUIPPAI_5WAN				= 55,
	EQUIPPAI_6WAN				= 56,
	EQUIPPAI_7WAN				= 57,
	EQUIPPAI_8WAN				= 58,
	EQUIPPAI_9WAN				= 59,
	EQUIP_PAI_NUM,
};

enum EQUIP_CHAIN_INFO
{
	EQUIPCHAIN_ANYSHUN			= 9,
	EQUIPCHAIN_ANYKE			= 10,
	EQUIPCHAIN_ANYJIANG			= 11,
	EQUIPCHAIN_ANYTISHUN			= 12,
	EQUIPCHAIN_ANYTOSHUN			= 13,
	EQUIPCHAIN_ANYWSHUN			= 14,
	EQUIPCHAIN_ANYTIAOKE			= 15,
	EQUIPCHAIN_ANYTONGKE			= 16,
	EQUIPCHAIN_ANYWANKE			= 17,
	EQUIPCHAIN_ANYTIJIANG			= 18,
	EQUIPCHAIN_ANYTOJANG			= 19,
	EQUIPCHAIN_ANYWJIANG			= 20,
	EQUIPCHAIN_ZHONGJIANG			= 90,
	EQUIPCHAIN_FAJIANG				= 91,
	EQUIPCHAIN_BAIJIANG				= 92,
	EQUIPCHAIN_FIVETIJIANG			= 93,
	EQUIPCHAIN_FIVETOJIANG			= 94,
	EQUIPCHAIN_FIVEWJIANG			= 95,
	EQUIPCHAIN_ANYJJIANG			= 96,
	EQUIPCHAIN_ANYFJIANG			= 97,
	EQUIPCHAIN_ANYJIANKE			= 98,
	EQUIPCHAIN_ANYFENGKE			= 99,
	EQUIPCHAIN_TIAO123			= 100,
	EQUIPCHAIN_TIAO456			= 101,
	EQUIPCHAIN_TIAO789			= 102,
	EQUIPCHAIN_TONG123			= 103,
	EQUIPCHAIN_TONG456			= 104,
	EQUIPCHAIN_TONG789			= 105,
	EQUIPCHAIN_WAN123			= 106,
	EQUIPCHAIN_WAN456			= 107,
	EQUIPCHAIN_WAN789			= 108,
	EQUIPCHAIN_DONGKE			= 109,
	EQUIPCHAIN_NANKE			= 110,
	EQUIPCHAIN_XIKE				= 111,
	EQUIPCHAIN_BEIKE			= 112,
	EQUIPCHAIN_ZHONGKE			= 113,
	EQUIPCHAIN_FAKE				= 114,
	EQUIPCHAIN_BAIKE			= 115,
	EQUIPCHAIN_2TIAOKE			= 116,
	EQUIPCHAIN_5TIAOKE			= 117,
	EQUIPCHAIN_8TIAOKE			= 118,
	EQUIPCHAIN_2TONGKE			= 119,
	EQUIPCHAIN_5TONGKE			= 120,
	EQUIPCHAIN_8TONGKE			= 121,
	EQUIPCHAIN_2WANKE			= 122,
	EQUIPCHAIN_5WANKE			= 123,
	EQUIPCHAIN_8WANKE			= 124,
	EQUIPCHAIN_2TIAOJIANG			= 125,
	EQUIPCHAIN_2TONGJIANG			= 126,
	EQUIPCHAIN_2WANJIANG			= 127,
	EQUIPCHAIN_8TIAOJIANG			= 128,
	EQUIPCHAIN_8TONGJIANG			= 129,
	EQUIPCHAIN_8WANJIANG			= 130,
};

enum INDEX_PAITYPE
{
	INDEX_ANYSHUN				= 0,
	INDEX_ANYKE				= 1,
	INDEX_ANYJIANG				= 2,
	INDEX_NOANYPAINUM			= 18,
};

enum EM_EQUIP_CARD_GROUP
{
	EM_EQUIP_CARD_GROUP_INVAILD		= -1,
	EM_EQUIP_CARD_GROUP_CHAIN1		= 0,
	EM_EQUIP_CARD_GROUP_CHAIN2,
	EM_EQUIP_CARD_GROUP_CHAIN3,
	EM_EQUIP_CARD_GROUP_CHAIN4,
	EM_EQUIP_CARD_GROUP_JIANG,
	EM_EQUIP_CARD_GROUP_MAXNUM,
};

enum eITEM_CLASS
{
	ICLASS_EQUIP				= 10,
	ICLASS_MATERIAL,
	ICLASS_COMITEM,
	ICLASS_TASKITEM,
	ICLASS_GEM,
	ICLASS_EXTRABAG				= 19,
	ICLASS_NUMBER,
};

enum ITEM_CREATE_TYPE { ITEM_IB = 0, ITEM_DROP, ITEM_TASK, ITEM_CREATE, ITEM_NUM, };

enum EQUIP_TYPE
{
	EQUIP_MDAO				= 1,	//主手刀
	EQUIP_MJIAN,					//主手剑
	EQUIP_MGONG,					//主手弓
	EQUIP_MHUOQIANG,				//主手火枪
	EQUIP_MCHUI,					//主手锤子
	EQUIP_MZHANG,					//主手杖
	EQUIP_SDUN,						//副手盾
	EQUIP_SJIAN,					//副手剑
	EQUIP_SJIANZHI,					//副手箭支
	EQUIP_SZIDAN,					//副手子弹
	EQUIP_SGU,						//副手鼓
	EQUIP_SHAOJIAO,					//副手号角
	EQUIP_CAP				= 20,	//帽子
	EQUIP_NECKLACE,					//徽章
	EQUIP_SHOULDER,					//披风
	EQUIP_ARMOR,					//衣服
	EQUIP_CUFF,						//项链
	EQUIP_HAND,						//手套
	EQUIP_SASH,						//腰带
	EQUIP_BOOT,						//鞋
	EQUIP_RING,						//戒指
	EQUIP_ADORN,					//手镯
	EQUIP_SUIT,						//时装
	EQUIP_RIDER,					//座骑
	EQUIP_SIGN,						//符文(掌门牌)

	EQUIP_RECOVER,//自动回血道具
	EQUIP_AMULET,//护身符

	EQUIP_CRUSADE_MASTER_HAND,		//十字军主手
	EQUIP_FIRE_ENVOY_MASTER_HAND,	//圣火使主手
	EQUIP_ASSASSIN_MASTER_HAND,		//刺客主手
	EQUIP_GUARDS_MASTER_HAND,		//近卫军主手
	EQUIP_FRIAR_MASTER_HAND,		//隐修士主手
	EQUIP_LAMA_MASTER_HAND,			//喇嘛主手
	EQUIP_CRUSADE_ASSIST_HAND,		//十字军副手
	EQUIP_FIRE_ENVOY_ASSIST_HAND,	//圣火使副手
	EQUIP_ASSASSIN_ASSIST_HAND,		//刺客副手
	EQUIP_GUARDS_ASSIST_HAND,		//近卫军副手
	EQUIP_FRIAR_ASSIST_HAND,		//隐修士副手
	EQUIP_LAMA_ASSIST_HAND,			//喇嘛副手

	EQUIP_TYPE_NUM,
};

enum GEM_TYPE { GEM_COLORFUL = 0, GEM_RED, GEM_GREEN, GEM_YELLOW, GEM_BLUE, GEM_TYPE_NUM, };

enum MATERIAL_TYPE { };

enum EQUIP_LEVEL_TYPE
{
	EQUIPLEVEL_TYPE0			= 0,
	EQUIPLEVEL_TYPE1,
	EQUIPLEVEL_TYPE2,
	EQUIPLEVEL_TYPE3,
	EQUIPLEVEL_TYPE4,
	EQUIPLEVEL_TYPENUM,
};

enum UPDATE_EQUIP_DATA
{
	UPDATE_EQUIP_BIND			= 1,
	UPDATE_EQUIP_PAITYPE,
	UPDATE_EQUIP_EQUIPTYPE,
	UPDATE_EQUIP_NEEDLEVEL,
	UPDATE_EQUIP_LEVEL,
	UPDATE_EQUIP_CURMAXDUR,
	UPDATE_EQUIP_CURDUR,
	UPDATE_EQUIP_CURGEMHOLE,
	UPDATE_EQUIP_SCORE,
	UPDATE_EQUIP_TERMEND,
	UPDATE_EQUIP_NUMS,
};
enum eMISC_ITEM_TYPE
{
	COMMON_ITEM_0				= 0,
	COMMON_ITEM_1,
	COMMON_ITEM_2,
	COMMON_ITEM_3,
	COMITEM_PRESCR				= 4,
	COMMON_HORSE_ITEM			= 5,
	COMITEM_WPIDENT				= 6,
	COMITEM_ARIDENT				= 7,
	COMITEM_NCIDENT				= 8,
	COMITEM_TREASUREBOX			= 9,
	COMITEM_TREASUREBOX_KEY			= 10,
	FRIENT_SEND_ITEM			= 11,
	FIND_ENEMY_ITEM				= 12,
	COMITEM_ENERGYBALL			= 24, //能量球
    COMMON_BADGE                = 25, // 徽章，用于职业转换
	COMMON_CHANGEAPPEARANCE     = 26, //整容券
	COMMON_QINGJIAN			    = 27, //朝廷请柬
	COMMON_FIND_PLAYER_ITEM		= 28, //追踪符

};

enum MATERIAL_ITEM_TYPE
{
	MATERIAL_STRENGTHEN			= 0,
	MATERIAL_CREATION_1			= 1,
	MATERIAL_CREATION_2			= 2,
	MATERIAL_CREATION_3			= 3,
	MATERIAL_CREATION_4			= 4,
	MATERIAL_CREATION_5			= 5,
	MATERIAL_VALUABLE			= 96,
	MATERIAL_MAJIANG_ITEM			= 97,
	MATERIAL_MAJIANG			= 98,
	MATERIAL_QUEST				= 99,
};

enum eUPDATE_EQIPMENT
{
	UPDATE_EQIPMENT_WEAPON_ID		= 0,
	UPDATE_EQIPMENT_CAP_ID,
	UPDATE_EQIPMENT_ARMOUR_ID,
	UPDATE_EQIPMENT_WRIST_ID,
	UPDATE_EQIPMENT_FOOT_ID,
	UPDATE_EQIPMENT_NUMBERS
};

enum OBJITEM_TYPE
{
	ITYPE_DROPBOX				= -1,
	ITYPE_GROWPOINT,
	ITYPE_MONSTERDROP_OBJ_ITEM,
	ITYPE_PERSONDROP_OBJ_ITEM,
};

enum DURSPOIL_RULER
{
	DURSPOIL_NO				= -1,
	DURSPOIL_ATTACT				= 1,
	DURSPOIL_DEFENCE			= 2,
	DURSPOIL_NUMBER,
};

enum ePICK_RULER_TYPE { IPR_FREE_PICK, IPR_BET_PICK, IPR_TURN_PICK, };

enum eBOX_DISTRIBUTE_RULER
{
	BDR_COMMON				= 0,
	BDR_BOSS				= 1,
	BDR_BLUE				= 2,
	BDR_GOLD				= 3,
	BDR_UNKNOW				= 0xFFFF
};

enum eITEM_DISTRIBUTE_RULER { ITEMDR_RANDOM, ITEMDR_ALLGET };

enum eITEM_CONTAINER_TYPE
{
	ICT_UNKNOW_CONTAINER,
	ICT_BASE_CONTAINER,
	ICT_BAG_CONTAINER,
	ICT_BASEBAG_CONTAINER,
	ICT_EXTRABAG_CONTAINER,
	ICT_EXTRA_CONTAINER,
	ICT_TASK_CONTAINER,
	ICT_MAT_CONTAINER,
	ICT_EQUIP_CONTAINER,
	ICT_BANK_CONTAINER,
	ICT_ITEMBOX_CONTAINER,
	ICT_EXCHANGEBOX_CONTAINER,
	ICT_HUMAN_PET_CONTAINER,
	ICT_HUMAN_BANKPET_CONTAINER,
};

enum eITEM_TARGET_TYPE
{
	ITEM_TARGET_TYPE_INVALID		= -1,
	ITEM_TARGET_TYPE_NONE,
	ITEM_TARGET_TYPE_POS,
	ITEM_TARGET_TYPE_DIR,
	ITEM_TARGET_TYPE_ITEM,
	ITEM_TARGET_TYPE_SELF,
	ITEM_TARGET_TYPE_SELF_PET,
	ITEM_TARGET_TYPE_FRIEND,
	ITEM_TARGET_TYPE_FRIEND_PLAYER,
	ITEM_TARGET_TYPE_FRIEND_MONSTER,
	ITEM_TARGET_TYPE_FRIEND_PET,
	ITEM_TARGET_TYPE_ENEMY,
	ITEM_TARGET_TYPE_ENEMY_PLAYER,
	ITEM_TARGET_TYPE_ENEMY_MONSTER,
	ITEM_TARGET_TYPE_ENEMY_PET,
	ITEM_TARGET_TYPE_ALL_CHARACTER,
	ITEM_TARGET_TYPE_NUMBERS
};

#define ITEM_PET_SKILL_STUDY_BEGIN	30402000
#define ITEM_PET_SKILL_STUDY_END	30403000

#define ITEM_PET_RETURN_BABAY_BEGIN	30503011
#define ITEM_PET_RETURN_BABAY_END	30503020

#define ITEM_DOME_MEDICINE		30601000
#define ITEM_MEAT_MEDICINE		30602000
#define ITEM_GRASS_MEDICINE		30603000
#define ITEM_WORM_MEDICINE		30604000
#define ITEM_PADDY_MEDICINE		30605000

#define ITEM_PET_FEED_MEDICINE_MAX	ITEM_PADDY_MEDICINE + 1000

#define ITEM_PET_ADD_LIFE_BEGIN		ITEM_PET_FEED_MEDICINE_MAX
#define ITEM_PET_ADD_LIFE_END		30607000

enum eITEM_EXT_INFO
{
	IEI_PBIND_INFO				= 0x00000001,//普通绑定
	IEI_GBIND_INFO				= 0x00000002,//现金绑定
	IEI_PLOCK_INFO				= 0x00000004,
	IEI_BLUE_ATTR				= 0x00000008,
	IEL_CREATOR				= 0x00000010,
};

enum BIND_TYPE
{
	BIND_NONE				= 0,
	BIND_NORMAL				= 1,	//普通绑定
	BIND_GOLD				= 2,	//现金绑定
	BIND_INVALID,
};

enum EQUIP_OPTYPE
{
	EQUIPOP_USE				= 0,
	EQUIPOP_UNEQUIP,
	EQUIPOP_LEVELUP,
	EQUIPOP_ADDHOLE,
	EQUIPOP_USEGEM,
	EQUIPOP_KEZI,
	EQUIPOP_CHANGEPAI,
	EQUIPOP_EXCHANGEPAI,
	EQUIPOP_DECOMPOUND,
	EQUIPOP_REMOULD,
	EQUIPOP_COLORCHANGE,
	EQUIPOP_PURPLEREWORK,
	EQUIPOP_BLUEINTENSIFY,	//蓝属性强化
	EQUIPOP_BLUEREWORK,		//洗蓝属性，蓝属性重置
	EQUIPOP_NUM,
};

enum PACKUP_TYPE { PACKUP_BAG = 0, PACKUP_BANK, PACKUP_INVALID, };

enum EQUIP_ACTIVATION_TYPE { EQUIP_AT_LEVELUP = 0, EQUIP_AT_IMPRINT, EQUIP_AT_CONST1,EQUIP_AT_CONST2};

enum EQUIP_COLOR_TYPE { EQUIP_CT_WHITE = 1, EQUIP_CT_GREEN, EQUIP_CT_BLUE, EQUIP_CT_YELLOW, EQUIP_CT_PURPLE, EQUIP_CT_ORANGE};

#define EQUIP_ACTIVATION_ATT_NUM	(2)

enum EQUIP_WANFA_TYPE
{
	EQUIP_WANFA_TYPE_COLORCHANGE= 1,	//黄装升紫装
	EQUIP_WANFA_TYPE_PURPLEREWORK,		//紫装洗属性
	EQUIP_WANFA_TYPE_GEMREWORK,			//宝石升级
	EQUIP_WANFA_TYPE_GEMSYN,			//宝石合成
	EQUIP_WANFA_TYPE_GEMUNINST,			//宝石拆卸
	EQUIP_WANFA_TYPE_REPEAT,			//装备复制
	EQUIP_WANFA_TYPE_RECALL,			//装备回收
	EQUIP_WANFA_TYPE_SUBMIT,			//帮会跑环提交蓝装物品(提交当前UI选择的物品)
	EQUIP_WANFA_TYPE_BLUEIN,			//蓝属性吸收
	EQUIP_WANFA_TYPE_BLUEADD,			//蓝属性附加
	EQUIP_WANFA_TYPE_ADDHOLE,			//装备打孔
	EQUIP_WANFA_TYPE_USEGEM,			//装备镶嵌
	EQUIP_WANFA_TYPE_LEVELUP,			//装备打星
	EQUIP_WANFA_TYPE_BIND,				//装备绑定/铭刻
	EQUIP_WANFA_TYPE_CHANGE_PAI_TYPE,	//麻将铭刻（装备增加麻将）
	EQUIP_WANFA_TYPE_EX_CHANGE_PAI_TYPE,//装备换牌
	EQUIP_WANFA_TYPE_REMOULD,			//装备改造
	EQUIP_WANFA_TYPE_DECOMPOUND,		//装备分解
	EQUIP_WANFA_TYPE_CREATE,			//装备打造、合成
	EQUIP_WANFA_TYPE_BLUE_INTENSIFY,	//装备蓝属性强化
	EQUIP_WANFA_TYPE_BLUE_RESET,		//装备蓝属性重置
	EQUIP_WANFA_TYPE_SWITCH,			//装备转化
	EQUIP_WANFA_TYPE_RECALLITEM,		//多彩宝石回收
	EQUIP_WANFA_TYPE_BLUE_SYN,			//蓝属性合成，即护身符布色
	EQUIP_WANFA_TYPE_NEW_EQUIP_PRODUCE, //橙装打造,随机蓝属性
	EQUIP_WANFA_TYPE_CONST_BIND,		//星座铭刻
	EQUIP_WANFA_TYPE_HONOR_BIND,		//荣誉铭刻
};

enum ITEM_USE_TYPE { ITEM_USED_BY_MORMAL = 0, ITEM_USED_BY_SPECAIL_EQUIP, };

enum MAJIANG_SPECIAL_SOUL { MAJIANG_PIHU =0, MAJIANG_QING, };

enum EQUIP_CONST_ATTR_TYPE {BASE_TYPE =0,ACTIVE_TYPE,CONST_ATTR_TYPE_NUMBER,};
#define TRANSITEM_COMMONCOUNTRY 4
#define TRANS_ITEM_SCRIPT 430014
#define BLUE_ADD_MAX_ENCHASE	6 //蓝属性附加最大的附加数量
#define BLUE_INTENSIFY_MAX_ENCHASE	11 //蓝属性强化最大的附加数量
#define EQUIP_ADD_HOLE_MIN_LEVEL  1   //装备打孔需要的最小级别
//#define EQUIP_BIND_MIN_STARTLEVEL 7    //装备灵魂铭刻需要的最小星级 取消星级判断
#define EQUIP_BIND_MIN_LEVEL 40    //装备灵魂铭刻需要的最小级别
#define EQUIP_COLORCHANGE_MIN_LEVEL  60   //装备鎏金需要的最小级别
//#define EQUIP_CHANGE_CARD_MIN_LEVEL  60   //装备麻雀铭刻需要的最小级别 todo取消
#define EQUIP_BLUE_INTENSIFY_MIN_HOLE  3   //蓝属性强化需要的最小孔数
#define EQUIP_BLUE_INTENSIFY_MIN_LEVEL  80   //蓝属性强化需要的最小孔数最级别

#endif
