/*$T Common/DefineResult.cpp GC 1.140 10/10/07 10:06:29 */


/*$6
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 */


#include "stdafx.h"
#include "TypeDefine.h"
#include <map>
#include "DefineResult.h"

struct SResultText
{
	eOPTRESULT	nCode;
	const char		*pszText;
};

static SResultText	s_aResultText[] =
{
	{ OR_OK, "OR_OK" },
	{ OR_ERROR, "OR_ERROR" },
	{ OR_DIE, "OR_DIE" },
	{ OR_INVALID_SKILL, "OR_INVALID_SKILL" },
	{ OR_TARGET_DIE, "OR_TARGET_DIE" },
	{ OR_LACK_MANA, "OR_LACK_MANA" },
	{ OR_COOL_DOWNING, "OR_COOL_DOWNING" },
	{ OR_NO_TARGET, "OR_NO_TARGET" },
	{ OR_INVALID_TARGET, "OR_INVALID_TARGET" },
	{ OR_OUT_RANGE, "OR_OUT_RANGE" },
	{ OR_IN_RANGE, "OR_IN_RANGE" },
	{ OR_NO_PLATFORM, "OR_NO_PLATFORM" },
	{ OR_OUT_PLATFORM, "OR_OUT_PLATFORM" },
	{ OR_NO_TOOL, "OR_NO_TOOL" },
	{ OR_STUFF_LACK, "OR_STUFF_LACK" },
	{ OR_BAG_OUT_OF_SPACE, "OR_BAG_OUT_OF_SPACE" },
	{ OR_WARNING, "OR_WARNING" },
	{ OR_BUSY, "OR_BUSY" },
	{ OR_QUEST_HAVE, "OR_QUEST_HAVE" },
	{ OR_QUEST_LIST_FULL, "OR_QUEST_LIST_FULL" },
	{ OR_QUEST_NOT_FIND, "OR_QUEST_NOT_FIND" },
	{ OR_EXP_LACK, "OR_EXP_LACK" },
	{ OR_CHAR_DO_NOT_KNOW_THIS_SKILL, "OR_CHAR_DO_NOT_KNOW_THIS_SKILL" },
	{ OR_NO_SCRIPT, "OR_NO_SCRIPT" },
	{ OR_NOT_ENOUGH_HP, "OR_NOT_ENOUGH_HP" },
	{ OR_NOT_ENOUGH_RAGE, "OR_NOT_ENOUGH_RAGE" },
	{ OR_NOT_ENOUGH_STRIKE_POINT, "OR_NOT_ENOUGH_STRIKE_POINT" },
	{ OR_NOT_ENOUGH_ITEM, "OR_NOT_ENOUGH_ITEM" },
	{ OR_NOT_ENOUGH_VIGOR, "OR_NOT_ENOUGH_VIGOR" },
	{ OR_NO_LEVEL, "OR_NO_LEVEL" },
	{ OR_CANNOT_UPGRADE, "OR_CANNOT_UPGRADE" },
	{ OR_FAILURE, "OR_FAILURE" },
	{ OR_GEM_CONFLICT, "OR_GEM_CONFLICT" },
	{ OR_NEED_IN_FURY_STANCE, "OR_NEED_IN_FURY_STANCE" },
	{ OR_INVALID_TARGET_POS, "OR_INVALID_TARGET_POS" },
	{ OR_GEM_SLOT_LACK, "OR_GEM_SLOT_LACK" },
	{ OR_LIMIT_MOVE, "OR_LIMIT_MOVE" },
	{ OR_LIMIT_USE_SKILL, "OR_LIMIT_USE_SKILL" },
	{ OR_INACTIVE_SKILL, "OR_INACTIVE_SKILL" },
	{ OR_TOO_MUCH_HP, "OR_TOO_MUCH_HP" },
	{ OR_NEED_A_WEAPON, "OR_NEED_A_WEAPON" },
	{ OR_NEED_HIGH_LEVEL_TALENT, "OR_NEED_HIGH_LEVEL_TALENT" },
	{ OR_NEED_LEARN_SKILL_FIRST, "OR_NEED_LEARN_SKILL_FIRST" },
	{ OR_NEED_PROFESSION_FOR_LEVELUP, "OR_NEED_PROFESSION_FOR_LEVELUP" },
	{ OR_U_CANNT_DO_THIS_RIGHT_NOW, "OR_U_CANNT_DO_THIS_RIGHT_NOW" },
	{ OR_ROBOT_TIMEOUT, "OR_ROBOT_TIMEOUT" },
	{ OR_NEED_HAPPINESS_60, "OR_NEED_HAPPINESS_60" },
	{ OR_NEED_HIGH_LEVEL, "OR_NEED_HIGH_LEVEL" },
	{ OR_CANNOT_GETEXP, "OR_CANNOT_GETEXP" },
	{ OR_NEED_LIFE, "OR_NEED_LIFE" },
	{ OR_EXP_FULL, "OR_EXP_FULL" },
	{ OR_TOO_MANY_TRAPS, "OR_TOO_MANY_TRAPS" },
	{ OR_PET_PLACARD_ISSUE_FAILED, "OR_PET_PLACARD_ISSUE_FAILED" },
	{ OR_PET_PLACARD_NOT_APPOINT_PET, "OR_PET_PLACARD_NOT_APPOINT_PET" },
	{ OR_PET_PLACARD_ONLY_CAN_ISSUE_ONE, "OR_PET_PLACARD_ONLY_CAN_ISSUE_ONE" },
	{ OR_PET_PLACARD_NEED_PET_TYPE, "OR_PET_PLACARD_NEED_PET_TYPE" },
	{ OR_PET_PLACARD_NEED_PET_LEVEL, "OR_PET_PLACARD_NEED_PET_LEVEL" },
	{ OR_PET_PLACARD_NEED_PET_HAPPINESS, "OR_PET_PLACARD_NEED_PET_HAPPINESS" },
	{ OR_PET_PLACARD_NEED_PET_LIFE, "OR_PET_PLACARD_NEED_PET_LIFE" },
	{ OR_NEED_IN_STEALTH_MODE, "OR_NEED_IN_STEALTH_MODE" },
	{ OR_NOT_ENOUGH_ENERGY, "OR_NOT_ENOUGH_ENERGY" },
	{ OR_NEED_IN_SHIELD_MODE, "OR_NEED_IN_SHIELD_MODE" },
	{ OR_PET_DIE, "OR_PET_DIE" },
	{ OR_PET_HADRECALL_NEEDHAPPINESS, "OR_PET_HADRECALL_NEEDHAPPINESS" },
	{ OR_PET_HADRECALL_NEEDLIFE, "OR_PET_HADRECALL_NEEDLIFE" },
	{ OR_CAN_NOT_MOVE_STALL_OPEN, "OR_CAN_NOT_MOVE_STALL_OPEN" },
	{ OR_GEM_NOT_FIT_EQUIP, "OR_GEM_NOT_FIT_EQUIP" },
	{ OR_CANNOT_ASK_PETDETIAL, "OR_CANNOT_ASK_PETDETIAL" },
	{ OR_VARIANCEPET_CANNOT_RETURNTOCHILD, "OR_VARIANCEPET_CANNOT_RETURNTOCHILD" },
	{ OR_IMPASSABLE_ZONE, "OR_IMPASSABLE_ZONE" },
	{ OR_NEED_SETMINORPASSWORD, "OR_NEED_SETMINORPASSWORD" },
	{ OR_NEED_UNLOCKMINORPASSWORD, "OR_NEED_UNLOCKMINORPASSWORD" },
	{ OR_PETINEXCHANGE_CANNOT_GOFIGHT, "OR_PETINEXCHANGE_CANNOT_GOFIGHT" },
	{ OR_HASSPOUSE_CANNOT_RETURNTOCHILD, "OR_HASSPOUSE_CANNOT_RETURNTOCHILD" },
	{ OR_CAN_NOT_FIND_SPECIFIC_ITEM, "OR_CAN_NOT_FIND_SPECIFIC_ITEM" },
	{ OR_ISSUEHORSE_MUSTBE_ZHANMA, "OR_ISSUEHORSE_MUSTBE_ZHANMA" },
	{ OR_ISSUEHORSE_MUSTNOT_HAVEMATE, "OR_ISSUEHORSE_MUSTNOT_HAVEMATE" },
	{ OR_ISSUEHORSE_HAVE_ONLYONE, "OR_ISSUEHORSE_HAVE_ONLYONE" },
	{ OR_ISSUEHORSE_NOTENOUGH_LEVEL, "OR_ISSUEHORSE_NOTENOUGH_LEVEL" },
	{ OR_ISSUEHORSE_NOTENOUGH_HAPPINESS, "OR_ISSUEHORSE_NOTENOUGH_HAPPINESS" },
	{ OR_ISSUEHORSE_NOTENOUGH_MONEY, "OR_ISSUEHORSE_NOTENOUGH_MONEY" },
	{ OR_ISSUEHORSE_SUCC, "OR_ISSUEHORSE_SUCC" },
	{ OR_ISSUEHORSE_FAIL, "OR_ISSUEHORSE_FAIL" },
	{ OR_CANCELHORSEFINDMATE_SUCC, "OR_CANCELHORSEFINDMATE_SUCC" },
	{ OR_CANCELHORSEFINDMATE_FAIL, "OR_CANCELHORSEFINDMATE_FAIL" },
	{ OR_THIS_PLAYER_IS_OFFLINE, "OR_THIS_PLAYER_IS_OFFLINE" },
	{ OR_DOUBLEMOODACT_REFUSED, "OR_DOUBLEMOODACT_REFUSED" },
	{ OR_CALLUP_HORSE_CAN_NOT_FREE, "OR_CALLUP_HORSE_CAN_NOT_FREE" },
	{ OR_HORSE_HAPPINESS_ENOUGH, "OR_HORSE_HAPPINESS_ENOUGH" },
	{ OR_NOT_ENOUGH_MONEY, "OR_NOT_ENOUGH_MONEY" },
	{ OR_HORSE_CALLUP_CAN_NOT_CHECKUP, "OR_HORSE_CALLUP_CAN_NOT_CHECKUP" },
	{ OR_HORSE_CHECKUP_NEED_10LEVEL, "OR_HORSE_CHECKUP_NEED_10LEVEL" },
	{ OR_MOUNT_MOUNTING, "OR_MOUNT_MOUNTING" },
	{ OR_MOUNT_EXCHANGE, "OR_MOUNT_EXCHANGE" },
	{ OR_MOUNT_STALL, "OR_MOUNT_STALL" },
	{ OR_MOUNT_MATING, "OR_MOUNT_MATING" },
	{ OR_MOUNT_FRIEND, "OR_MOUNT_FRIEND" },
	{ OR_HORSE_FULL, "OR_HORSE_FULL" },
	{ OR_BEEN_FORBIDCHAT, "OR_BEEN_FORBIDCHAT" },
	{ OR_ENJAIL_BUSY, "OR_ENJAIL_BUSY" },
	{ OR_FORBIDCHAT_BUSY, "OR_FORBIDCHAT_BUSY" },
	{ OR_COLLECT_BUSY, "OR_COLLECT_BUSY" },
	{ OR_MODIFYNOTICE_BUSY, "OR_MODIFYNOTICE_BUSY" },
	{ OR_NOT_ENOUGH_CONTRIBUTE, "OR_NOT_ENOUGH_CONTRIBUTE" },
	{ OR_YOU_MUSTBE_CHIEFTAIN, "OR_YOU_MUSTBE_CHIEFTAIN" },
	{ OR_APPLYKING_SUCC, "OR_APPLYKING_SUCC" },
	{ OR_YOU_ARE_THE_KING, "OR_YOU_ARE_THE_KING" },
	{ OR_YOU_MUSTBE_CHIEFTAIN_FOR_KING, "OR_YOU_MUSTBE_CHIEFTAIN_FOR_KING" },
	{ OR_GUILD_MEMBER_NOT_ENOUGH_FOR_KING, "OR_GUILD_MEMBER_NOT_ENOUGH_FOR_KING" },
	{ OR_GUILD_LEVEL_NOT_ENOUGH_FOR_KING, "OR_GUILD_LEVEL_NOT_ENOUGH_FOR_KING" },
	{ OR_GUILD_LEVEL_NOT_ENOUGH_FOR_ACTIVEMERCH, "OR_GUILD_LEVEL_NOT_ENOUGH_FOR_ACTIVEMERCH" },
	{ OR_GUILD_EXP_NOT_ENOUGH_FOR_ACTIVEMERCH, "OR_GUILD_EXP_NOT_ENOUGH_FOR_ACTIVEMERCH" },
	{ OR_GUILD_ALREADY_ACTIVEMERCH, "OR_GUILD_ALREADY_ACTIVEMERCH" },
	{ OR_BUY_AFTER_GUILD_ACTIVE, "OR_BUY_AFTER_GUILD_ACTIVE" },
	{ OR_NOT_ENOUGH_MONEY_FOR_KING, "OR_NOT_ENOUGH_MONEY_FOR_KING" },
	{ OR_CHALLENGER_IS_YOU, "OR_CHALLENGER_IS_YOU" },
	{ OR_KING_EXSIT, "OR_KING_EXSIT" },
	{ OR_APPLY_KING_DATE_WRONG, "OR_APPLY_KING_DATE_WRONG" },
	{ OR_APPLY_KING_TIME_WRONG, "OR_APPLY_KING_TIME_WRONG" },
	{ OR_DONATE_COUNTRY_SUCC, "OR_DONATE_COUNTRY_SUCC" },
	{ OR_ALREADY_BEEN_FORBIDCHAT, "OR_ALREADY_BEEN_FORBIDCHAT" },
	{ OR_ALREADY_BEEN_ENJAIL, "OR_ALREADY_BEEN_ENJAIL" },
	{ OR_CANNOT_LEAVE_HAVE_POSITION, "OR_CANNOT_LEAVE_HAVE_POSITION" },
	{ OR_MODIFY_GUILDDESC_BUSY, "OR_MODIFY_GUILDDESC_BUSY" },
	{ OR_MODIFY_GUILDTITLE_BUSY, "OR_MODIFY_GUILDTITLE_BUSY" },
	{ OR_GUILD_MOVE_MEMBER_SUCC, "OR_GUILD_MOVE_MEMBER_SUCC" },
	{ OR_DEMISE_FAILE_NO_ASSCHIEFTAIL, "OR_DEMISE_FAILE_NO_ASSCHIEFTAIL" },
	{ OR_DEMISE_FAILE_NOT_GOLDFAMILYUSER, "OR_DEMISE_FAILE_NOT_GOLDFAMILYUSER" },
	{ OR_DEMISE_FAILE_NOT_FAMILYUSER, "OR_DEMISE_FAILE_NOT_FAMILYUSER" },
	{ OR_GUILD_CANTMOVE_HAVEPOSITION, "OR_GUILD_CANTMOVE_HAVEPOSITION" },
	{ OR_RECREATE_GUILD_BUSY, "OR_RECREATE_GUILD_BUSY" },
	{ OR_REJOIN_GUILD_BUSY, "OR_REJOIN_GUILD_BUSY" },
	{ OR_GUILD_MOVE_MEMBER_FAIL, "OR_GUILD_MOVE_MEMBER_FAIL" },
	{ OR_BUSY_OPEN_BOX, "OR_BUSY_OPEN_BOX" },
	{ OR_BUSY_HITCHING, "OR_BUSY_HITCHING" },
	{ OR_CANCELKING, "OR_CANCELKING" },
	{ OR_APPOINT_QUEEN_SUC, "OR_APPOINT_QUEEN_SUC" },
	{ OR_APPOINT_KINGGUARD_SUC, "OR_APPOINT_KINGGUARD_SUC" },
	{ OR_CANCEL_QUEEN, "OR_CANCEL_QUEEN" },
	{ OR_CANCEL_KINGGUARD, "OR_CANCEL_KINGGUARD" },
	{ OR_NOT_ENOUGH_MONEY_FOR_KING, "OR_NOT_ENOUGH_MONEY_FOR_KING" },
	{ OR_NO_ENOUGH_EXP, "OR_NO_ENOUGH_EXP" },
	{ OR_MONEY_MAXLIMIT, "OR_MONEY_MAXLIMIT" },
	{ OR_BANKITEM_MAX, "OR_BANKITEM_MAX" },
	{ OR_MS_Stall, "OR_MS_Stall" },
	{ OR_MS_Fuben, "OR_MS_Fuben" },
	{ OR_MS_BattleFieldMap, "OR_MS_BattleFieldMap" },
	{ OR_MS_ArenaMap, "OR_MS_ArenaMap" },
	{ OR_MS_CityMap, "OR_MS_CityMap" },
	{ OR_MS_PrisonMap, "OR_MS_PrisonMap" },
	{ OR_MS_Die, "OR_MS_Die" },
	{ OR_MS_Bus, "OR_MS_Bus" },
	{ OR_MS_Cashbox, "OR_MS_Cashbox" },
	{ OR_MS_Exchange, "OR_MS_Exchange" },
	{ OR_MS_MentalGame, "OR_MS_MentalGame" },
	{ OR_MS_TeamFollow, "OR_MS_TeamFollow" },
	{ OR_MS_AutoPlay, "OR_MS_AutoPlay" },
	{ OR_MS_SubTrain, "OR_MS_SubTrain" },
	{ OR_MS_Prison, "OR_MS_Prison" },
	{ OR_MS_OpenBox, "OR_MS_OpenBox" },
	{ OR_MS_ProtectTime, "OR_MS_ProtectTime" },
	{ OR_MS_KeyboardMove, "OR_MS_KeyboardMove" },
	{ OR_MS_Quest_TieSan, "OR_MS_Quest_TieSan" },
	{ OR_MS_ReadyFuben, "OR_MS_ReadyFuben" },
	{ OR_MS_Quest_DuoQiBuff, "OR_MS_Quest_DuoQiBuff" },
	{ OR_MS_Quest_TongQuBuff, "OR_MS_Quest_TongQuBuff" },
	{ OR_MS_PKMode, "OR_MS_PKMode" },
	{ OR_MS_ForbidRide, "OR_MS_ForbidRide" },
	{ OR_MS_Wedding, "OR_MS_Wedding" },
	{ OR_PWD_ErrorProtect, "OR_PWD_ErrorProtect" },
	{ OR_PWD_ErrorMax, "OR_PWD_ErrorMax" },
	{ OR_MS_Enjail, "OR_MS_Enjail" },
	{ OR_MS_Award, "OR_MS_Award" },
	{ OR_MS_TransGold, "OR_MS_TransGold" },
	{ OR_SUPER_PW_ERROR, "OR_SUPER_PW_ERROR" },
	{ OR_ISRULER_IRL_BANK, "OR_ISRULER_IRL_BANK" },
	{ OR_ISRULER_IRL_EXCHANGE, "OR_ISRULER_IRL_EXCHANGE" },
	{ OR_LEVEL_MONEY_MAXLIMIT, "OR_LEVEL_MONEY_MAXLIMIT" },
	{ OR_LEVEL_MONEY_LIMIT, "OR_LEVEL_MONEY_LIMIT" },
	{ OR_TRY_CATCH_RETURN, "OR_TRY_CATCH_RETURN" },
	{ OR_NULL_POINTER, "OR_NULL_POINTER" },
	{ OR_NULL_MAP, "OR_NULL_MAP" },
	{ OR_NEW_PET_ERROR, "OR_NEW_PET_ERROR" },
	{ OR_INIT_PET_ERROR, "OR_INIT_PET_ERROR" },
	{ OR_CANNOT_FIND_THIS_TYPE_PET, "OR_CANNOT_FIND_THIS_TYPE_PET" },
	{ OR_QUEST_IS_FULL, "OR_QUEST_IS_FULL" },
	{ OR_CANNOT_FIND_THIS_QUEST, "OR_CANNOT_FIND_THIS_QUEST" },
	{ OR_HAVENOT_LEARN_THIS_SKILL, "OR_HAVENOT_LEARN_THIS_SKILL" },
	{ OR_DONOT_HAVE_ENOUGH_SKILL_POINT, "OR_DONOT_HAVE_ENOUGH_SKILL_POINT" },
	{ OR_HAVENOT_LEARN_PARENT_SKILL, "OR_HAVENOT_LEARN_PARENT_SKILL" },
	{ OR_CANNOT_FIND_THIS_SKILL_IN_STUDY_TABLE, "OR_CANNOT_FIND_THIS_SKILL_IN_STUDY_TABLE" },
	{ OR_THIS_SKILL_IS_MAX_LEVEL, "OR_THIS_SKILL_IS_MAX_LEVEL" },
	{ OR_ABILITY_CANNOT_FIND_OWNER, "OR_ABILITY_CANNOT_FIND_OWNER" },
	{ OR_ABILITY_OWNER_ISNOT_HUMAN, "OR_ABILITY_OWNER_ISNOT_HUMAN" },
	{ OR_INVALID_ABILITY, "OR_INVALID_ABILITY" },
	{ OR_ABILITY_PROC_OVER_FAIL, "OR_ABILITY_PROC_OVER_FAIL" },
	{ OR_CHANGE_STATE_FAIL, "OR_CHANGE_STATE_FAIL" },
	{ OR_CHARACTER_IS_UNACTIVE, "OR_CHARACTER_IS_UNACTIVE" },
	{ OR_CHARACTER_IS_LIMIT_MOVE, "OR_CHARACTER_IS_LIMIT_MOVE" },
	{ OR_CHARACTER_DONOT_HAVE_DEST_POS, "OR_CHARACTER_DONOT_HAVE_DEST_POS" },
	{ OR_CHARACTER_CANNOT_MOVE_TO_DEST_POS, "OR_CHARACTER_CANNOT_MOVE_TO_DEST_POS" },
	{ OR_MOVE_ERROR, "OR_MOVE_ERROR" },
	{ OR_SKILL_STATE_ERROR, "OR_SKILL_STATE_ERROR" },
	{ OR_CANNOT_FIND_MOVE_PATH, "OR_CANNOT_FIND_MOVE_PATH" },
	{ OR_DEFAULT_ERROR, "OR_DEFAULT_ERROR" },
	{ OR_IS_ENEMY_CAMP, "OR_IS_ENEMY_CAMP" },
	{ OR_TEAM_FOLLOW_STATE, "OR_TEAM_FOLLOW_STATE" },
	{ OR_CANNOT_FIND_NPC, "OR_CANNOT_FIND_NPC" },
	{ OR_VARIFY_EVENT_ERROR, "OR_VARIFY_EVENT_ERROR" },
	{ OR_DONOT_HAVE_TEAM_LEADER, "OR_DONOT_HAVE_TEAM_LEADER" },
	{ OR_ABILITY_OPERATOR_BAG_POS_ERROR, "OR_ABILITY_OPERATOR_BAG_POS_ERROR" },
	{ OR_CREATE_ITEM_TO_BAG_ERROR, "OR_CREATE_ITEM_TO_BAG_ERROR" },
	{ OR_IS_PASSIVE_SKILL, "OR_IS_PASSIVE_SKILL" },
	{ OR_SCAN_ERROR, "OR_SCAN_ERROR" },
	{ OR_IN_FURY_STANCE, "OR_IN_FURY_STANCE" },
	{ OR_MS_InDancery, "OR_MS_InDancery" },
	{ OR_TALK_TOO_FAST, "OR_TALK_TOO_FAST" },
	{ OR_MS_BlackGold, "OR_MS_BlackGold" },
	{ OR_YOU_ARE_BEEN_DELATED_KING, "OR_YOU_ARE_BEEN_DELATED_KING" },
	{ OR_NOT_BIND_PWCARD, "OR_NOT_BIND_PWCARD" },
	{ OR_KING_IS_KILLED_TODAY, "OR_KING_IS_KILLED_TODAY" },
	{ OR_STALL_CHANGE_PRICE_TOTALERROR, "OR_STALL_CHANGE_PRICE_TOTALERROR" },
	
	//-- «‡¡˙°¢÷Ï»∏start
	{OR_YOU_ARE_THE_QINGLONG,"OR_YOU_ARE_THE_QINGLONG" }, 
	{OR_YOU_ARE_THE_ZHUQUE,"OR_YOU_ARE_THE_ZHUQUE" }, 
	{OR_YOU_MUSTBE_CHIEFTAIN_FOR_QINGLONG,"OR_YOU_MUSTBE_CHIEFTAIN_FOR_QINGLONG" }, 
	{OR_YOU_MUSTBE_CHIEFTAIN_FOR_ZHUQUE,"OR_YOU_MUSTBE_CHIEFTAIN_FOR_ZHUQUE" }, 
	{OR_KING_NOT_ALLOW_QINGLONG,"OR_KING_NOT_ALLOW_QINGLONG" }, 
	{OR_KING_NOT_ALLOW_ZHUQUE,"OR_KING_NOT_ALLOW_ZHUQUE" }, 
	{OR_GUILD_MEMBER_NOT_ENOUGH_FOR_QINGLONG,"OR_GUILD_MEMBER_NOT_ENOUGH_FOR_QINGLONG" }, 
	{OR_GUILD_MEMBER_NOT_ENOUGH_FOR_ZHUQUE,"OR_GUILD_MEMBER_NOT_ENOUGH_FOR_ZHUQUE" }, 
	{OR_GUILD_LEVEL_NOT_ENOUGH_FOR_QINGLONG,"OR_GUILD_LEVEL_NOT_ENOUGH_FOR_QINGLONG" }, 
	{OR_GUILD_LEVEL_NOT_ENOUGH_FOR_ZHUQUE,"OR_GUILD_LEVEL_NOT_ENOUGH_FOR_ZHUQUE" }, 
	{OR_ZHUQUE_NOT_ALLOW_QINGLONG,"OR_ZHUQUE_NOT_ALLOW_QINGLONG" }, 
	{OR_QINGLONG_NOT_ALLOW_ZHUQUE,"OR_QINGLONG_NOT_ALLOW_ZHUQUE" }, 
	//-- «‡¡˙°¢÷Ï»∏end
	
	{ OR_NOT_ENOUGH_RAGE_WUSHI, "OR_NOT_ENOUGH_RAGE_WUSHI" },
	{ OR_NOT_ENOUGH_RAGE_JIANXIA, "OR_NOT_ENOUGH_RAGE_JIANXIA" },
	{ OR_NOT_ENOUGH_RAGE_QISHE, "OR_NOT_ENOUGH_RAGE_QISHE" },
	{ OR_NOT_ENOUGH_RAGE_HUOQIANG, "OR_NOT_ENOUGH_RAGE_HUOQIANG" },
	{ OR_NOT_ENOUGH_RAGE_XIANZHI, "OR_NOT_ENOUGH_RAGE_XIANZHI" },
	{ OR_NOT_ENOUGH_RAGE_SAMAN, "OR_NOT_ENOUGH_RAGE_SAMAN" },
	{ OR_MAIL_TOO_FAST, "OR_MAIL_TOO_FAST" },
	{ OR_CONDITION_ERROR, "OR_CONDITION_ERROR" },
	
};

class			RetriveResultStrManager
{
/*
 -----------------------------------------------------------------------------------------------------------------------
 -----------------------------------------------------------------------------------------------------------------------
 */
protected:
	typedef std::map<int32, const char *>	COResultTextMap;
	COResultTextMap m_mapOResultText;

/*
 -----------------------------------------------------------------------------------------------------------------------
 -----------------------------------------------------------------------------------------------------------------------
 */
public:

	/*
	 ===============================================================================================================
	 ===============================================================================================================
	 */
	RetriveResultStrManager()
	{
		/*~~~~~~~~~~~*/
		int32 i, nSize;
		/*~~~~~~~~~~~*/

		nSize = sizeof(s_aResultText) / sizeof(SResultText);
		for(i = 0; i < nSize; i++)
		{
			m_mapOResultText.insert(COResultTextMap::value_type(s_aResultText[i].nCode, s_aResultText[i].pszText));
		}
	}

	/*
	 ===============================================================================================================
	 ===============================================================================================================
	 */
	~RetriveResultStrManager()
	{
		m_mapOResultText.erase(m_mapOResultText.begin(), m_mapOResultText.end());
	}

	/*
	 ===============================================================================================================
	 ===============================================================================================================
	 */
	LPCSTR GetOperateResultText(eOPTRESULT oResult)
	{
		/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
		static const char		*szOR_ERROR = "unkown error";
		COResultTextMap::iterator	itFind;
		/*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

		itFind = m_mapOResultText.find(oResult);
		if(itFind != m_mapOResultText.end())
		{
			return itFind->second;
		}
		else
		{
			return szOR_ERROR;
		}
	}
};

static RetriveResultStrManager g_ORTTextManager;

/*
 =======================================================================================================================
 =======================================================================================================================
 */

const char *GetORTText(eOPTRESULT code)
{
	return g_ORTTextManager.GetOperateResultText(code);
}
